# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "cd5fa172af484872820ffbb0d713985b"
  blueprint_name: "ArcRifleT1CH2_Item"
  name_key: "ef8f9814-937f-43ae-9c1f-33ca4445b833"
  name: "[Mezoa-Pattern] Arc Rifle"
  description_shared_key: "6144a427-d1af-4fd6-96b3-3f5f4748554a"
  description: "Whenever the wielder {g|Encyclopedia:HitSequenceGlossary}hits{/g} a target with the arc rifle, they also attack all targets within 2 cells of the main target."
  category: Basic
  family: Exotic
  classification: SniperRifle
  heavy: false
  two_handed: true
  min_damage: 13
  max_damage: 20
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 18
  ammo: 4
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "ArcRifle_AbilityFXSettings"
    fx_bp: "7ddfcc6c73c94d9c90a5843aafa07674"
    on_hit_actions: "6fd35e86996e4b729a0b98afd9fa265c"
    on_hit_action_name: "ArcRifleChain_AbilityAdditionalEffect"
    ap: 2
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "ArcRifle_AbilityFXSettings"
    fx_bp: "7ddfcc6c73c94d9c90a5843aafa07674"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - Ch02_ForgeWorldAndHeart: HeretekLogi"
  sources: "Unit - Ch05_ArcShip: ImmortalSkitariiAlpha_ArcShip"
  sources: "Unit - ExportedPregens: Sayonara_23_Cassia_ExportedPregen"
  sources: "Vendor - ExploratorChapter2_VendorTable_Base 55PF"
}
weapon {
  guid: "bf9d592fc8444f29a99e27486182afb6"
  blueprint_name: "ArcRifleT2_Item"
  name_key: "95ebde75-1af6-40f3-94be-3d4b533f0bf0"
  name: "Alpha\'s Arc Rifle"
  description_key: "2165bc9d-d02c-4c07-8695-7dfc17005b71"
  description: "On a successful {g|Encyclopedia:HitSequenceGlossary}hit{/g} with this weapon, the wielder also attacks all targets in a 4-cell radius around the target."
  category: Basic
  family: Exotic
  classification: SniperRifle
  heavy: false
  two_handed: true
  min_damage: 28
  max_damage: 32
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 16
  ammo: 4
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "ArcRifle_AbilityFXSettings"
    fx_bp: "7ddfcc6c73c94d9c90a5843aafa07674"
    on_hit_actions: "241f4886e71e434d9af3c1037bad3b03"
    on_hit_action_name: "ArcRifleT2Chain_AbilityAdditionalEffect"
    ap: 2
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "ArcRifle_AbilityFXSettings"
    fx_bp: "7ddfcc6c73c94d9c90a5843aafa07674"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - Test: TestRaritiesLoot"
}
weapon {
  guid: "89922abe7a3b4a1d9359ba7d316114fc"
  blueprint_name: "ArcRifle_Item"
  name_key: "e30f0954-c83e-4b7f-bfc5-c7a81e3b7377"
  name: "Arc Rifle"
  description_shared_key: "6144a427-d1af-4fd6-96b3-3f5f4748554a"
  description: "Whenever the wielder {g|Encyclopedia:HitSequenceGlossary}hits{/g} a target with the arc rifle, they also attack all targets within 2 cells of the main target."
  category: Basic
  family: Exotic
  classification: SniperRifle
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 15
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 18
  ammo: 4
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "ArcRifle_AbilityFXSettings"
    fx_bp: "7ddfcc6c73c94d9c90a5843aafa07674"
    on_hit_actions: "6fd35e86996e4b729a0b98afd9fa265c"
    on_hit_action_name: "ArcRifleChain_AbilityAdditionalEffect"
    ap: 2
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "ArcRifle_AbilityFXSettings"
    fx_bp: "7ddfcc6c73c94d9c90a5843aafa07674"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - CR10: Forest_GoodLoot2"
  sources: "Unit - ExportedPregens: CassiaCompanion_level27_VasyaParty_ExportedPregen"
}
weapon {
  guid: "f75f6f41fdc74a7ba6ce177964dbed4e"
  blueprint_name: "ArcRifleCH4Unique_Item"
  name_key: "355f0a94-fdda-46ad-b120-01795e360d53"
  name: "Corpuscarii Oath"
  description_key: "32bf6b17-e1b6-4968-b07b-9e2bb92f9c74"
  description: "Enemies that are {g|Encyclopedia:HitSequenceGlossary}hit{/g} by this weapon suffer an irradiated effect that lasts for 3 {g|Encyclopedia:Turn}turns{/g}, decreasing all healing received by \342\210\22250%. Also prevents using <b>Reanimation Protocol</b> for 3 {g|Encyclopedia:Round}rounds{/g}."
  category: Basic
  family: Exotic
  classification: SniperRifle
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 40
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 20
  ammo: 4
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "ArcRifle_AbilityFXSettings"
    fx_bp: "7ddfcc6c73c94d9c90a5843aafa07674"
    on_hit_actions: "6fd35e86996e4b729a0b98afd9fa265c"
    on_hit_action_name: "ArcRifleChain_AbilityAdditionalEffect"
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "8cb88e846905485cac386809c7767139"
  extra_fact_name: "ArcRifleCH4Unique_Feature"
  sources: "Chest - CR0: Forest_SslythSkinLoot"
}

