# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "96454b5f89a44a24baca3a940991f7a2"
  blueprint_name: "AutoCannon_Item"
  name_shared_key: "41dfadd4-f930-4548-a2bc-fecbe88bda4b"
  name: "Heavy Enforcer Autocannon"
  description_key: "8b404abc-0119-44c8-900d-01646b1895f2"
  description: "Targets hit with this weapon must pass a Toughness resistance test with a \342\210\22210 penalty or be {g|Encyclopedia:PushGlossary}pushed{/g} 2 cells away."
  category: Heavy
  family: Solid
  heavy: true
  two_handed: true
  min_damage: 10
  max_damage: 11
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 50
  max_range: 24
  ammo: 100
  rate_of_fire: 7
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_actions: "a921b4f94b694101a6852d5f884fd98d"
    on_hit_action_name: "AutoCannon_PushAbilityAdditionalEffect"
    ap: 2
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_actions: "a921b4f94b694101a6852d5f884fd98d"
    on_hit_action_name: "AutoCannon_PushAbilityAdditionalEffect"
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "HeavyBolter_BoltShot_AbilityFXSettings"
    fx_bp: "86dda65e384f4ecc9bc2cdf3e6ad06e7"
    on_hit_action_name: ""
    ap: 4
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
}
weapon {
  guid: "1152a4e51ee7456e922ac8be387f14fb"
  blueprint_name: "Autogun10test_Item"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 10
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 16
  ammo: 1000
  rate_of_fire: 6
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - ArgentaCompanion: SoldierQA_lvl15"
  sources: "Unit - ArgentaCompanion: SoldierQA_lvl4"
  sources: "Unit - CassiaCompanion: LeaderNavigatorOverseer_lvl15"
  sources: "Unit - CassiaCompanion: LeaderNavigatorQA_lvl15"
  sources: "Unit - CassiaCompanion: LeaderNavigatorQA_lvl4"
  sources: "Unit - HeinrixCompanion: FighterPsykerQA_lvl15"
  sources: "Unit - HeinrixCompanion: FighterPsykerQA_lvl4"
  sources: "Unit - IdiraCompanion: AdeptPsykerQA_lvl4"
}
weapon {
  guid: "6b4f1321cd6e4f919bd19059def2799c"
  blueprint_name: "AutogunM40_Item"
  name_key: "aa58dd27-e7a3-4e33-8e54-e0d31128acf1"
  name: "[Civitas Pattern] Autogun"
  description_shared_key: "8f4bcd02-d3ce-450a-9ee8-ba61a3b7b90a"
  description: "Solid projectile weapons have an increased (+50%) {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g}."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 5
  max_damage: 8
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 24
  ammo: 24
  rate_of_fire: 7
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - CR15: AdeptusMechanicus_LootChest_RebelStash"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldRebelArmoured"
  sources: "Unit - Ch02_AgriWorldTown: Corrupted_GovernorGuard"
  sources: "Unit - Ch02_AgriWorldTown: GovernorGuard_TrailerCinematicM40"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditRingleaderWarehouse"
  sources: "Unit - Ch02_Lair3: Lair3RebelRangedAutogun"
  sources: "Unit - Ch03_Prison: ImperialMale_Gladiator"
  sources: "Unit - Ch02_FootfallSlums: SlumsMutantGuard"
  sources: "Unit - Ch02_LowerDecks: GuardLeader"
  sources: "Unit - Units: BoardedShip_Pirate_Gunner_Common_Unit"
  sources: "Unit - FootfallAtrium: SideQuestSlyOfficial1"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level7_EtelParty_ExportedPregen"
  sources: "Unit - ExportedPregens: ArgentaCompanion_Level29_ExportedPregen"
}
weapon {
  guid: "25ae34851bc544728146abb51a976ee6"
  blueprint_name: "AutogunRapid_Item"
  name_key: "3688a5c5-2e32-4a76-9760-ddd140efa0aa"
  name: "Rapid-Fire Autogun"
  description_shared_key: "8f4bcd02-d3ce-450a-9ee8-ba61a3b7b90a"
  description: "Solid projectile weapons have an increased (+50%) {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g}."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 7
  max_damage: 10
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 16
  ammo: 24
  rate_of_fire: 8
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - Ch02_RogueTraderPalace: InquisitorSoldier_Boarding"
  sources: "Unit - Ch04_Canteena: Ch04Chorda_RangeSpecialist_unit"
  sources: "Unit - CassiaCompanion: CassiaCompanion_Ch03_TrueStart"
}
weapon {
  guid: "439720b238c94780ac50ae3270673471"
  blueprint_name: "AutogunT2CH1_Item"
  name_key: "1031fb7f-50f2-4e6a-887b-1686771cdd05"
  name: "[Mezoa-Pattern] Autogun"
  description_shared_key: "8f4bcd02-d3ce-450a-9ee8-ba61a3b7b90a"
  description: "Solid projectile weapons have an increased (+50%) {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g}."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 3
  max_damage: 6
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 16
  ammo: 24
  rate_of_fire: 6
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - DLC1_Ch02_VoidshipCrypt: GenestealerAutogun_Ranged_VoidshipCrypt"
  sources: "Unit - Units: BoardedShip_Pirate_Gunner_Swarm_Unit"
  sources: "Vendor - PirateChapter1_VendorTable_Base 9PF"
}
weapon {
  guid: "ff30bc4470f5496c8d29818da6c6931e"
  blueprint_name: "Autogun_Item"
  name_shared_key: "be7dd76c-dff7-4e0d-b001-0128e59d9913"
  name: "Autogun"
  description_shared_key: "8f4bcd02-d3ce-450a-9ee8-ba61a3b7b90a"
  description: "Solid projectile weapons have an increased (+50%) {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g}."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 3
  max_damage: 5
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 16
  ammo: 24
  rate_of_fire: 6
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - CR12: Forest_Cube (2)"
  sources: "Chest - DrukhariAttackOnShip: DrukhariAttack_WeaponLootAutogun"
  sources: "Chest - FootFallDock: Loot_Uniq - puzzle"
  sources: "Chest - CR22: AdeptusMechanicus_OutdorWeaponCrate"
  sources: "Chest - LowerTunnels: ImperiumMilitary_PoorLootBig (10)"
  sources: "Unit - Ch01_JailPlanetoid: JailPlanetoidArturGuardF"
  sources: "Unit - Ch01_JailPlanetoid: JailPlanetoidEnforcerBurst"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_CassiaRoom"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_CassiaRoomFemale"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Medic"
  sources: "Unit - Ch02_AdministratumPalace: AdministratumEnforcer"
  sources: "Unit - Ch02_FootFallSlums: FootfallBanditInfectedRanged"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedTechPriest"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedTechPriestAutogun"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedTechPriestBlindGrenade"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedTechPriestFragGrenade"
  sources: "Unit - Ch02_ForgeWorldAndHeart: HeretekMagiUralonSidekick2"
  sources: "Unit - Ch02_Lair1: CultistRangeLair1_Bark"
  sources: "Unit - Ch02_Lair1: CultistRangeLair2"
  sources: "Unit - Ch02_Lair3: Lair3RebelRanged"
  sources: "Unit - Ch02_RandomEncounters: AltGoals_CrazyTechPriest"
  sources: "Unit - Ch02_RandomEncounters: CrazyTechPriestRandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: CultistRangeKhorneRandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: CultistRangeKhorneRandomEncounter_NoGrenades"
  sources: "Unit - Ch02_RandomEncounters: OfficerRangedRandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: PossessedEnginseer"
  sources: "Unit - Ch02_RandomEncounters: PossessedTechPriestBlindGrenadeRandomEncounter"
  sources: "Unit - Ch04_LairCliff: ChaosCultist_Ritualist"
  sources: "Unit - Ch04_LairCliff: ChaosCultist_Sniper"
  sources: "Unit - Ch04_Janus_ChapterStart: OldMan"
  sources: "Unit - Ch04: Footfall_ChordaEnforcer5"
  sources: "Unit - Companions: CompanionPascalPrototype"
}
weapon {
  guid: "a50db54c76a44ac9a8986c8a602d66b4"
  blueprint_name: "CalibratedHeavyStubber_Item"
  name_key: "cd751964-d459-4403-af29-5d963cc366c3"
  name: "Calibrated Heavy Stubber"
  category: Heavy
  family: Solid
  heavy: true
  two_handed: true
  min_damage: 3
  max_damage: 6
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 50
  max_range: 18
  ammo: 156
  rate_of_fire: 12
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 60
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Vendor - LiegeChapter2_VendorTable_Base 35PF"
}
weapon {
  guid: "bc7201bf17ed4a8cb5018c83a05ff630"
  blueprint_name: "HeavyEqualizer_HeavyStubber_Item"
  name_shared_key: "af32975e-ba1a-419a-93e6-9c6cb38570af"
  description_shared_key: "ddbaf9c9-ffb0-48da-a2a7-e7a2b8937be7"
  description: "This weapon deals additional damage equal to the target\'s difficulty tier."
  category: Heavy
  family: Solid
  heavy: true
  two_handed: true
  min_damage: 5
  max_damage: 7
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 35
  max_range: 18
  ammo: 120
  rate_of_fire: 10
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "HeavyBolter_BoltShot_AbilityFXSettings"
    fx_bp: "86dda65e384f4ecc9bc2cdf3e6ad06e7"
    on_hit_action_name: ""
    ap: 4
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "fce6b66a0004487d89967d9320695c64"
  extra_fact_name: "HeavyEqualizer_HeavyStubber_Feature"
}
weapon {
  guid: "053074cada484310a920573477ebc7ed"
  blueprint_name: "HeavyStubber_Item"
  name_shared_key: "f66d5e29-7428-419b-a4fe-91506460b0bf"
  name: "Righteous Anger"
  category: Heavy
  family: Solid
  heavy: true
  two_handed: true
  min_damage: 4
  max_damage: 7
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 40
  max_range: 18
  ammo: 120
  rate_of_fire: 10
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "HeavyBolter_BoltShot_AbilityFXSettings"
    fx_bp: "86dda65e384f4ecc9bc2cdf3e6ad06e7"
    on_hit_action_name: ""
    ap: 4
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - CR33: ImperiumMilitary_PrisonPitTrashWeapon"
  sources: "Chest - TheLure_Lair4: Loot_Good_RelicChest"
  sources: "Unit - DLC2_CH01_StarPort: ArbitratorClayton_Stubber"
}
weapon {
  guid: "8b204cf8f3c24a05a902d6b890e38daf"
  blueprint_name: "ScrappyAutogun_Item"
  name_key: "06b3d817-5ec2-4bf2-b3b5-0e5993e1d5dd"
  name: "Scrappy Autogun"
  description_shared_key: "8f4bcd02-d3ce-450a-9ee8-ba61a3b7b90a"
  description: "Solid projectile weapons have an increased (+50%) {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g}."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 3
  max_damage: 5
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 16
  ammo: 24
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - Ch00_OfficersDeck: CultistPirate_Ranged_ArgentaFight"
  sources: "Unit - Ch00_OfficersDeck: CultistPirate_Ranged_OfficersDeck"
  sources: "Unit - Ch01_Starport: StarportRebelRangeSwarm1"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsCultistRangedHeavy"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsRebel"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsRebelRangedHeavy"
  sources: "Unit - Ch02_FootfallDock: FootfallAnver_MeleeRanged_SwarmQS"
  sources: "Unit - DLC1_LowerTunnels: RebelMutantRangedCH02_Swarm"
}
weapon {
  guid: "5febd01fd8574d37be99680f16e3f094"
  blueprint_name: "Spinup_HeavyStubber_Item"
  name_shared_key: "f66d5e29-7428-419b-a4fe-91506460b0bf"
  name: "Righteous Anger"
  description_shared_key: "963ab037-6814-4c70-b715-8fb8edcd7112"
  description: "Whenever the wielder makes a {g|Encyclopedia:BurstAttacksGlossary}burst{/g} attack with this weapon, its {g|Encyclopedia:RateOfFire}rate of fire{/g} is increased by +2 (up to a maximum of +10). Stacks and lasts until the end of combat."
  category: Heavy
  family: Solid
  heavy: true
  two_handed: true
  min_damage: 9
  max_damage: 12
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 50
  max_range: 20
  ammo: 120
  rate_of_fire: 5
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "HeavyBolter_BoltShot_AbilityFXSettings"
    fx_bp: "86dda65e384f4ecc9bc2cdf3e6ad06e7"
    on_hit_action_name: ""
    ap: 4
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "a4b1c2f8197c458994ad8092378b506f"
  extra_fact_name: "Spinup_HeavyStubber_Feature"
  sources: "Unit - DLC2_Ch04_TreasureWorld: TreasureWorld_Arbites_Leader"
}
weapon {
  guid: "64914940171c44eaaeaab968c13c6a3f"
  blueprint_name: "StandartAutoCannon_Item"
  name_shared_key: "12850e94-d0bd-44d7-8b27-75b4cefafcb4"
  name: "Stolen Autocannon"
  category: Heavy
  family: Solid
  heavy: true
  two_handed: true
  min_damage: 4
  max_damage: 6
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 50
  max_range: 16
  ammo: 100
  rate_of_fire: 8
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "AutoCannonShot_AbilityFXSettings"
    fx_bp: "3285473dec4d46a0b8e599dae31dae9a"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "AutoCannonShot_AbilityFXSettings"
    fx_bp: "3285473dec4d46a0b8e599dae31dae9a"
    on_hit_action_name: ""
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "HeavyBolter_BoltShot_AbilityFXSettings"
    fx_bp: "86dda65e384f4ecc9bc2cdf3e6ad06e7"
    on_hit_action_name: ""
    ap: 4
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - LowerTunnels: ImperiumMilitary_PoorLootBig (10)"
}
weapon {
  guid: "7cc2fdbab097461ea87efe6a5ba303b0"
  blueprint_name: "TrapAutogun_Item"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 6
  max_damage: 9
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 16
  ammo: 24
  rate_of_fire: 6
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_TrapAbility"
    ability_bp: "417a57aa5eb04c5cbba400354987ba41"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
}
weapon {
  guid: "81861b35110b4958893237d6e73b4fba"
  blueprint_name: "AutogunCultistCH4Unique_Item"
  name_key: "15356563-4a30-4414-8652-bb0580ab63ef"
  name: "Eroding Autogun"
  description_key: "d4ec1afd-ce35-4275-be7c-7708a4bf3657"
  description: "Targets hit by this autogun suffer +20% more toxic damage until the end of combat."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 12
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 16
  ammo: 32
  rate_of_fire: 8
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Vendor - PirateChapter4_VendorTable_Base 101PF"
}
weapon {
  guid: "f1195e80325d4430922123f0b8480ba8"
  blueprint_name: "AutogunT2CH04_Item"
  name_shared_key: "be7dd76c-dff7-4e0d-b001-0128e59d9913"
  name: "Autogun"
  description_shared_key: "8f4bcd02-d3ce-450a-9ee8-ba61a3b7b90a"
  description: "Solid projectile weapons have an increased (+50%) {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g}."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 6
  max_damage: 10
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 16
  ammo: 24
  rate_of_fire: 8
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - DLC1_LowerTunnels: InfernusCH04LTState2_Ranged_Swarm"
  sources: "Unit - DLC1_LowerTunnels_StreetFight: GenestealerAutogun_Ranged_LowerTunnels"
}
weapon {
  guid: "98d6a0b61db04f3aba0ac0e735e7096d"
  blueprint_name: "ExperimentalAssaultRifle_Item"
  name_key: "ef5d2a13-cd14-4edc-93ba-9a629afd48ef"
  name: "Experimental Assault Rifle"
  description_key: "224d494c-971d-4e9c-b4b7-65e5f71c93da"
  description: "This rifle has 3 different {g|Encyclopedia:BurstAttacksGlossary}burst{/g} attacks with different {g|Encyclopedia:RateOfFire}rate of fire{/g} and {g|Encyclopedia:DamageGlossary}damage{/g}. Each {g|Encyclopedia:Round}round{/g} only one of these burst attacks is available, determined randomly."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 11
  max_damage: 19
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 5
  recoil: 15
  max_range: 16
  ammo: 30
  rate_of_fire: 7
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "ExperimentalAssaultRifle_BurstFirePowerful_Ability"
    ability_bp: "c40fc0042b774fc3ad30dbcf6babbb1e"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Burst
    ability_bp_name: "ExperimentalAssaultRifle_BurstFireRapid_Ability"
    ability_bp: "8bcff2d4e9b0479ca592ac29c579b7f4"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Burst
    ability_bp_name: "ExperimentalAssaultRifle_BurstFireVolatile_Ability"
    ability_bp: "2c1afe3a847f4985871c7319d5f72876"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability5 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "f8102bce2d854d409a00368fc7e80deb"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ExperimentalAssaultRifle_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
}
weapon {
  guid: "cf9f36e4834147e88f2f1b79363e8d64"
  blueprint_name: "ModifiedAutogun_Item"
  name_key: "4d0990fc-5678-45c8-a576-a3492b0b5bf9"
  name: "[Orthlack-Pattern] Autogun"
  description_shared_key: "8f4bcd02-d3ce-450a-9ee8-ba61a3b7b90a"
  description: "Solid projectile weapons have an increased (+50%) {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g}."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 6
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 16
  ammo: 32
  rate_of_fire: 8
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - CR17: ImperiumMilitary_Good1"
}
weapon {
  guid: "7c25fe227e9a4e8ebe152349853eb083"
  blueprint_name: "Ripper_Autogun_Item"
  name_key: "5068b79b-78d2-4570-8bd1-1e52a9875613"
  name: "The Ripper"
  description_shared_key: "8f4bcd02-d3ce-450a-9ee8-ba61a3b7b90a"
  description: "Solid projectile weapons have an increased (+50%) {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g}."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 5
  max_damage: 7
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 16
  ammo: 32
  rate_of_fire: 8
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - LowerTunnels: Military_Loot_Good"
  sources: "Unit - Ch03_CommorraghArena: HumanGladiator_Ranged_Arena_01"
  sources: "Unit - ExportedPregens: ArgentaCompanion_Level15_ExportedPregen"
}
weapon {
  guid: "594030b15093416c925dabc415eda101"
  blueprint_name: "Chapter4_Unique_UncoverHeavyStubber_Item"
  name_shared_key: "3214d173-dcfb-42a8-917a-fa6e21ddbc26"
  name: "Advanced Heavy Stubber"
  description_shared_key: "32ec41db-5f07-4e15-ba60-e04eaeb89f63"
  description: "Destructible {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} {g|Encyclopedia:HitSequenceGlossary}hit{/g} by this stubber is instantly destroyed. Both destructible and indestructible covers are automatically overpenetrated."
  category: Heavy
  family: Solid
  heavy: true
  two_handed: true
  min_damage: 10
  max_damage: 11
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 50
  max_range: 20
  ammo: 80
  rate_of_fire: 10
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "HeavyBolter_BoltShot_AbilityFXSettings"
    fx_bp: "86dda65e384f4ecc9bc2cdf3e6ad06e7"
    on_hit_action_name: ""
    ap: 4
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "dda482cc9bcb4f978d191b992c3e8885"
  extra_fact_name: "Chapter4_Unique_UncoverHeavyStubber_Feature"
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 145PF"
}

