# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "9715c0f5d59e4b7f91089ed18a96fd42"
  blueprint_name: "AccursedCrozius_Item"
  name_key: "eaf4006b-f5d5-4c04-971a-e73b64f6295b"
  description_key: "eb4526ad-4e9d-4321-93d6-b692fbcdb3b8"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 15
  max_damage: 20
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "TwoHandedAxeAoEAbility"
    ability_bp: "89340adeac4b4d189ade9ebf872b5e4d"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  extra_fact: "c895de107e9a4905aceec086c3593dbf"
  extra_fact_name: "AccursedCrozius_Feature"
  sources: "Unit - Ch02_ForgeWorldAndHeart: DarkApostleMob"
}
weapon {
  guid: "e9186ff71fd5477c9bbf092ba1600018"
  blueprint_name: "AstartesChainAxeT2_Item"
  name_shared_key: "4eb49a88-7f56-4df8-b67b-cbaff6d627ee"
  name: "Rending Chainaxe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Chain
  heavy: false
  two_handed: false
  min_damage: 30
  max_damage: 40
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: true
    negate: false
    bp: "950565a69d144391897cdc0024747755"
    bp: "9eeb3cc7064e407ba025c8adf2b4d5e9"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "CorruptionSoulMark_3"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Unit - Ch04_Eufrates: EufratesCSM_Melee_unit"
}
weapon {
  guid: "c225669f42784fe5852fe134e2768b56"
  blueprint_name: "AstartesChainAxe_Item"
  name_key: "a05428bd-3690-4690-899d-12b55fa773d0"
  name: "Astartes Chainaxe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Chain
  heavy: false
  two_handed: false
  min_damage: 12
  max_damage: 18
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: true
    negate: false
    bp: "950565a69d144391897cdc0024747755"
    bp: "fb7efcba2dcc427da2324d4066daf2d5"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "CorruptionSoulMark_1"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Unit - Ch02_Lair1: ChaosSpacemarineLair1"
  sources: "Unit - Ch02_ForgeWorldAndHeart: ChaosSpacemarineMelee"
  sources: "Unit - Ch04_Eufrates: CSM_MeleeRanged_UlfarQuest"
}
weapon {
  guid: "524fea4803af43f4beebc5bd3bccf797"
  blueprint_name: "Axe10test_Item"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Primitive
  heavy: false
  two_handed: false
  min_damage: 10
  max_damage: 10
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  extra_fact: "232ae3bb3ca04d27bdc5ea57156d629e"
  extra_fact_name: "Bleeding_Power6_ForWeapon_Feature"
  sources: "Unit - ArgentaCompanion: SoldierQA_lvl15"
  sources: "Unit - ArgentaCompanion: SoldierQA_lvl4"
  sources: "Unit - CassiaCompanion: LeaderNavigatorOverseer_lvl15"
  sources: "Unit - CassiaCompanion: LeaderNavigatorQA_lvl15"
  sources: "Unit - CassiaCompanion: LeaderNavigatorQA_lvl4"
  sources: "Unit - HeinrixCompanion: FighterPsykerQA_lvl15"
  sources: "Unit - HeinrixCompanion: FighterPsykerQA_lvl4"
  sources: "Unit - IdiraCompanion: AdeptPsykerQA_lvl4"
}
weapon {
  guid: "5b25633243174fb4a89716c40759796b"
  blueprint_name: "AxeT1Tutorial_Item"
  name_key: "03ec01c2-002a-46b1-a60c-0ec2f2727b2b"
  name: "Well-Maintained Axe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Primitive
  heavy: false
  two_handed: false
  min_damage: 6
  max_damage: 8
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "5eb5a4a6eda440cca04b7e1b89d768ce"
  extra_fact_name: "Bleeding_Power2_ForWeapon_Feature"
}
weapon {
  guid: "f35413e7022d462f944572b13c43c78f"
  blueprint_name: "AxeT2CH04_Item"
  name_shared_key: "61bfec02-4d12-4abe-a255-00826cd559b1"
  name: "Bleeder Axe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Primitive
  heavy: false
  two_handed: false
  min_damage: 14
  max_damage: 22
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "2dd9bfa29e1140a8a98f7d4140f74074"
  extra_fact_name: "Bleeding_Power8_ForWeapon_Feature"
  sources: "Unit - DLC1_LowerTunnels: InfernusCH04LTState2_Melee_Swarm"
}
weapon {
  guid: "b5bad5e8104d4b928dc13fdb10a5e8ec"
  blueprint_name: "AxeT2_Item"
  name_key: "6afc7c5b-7931-4e4a-acce-e29a9835451f"
  name: "Weighty Axe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Primitive
  heavy: false
  two_handed: false
  min_damage: 7
  max_damage: 11
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "8f2969f253c844ee8ee2f5f447cd98ec"
  extra_fact_name: "Bleeding_Power4_ForWeapon_Feature"
  sources: "Chest - Test: TestRaritiesLoot"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldRebelMelee"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldRebelMeleeCharge"
  sources: "Unit - Ch02_FootFallAtrium: FootfallAnverCutterFrenzy_Melee_Common"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverCharger_Melee_Swarm"
  sources: "Unit - Ch02_FootfallDock: FootfallAnver_MeleeRanged_Common"
  sources: "Unit - Ch02_Lair3: Lair3RebelMeleeAxe"
  sources: "Unit - Ch04_VoidshipBridgeBoarding: InquisitorBrute_Melee_Boarding"
  sources: "Unit - Ch05_ArcShip: TechpriestLogos_MeleeRanged_PasqualQuest"
}
weapon {
  guid: "b61740707f6b477f9ed139b22a81d245"
  blueprint_name: "Axe_Item"
  name_shared_key: "d288657d-ca7c-4758-b9f4-7deb6086e292"
  name: "Axe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Primitive
  heavy: false
  two_handed: false
  min_damage: 5
  max_damage: 7
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "5eb5a4a6eda440cca04b7e1b89d768ce"
  extra_fact_name: "Bleeding_Power2_ForWeapon_Feature"
  sources: "Chest - CR0: SantielUnderhiveCannibals02"
  sources: "Chest - CR33: ImperiumMilitary_PrisonPitTrashWeapon"
  sources: "Chest - JailPlanetoid: Loot_Poor_Locked  - Arsenal"
  sources: "Unit - Ch00_OfficersDeck: CultistPirate_Melee_OfficersDeck"
  sources: "Unit - Ch01_JailPlanetoid: JailPlanetoidCorruptedPrisoner"
  sources: "Unit - Ch02_FootFallAtrium: FootfallAnverCutterNimble_Melee_Common"
  sources: "Unit - Ch02_FootfallDock: FootfallAnver_MeleeRanged_Swarm"
  sources: "Unit - Ch02_FootfallDock: FootfallAnver_MeleeRanged_SwarmQS"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditPeacefull1"
  sources: "Unit - Ch02_FootfallDock: FootfallBandit_Quicksilver"
  sources: "Unit - Ch02_FootfallDock: FootfallBandit_Quicksilver2"
  sources: "Unit - Ch02_FootfallDock: FootfallPeacefullBandit"
  sources: "Unit - Ch02_FootfallDock: FootfallSuspiciousType"
  sources: "Unit - Ch02_FootfallDock: Footfall_JaeCanteenaSceneBandit1"
  sources: "Unit - Ch02_FootfallDock: Footfall_JaeCanteenaSceneBandit2"
  sources: "Unit - Ch02_FootfallDock: JaeGuard"
  sources: "Unit - Ch02_FootfallDock: JaeGuard_Kor"
  sources: "Unit - Ch02_FootfallDock: JaeGuard_Torra"
  sources: "Unit - Ch02_RandomEncounters: CultistMeleeKhorneRandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: CultistMeleeKhorneRandomEncounter_NoGrenades"
  sources: "Unit - Ch02_RogueTraderPalace: GladiatorWAxe"
  sources: "Unit - Ch02_SantielsPrideUnderhive: WildCannibalMelee"
  sources: "Unit - Ch04_FootfallSewersCh04: FootfallSewersPatrol"
  sources: "Unit - Ch04_FootfallSewersCh04: FootfallSewersPatrol1"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_Miner1"
  sources: "Unit - Ch02_FootfallSlums: SlumsMutantFighter"
  sources: "Unit - Ch02_RandomEncounters: NurgleAmbushZombieFlak_RandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: NurgleZombieSwarm01_RandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: RE_DemonTransform_Grunt"
  sources: "Unit - Ch02_RandomEncounters: RE_DemonTransform_NurgleBuboe"
  sources: "Unit - Ch02_RandomEncounters: RE_DemonTransform_NurgleZombie"
  sources: "Unit - Ch02_RandomEncounters: RE_PossessedOfficer_Flamer"
  sources: "Unit - Ch04_TheDoor: HaemonculusClone"
  sources: "Unit - Ch01_JailPlanetoid: JailPlanetoidEnforcerButcher"
  sources: "Unit - Ch01_JailPlanetoid: JailPlanetoidEnforcerButcher"
  sources: "Unit - DLC1_LowerTunnels_BlessedbyNurgle: LT_HumanNurgleFollowerExplosive_Melee_Hard"
  sources: "Unit - FootfallSlums: SuicideVladaimAgent"
  sources: "Unit - ExportedPregens: PlayerRT_Level7_EtelParty_ExportedPregen"
}
weapon {
  guid: "91b1727798054d60bb05ad9503ebb9c8"
  blueprint_name: "BreacherAxe_Item"
  name_key: "4c698a0c-2fb6-4bf5-ac77-b821040d170c"
  category: Melee
  family: Power
  heavy: false
  two_handed: true
  min_damage: 15
  max_damage: 20
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "TwoHandedAxeAoEAbility"
    ability_bp: "89340adeac4b4d189ade9ebf872b5e4d"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  extra_fact: "232ae3bb3ca04d27bdc5ea57156d629e"
  extra_fact_name: "Bleeding_Power6_ForWeapon_Feature"
}
weapon {
  guid: "591e5e582c8e406aa2b89ada1e38dcc0"
  blueprint_name: "ChainAxeT2CH02_Item"
  name_shared_key: "b2f9c6f4-9131-41b5-9287-2915710fed56"
  name: "Chainaxe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Chain
  heavy: false
  two_handed: false
  min_damage: 14
  max_damage: 20
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "232ae3bb3ca04d27bdc5ea57156d629e"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Bleeding_Power6_ForWeapon_Feature"
  sources: "Unit - Ch02_VoidshipOfficersDeck: GenestealerBrute_Melee_PatriarchVisions"
  sources: "Unit - DLC1_Ch02_VoidshipCrypt: GenestealerPickPistol_MeleeRanged_VoidshipCrypt"
  sources: "Unit - Ch02_DaringHeirGuttedShip: ShipServicemanMutantExplosive_Melee_Hard"
  sources: "Unit - DLC2_BoardedShip_Bridge: BoardedShip_OfficerMelee_Elite"
  sources: "Unit - Ch02_ForgeWorld: Fabricator"
  sources: "Unit - ExportedPregens: AbelardCompanion_level27_VasyaParty_ExportedPregen"
}
weapon {
  guid: "e7ecf796ee0c45a5bd74afbb8c94236f"
  blueprint_name: "ChainAxeT2CH03_Item"
  name_shared_key: "130c76d0-adfd-4bbf-9535-fac57aba8f4c"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Chain
  heavy: false
  two_handed: false
  min_damage: 16
  max_damage: 24
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "2dd9bfa29e1140a8a98f7d4140f74074"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Bleeding_Power8_ForWeapon_Feature"
}
weapon {
  guid: "f25530c2b1ce48068662f7c8ef8414b2"
  blueprint_name: "ChainAxeT2CH4_Item"
  name_shared_key: "b75e3116-953b-4f37-8ab9-8d5a11e4b5df"
  name: "Hardened Chainaxe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Chain
  heavy: false
  two_handed: false
  min_damage: 17
  max_damage: 25
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: false
    bp: "9eeb3cc7064e407ba025c8adf2b4d5e9"
    bp_name: "CorruptionSoulMark_3"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Chest - CR18: Lair3_GoodLootHidden"
}
weapon {
  guid: "43bec0b433d84bfb8bf98e8e87423145"
  blueprint_name: "ChainAxe_Item"
  name_shared_key: "b2f9c6f4-9131-41b5-9287-2915710fed56"
  name: "Chainaxe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Chain
  heavy: false
  two_handed: false
  min_damage: 10
  max_damage: 16
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "232ae3bb3ca04d27bdc5ea57156d629e"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Bleeding_Power6_ForWeapon_Feature"
  sources: "Unit - Ch02_FootFallAtrium: FootfallAnverAvangeMeLeader_Melee_Elite"
  sources: "Unit - Ch02_FootFallAtrium: FootfallAnverChange_MeleeRanged_Common"
  sources: "Unit - Ch02_ForgeWorldAndHeart: ForgeWorld_Cultist_Melee"
  sources: "Unit - DLC1_Ch02_VoidshipCrypt: Infernus_Melee_VoidshipCrypt"
  sources: "Unit - Units: BoardedShip_Pirate_Melee_Common_Unit"
  sources: "Unit - ExportedPregens: Argenta19Chapel_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_level27_VasyaParty_ExportedPregen"
  sources: "Unit - ExportedPregens: Yanus19Jae_ExportedPregen"
}
weapon {
  guid: "d87025713376453b97a5174fc08edbfb"
  blueprint_name: "ChainGreatAxe_Item"
  name_shared_key: "c21a08f9-75ee-4b4b-b353-90e776ece364"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Chain
  heavy: false
  two_handed: false
  min_damage: 14
  max_damage: 28
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "232ae3bb3ca04d27bdc5ea57156d629e"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Bleeding_Power6_ForWeapon_Feature"
  sources: "Unit - ExportedPregens: Executioner_ForMarketing_Pregen_ExportedPregen"
}
weapon {
  guid: "8d59fc3881114d1fbf81c62981211bdc"
  blueprint_name: "Fabricator_OmnissiahAxe_LootItem"
  name_shared_key: "1648449c-9730-476c-81f2-5509448b7937"
  name: "[Kiava Gamma Pattern] Omnissian Axe"
  category: Melee
  family: Power
  heavy: false
  two_handed: true
  min_damage: 18
  max_damage: 28
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OmnissiahAxeTwoHandedAxe_Ability"
    ability_bp: "5e35e29dfa8e4133a9d10b3070d20c0b"
    fx_bp_name: "OmnissiahAxe_AoE_AbilityFXSettings"
    fx_bp: "12258b3764a3417baf819b851360ac2b"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "fb02c043f8e84ae1b777779e75fa4cd2"
  extra_fact: "8f2969f253c844ee8ee2f5f447cd98ec"
  extra_fact_name: "WeaponSkill15_Feature"
  extra_fact_name: "Bleeding_Power4_ForWeapon_Feature"
}
weapon {
  guid: "67db0f23724442fbae91a21191114c54"
  blueprint_name: "FrostAxe_Item"
  name_shared_key: "294c574d-18ff-4978-b514-9b4ddc1b93cf"
  name: "Grin of the Iron Wolf"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Power
  heavy: false
  two_handed: false
  min_damage: 30
  max_damage: 45
  penetration: 50
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Unit - Ch05_Epitaph: Ch05Inquisitor_Ulfar_unit"
  sources: "Unit - Ch02_ForgeWorldAndHeart: RegindSpacewolfMarine_Melee"
  sources: "Unit - Ch03_CommorraghArena: CommorraghArenaUlfar"
  sources: "Unit - Ch04_Eufrates: Halbrandt_MeleeRanged_UlfarQuest"
  sources: "Unit - Ch05_UlfarQ2: GhostSpaceMarine_Bolter_Ranged_UlfarQ2"
  sources: "Unit - Ch05_UlfarQ2: GhostSpaceMarine_ChainSword_Melee_UlfarQ2"
  sources: "Unit - SpaceMarineFight: Spacemarine_axe"
  sources: "Unit - SpaceMarineFight: Spacemarine_bolter"
  sources: "Unit - SpaceMarineFight: Spacemarine_flamer"
  sources: "Unit - SpaceMarineFight: Spacemarine_melta"
  sources: "Unit - ExportedPregens: UlfarCompanion_Level47_ExportedPregen"
}
weapon {
  guid: "463c53b4d35b4005bd6c15853ccc7879"
  blueprint_name: "OmnissiahAxeT2CH4_Item"
  name_key: "352bc5e4-4c04-4e9b-9298-59ec593d11df"
  name: "[Mars-Pattern] Omnissian Axe"
  category: Melee
  family: Power
  heavy: false
  two_handed: true
  min_damage: 34
  max_damage: 50
  penetration: 55
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OmnissiahAxeTwoHandedAxe_Ability"
    ability_bp: "5e35e29dfa8e4133a9d10b3070d20c0b"
    fx_bp_name: "OmnissiahAxe_AoE_AbilityFXSettings"
    fx_bp: "12258b3764a3417baf819b851360ac2b"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "fb02c043f8e84ae1b777779e75fa4cd2"
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "WeaponSkill15_Feature"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Unit - Ch05_ArcShip: BrassWhisper"
}
weapon {
  guid: "87104954d3a6498ca6c4e2985b345b76"
  blueprint_name: "OmnissiahAxe_Item"
  name_shared_key: "17cecbe5-8208-4367-8f37-971646f9b88a"
  name: "Omnissian Axe"
  category: Melee
  family: Power
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 14
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OmnissiahAxeTwoHandedAxe_Ability"
    ability_bp: "5e35e29dfa8e4133a9d10b3070d20c0b"
    fx_bp_name: "OmnissiahAxe_AoE_AbilityFXSettings"
    fx_bp: "12258b3764a3417baf819b851360ac2b"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  extra_fact: "fb02c043f8e84ae1b777779e75fa4cd2"
  extra_fact: "8f2969f253c844ee8ee2f5f447cd98ec"
  extra_fact_name: "WeaponSkill15_Feature"
  extra_fact_name: "Bleeding_Power4_ForWeapon_Feature"
  sources: "Unit - Ch02_FootfallDock: Footfall_TechPriest"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedTechPriestAxe"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedTechPriestMeleeTough"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedTransmechanicMelee"
  sources: "Unit - Ch02_ForgeWorldAndHeart: HeretekArtisan"
  sources: "Unit - Ch02_ForgeWorldAndHeart: DarkMagos"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_Techpriest"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_TechpriestVillage"
  sources: "Unit - Ch2_PascalEvent: Tarzus"
  sources: "Unit - DLC1_AstropathicChapel: DrumEngineseer"
  sources: "Unit - OurShipCrew: OurCrewTechPriest"
  sources: "Unit - Companions: CompanionPascalPrototype"
  sources: "Unit - ExportedPregens: PascalCompanion_Level15_ExportedPregen"
  sources: "Unit - ExportedPregens: PascalCompanion_Level19_HarmonParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PascalCompanion_Level27_CyrusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PascalCompanion_level27_VasyaParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PascalCompanion_Level39_SolarParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PascalCompanion_LvL40_Bakula_ExportedPregen"
  sources: "Unit - ExportedPregens: Pasqal19Chapel_ExportedPregen"
  sources: "Unit - ExportedPregens: PasqalCompanion_Overseer_EaglePet_Level27_TesseraParty"
  sources: "Unit - ExportedPregens: VasiliyPascal_15LvL_ExportedPregen"
  sources: "Unit - PascalCompanion: PascalCompanion"
  sources: "Unit - PascalCompanion: PascalCompanion_Gamescom"
  sources: "Unit - PascalCompanion: PascalCompanion_StarportNPC"
  sources: "Unit - PascalCompanion: PascalCompanion_TrailerCinematic"
}
weapon {
  guid: "bfbac0eb741840289b3b51208f447688"
  blueprint_name: "PowerAxeT2CH4_Item"
  name_key: "8d9646b8-bdae-4530-8968-82ec96b03380"
  name: "[Mars-Pattern] Power Axe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Power
  heavy: false
  two_handed: false
  min_damage: 21
  max_damage: 31
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 84PF"
}
weapon {
  guid: "7b79b4991269412db0e112ae93f34b62"
  blueprint_name: "PowerAxeT2_Item"
  name_shared_key: "c11a75b9-2b0b-4582-88d2-90b16a7f8b32"
  name: "Master-Crafted Power Axe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Power
  heavy: false
  two_handed: false
  min_damage: 29
  max_damage: 39
  penetration: 50
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Unit - FakeAndWeak_WinterscaleParty: Quetza_Fake_Winterscale"
  sources: "Unit - FinalCompanions: Winterscale_Companion"
}
weapon {
  guid: "a98d90045f054725870925b23bf8a195"
  blueprint_name: "PowerAxe_Item"
  name_key: "9cc75657-b201-4963-9656-e5875af5fad6"
  name: "Power Axe"
  description_shared_key: "1d673611-90f3-40a1-955d-5806fc95b049"
  description: "Axes have a special attack that inflicts {g|Encyclopedia:BleedingEffect}bleeding{/g}."
  category: Melee
  family: Power
  heavy: false
  two_handed: false
  min_damage: 12
  max_damage: 19
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "232ae3bb3ca04d27bdc5ea57156d629e"
  extra_fact_name: "Bleeding_Power6_ForWeapon_Feature"
  sources: "Unit - Ch02_RogueTraderPalace: ArthurWinterscale"
  sources: "Unit - Ch02_RogueTraderPalace: ArthurWinterscale_Final"
  sources: "Unit - Ch02_RogueTraderPalace: Winterscale"
  sources: "Unit - Ch02_RogueTraderPalace: WinterscaleArchmillitant"
  sources: "Vendor - ExploratorChapter2_VendorTable_Base 52PF"
}
weapon {
  guid: "9789705abb9241d2acc21fb592567ad2"
  blueprint_name: "TwoHandedAxe_Item"
  name_shared_key: "d288657d-ca7c-4758-b9f4-7deb6086e292"
  name: "Axe"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: false
  min_damage: 9
  max_damage: 10
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "8f2969f253c844ee8ee2f5f447cd98ec"
  extra_fact_name: "Bleeding_Power4_ForWeapon_Feature"
  sources: "Vendor - PirateChapter1_VendorTable_Base 14PF"
}
weapon {
  guid: "ff3551eed6ee4b9a854e5f3812886455"
  blueprint_name: "AOO_OmnissiahAxe_Item"
  name_shared_key: "9940ca76-c298-4062-8358-006c30d7dc92"
  name: "[C-Delphim Pattern] Omnissian Axe"
  description_key: "443d15b1-3c83-4f0e-a93a-7ce874267bc7"
  description: "This axe uses <b>Brutal Strike</b> for {g|Encyclopedia:AttackOfOpportunityFullGlossary}attacks of opportunity{/g}."
  category: Melee
  family: Power
  heavy: false
  two_handed: true
  min_damage: 16
  max_damage: 24
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OmnissiahAxeTwoHandedAxe_Ability"
    ability_bp: "5e35e29dfa8e4133a9d10b3070d20c0b"
    fx_bp_name: "GreatSword_AOE_AbilityFXSettings"
    fx_bp: "7c573c13e98b492982288e35264f64bb"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "fb02c043f8e84ae1b777779e75fa4cd2"
  extra_fact: "232ae3bb3ca04d27bdc5ea57156d629e"
  extra_fact_name: "WeaponSkill15_Feature"
  extra_fact_name: "Bleeding_Power6_ForWeapon_Feature"
  sources: "Chest - Test: TestRaritiesLoot"
  sources: "Unit - ExportedPregens: Pascal35Yremeris_ExportedPregen"
  sources: "Unit - ExportedPregens: PasqalCompanionOverseer_Level38"
  sources: "Unit - ExportedPregens: PasqalCompanion_Level29_ExportedPregen"
  sources: "Unit - ExportedPregens: PasqalCompanion_lvl38_treasureworld_ExportedPregen"
  sources: "Unit - ExportedPregens: pasqual_lv38_chordafight_ExportedPregen"
  sources: "Unit - ExportedPregens: Yanus19Pascal_ExportedPregen"
  sources: "Vendor - ExploratorChapter2_VendorTable_Base 26PF"
}
weapon {
  guid: "c64f179c441c4abba2966c6eb69cd7b3"
  blueprint_name: "Carnage_ChainAxe_Item"
  name_shared_key: "bb329fc3-e0aa-49c1-99de-72b5de46f099"
  name: "Carnage"
  description_shared_key: "6bdaa914-108e-47fc-8082-b385d573e2fe"
  description: "Each successful {g|Encyclopedia:HitSequenceGlossary}hit{/g} with this axe increases the {g|Encyclopedia:CritChancesAndCritDamageGlossary}critical damage{/g} of this axe by 25% until the end of combat."
  category: Melee
  family: Chain
  heavy: false
  two_handed: false
  min_damage: 17
  max_damage: 27
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "ChainAxe_AbilityFXSettings"
    fx_bp: "754aec79e5d04d51a6c9eebaf0aa0365"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3cf3bbf928e749bab5af826a2eb02f31"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "232ae3bb3ca04d27bdc5ea57156d629e"
  extra_fact_name: "Carnage_ChainAxe_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Bleeding_Power6_ForWeapon_Feature"
  sources: "Vendor - PirateChapter2_VendorTable_Base 56PF"
}
weapon {
  guid: "7e35fc9f20594e518f0ad0907984776a"
  blueprint_name: "DespathcheringAxe_Item"
  name_key: "5a4c0533-c94d-413b-87b6-77658728add7"
  name: "Disemboweler"
  description_key: "fdc2cc5e-2b66-45fa-9935-7664c98bb7f6"
  description: "Increases the {g|Encyclopedia:BleedingEffect}bleeding{/g} level caused by this axe by +1 until the end of combat for each strike attack performed by it."
  category: Melee
  family: Primitive
  heavy: true
  two_handed: false
  min_damage: 23
  max_damage: 33
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "a9b7acd0719947428fff3d34fce0a074"
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "DespathcheringAxe_Feature"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Chest - Quetza-al_Khet: Loot_Good_Massacre_TechRoom"
}
weapon {
  guid: "5e536199ce074052babb98226bbd29fc"
  blueprint_name: "FrostAxeCH5Unique_Item"
  name_shared_key: "25fd3c33-3a24-4658-8cfe-11e66f3bdf87"
  description_key: "b017b621-9fe0-4a8d-85a5-c69f5bcd0cf9"
  description: "Attacks by this axe deal additional {g|Encyclopedia:DamageGlossary}damage{/g} equal to 5% of the target\'s {g|Encyclopedia:MaxWounds}maximum wounds{/g}. This {g|Encyclopedia:Bonus}bonus{/g} is applied to each enemy only once per {g|Encyclopedia:Round}round{/g}."
  category: Melee
  family: Power
  heavy: false
  two_handed: false
  min_damage: 35
  max_damage: 50
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "bedeb1015ba844e29223c658a5bfdd47"
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "FrostAxeCH5Unique_Feature"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Chest - CR0: AdeptusMechanicus_necron_container_GoodLoot"
}
weapon {
  guid: "2f66a1c30d544179a685ae27130e7233"
  blueprint_name: "HandOfXenocide_OmnissiahAxe_Item"
  name_shared_key: "080698cb-f80a-48e2-baa7-21523b3d347f"
  description_shared_key: "26881cb0-d67c-4fdb-868f-cb7eabd8d638"
  description: "This weapon deals +{uip|Damage|db50fd1f18244abdaa946cacbdca880d}% more {g|Encyclopedia:DamageGlossary}damage{/g} to xenos enemies."
  category: Melee
  family: Power
  heavy: false
  two_handed: true
  min_damage: 19
  max_damage: 30
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OmnissiahAxeTwoHandedAxe_Ability"
    ability_bp: "5e35e29dfa8e4133a9d10b3070d20c0b"
    fx_bp_name: "OmnissiahAxe_AoE_AbilityFXSettings"
    fx_bp: "12258b3764a3417baf819b851360ac2b"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "OmnissiahAxe_AoE_AbilityFXSettings"
    fx_bp: "12258b3764a3417baf819b851360ac2b"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "fb02c043f8e84ae1b777779e75fa4cd2"
  extra_fact: "db50fd1f18244abdaa946cacbdca880d"
  extra_fact: "232ae3bb3ca04d27bdc5ea57156d629e"
  extra_fact_name: "WeaponSkill15_Feature"
  extra_fact_name: "HandOfXenocide_OmnissiahAxe_Feature"
  extra_fact_name: "Bleeding_Power6_ForWeapon_Feature"
}
weapon {
  guid: "5b7337e76a404dad915422f82d11a789"
  blueprint_name: "Malivolent_PowerAxe_Item"
  name_key: "ade0914c-49d2-4996-bec4-c9bc60122aec"
  name: "Tarvanna\'s Last Stand"
  description_key: "cec7464f-a106-4a25-80a8-2971f9c48149"
  description: "This power axe deals +50% more {g|Encyclopedia:DamageGlossary}damage{/g} if the wielder has less than 50% {g|Encyclopedia:HitPoints}wounds{/g}."
  category: Melee
  family: Power
  heavy: false
  two_handed: false
  min_damage: 29
  max_damage: 39
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "43874bc26f0444b3a66af5e3bba2a96f"
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "Malivolent_PowerAxe_Feature"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_Winterscale"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_WinterscaleVillage"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level42_OlegParty_ExportedPregen"
}
weapon {
  guid: "36dec72188af4c3e99757db6443f8bd7"
  blueprint_name: "OmnissiahAxeCH04Unique_Item"
  name_shared_key: "f62b2395-2f13-4e57-ab6e-7b7f5ab8159c"
  name: "Omnissiah\'s Providence"
  description_shared_key: "a1ce79ce-dcad-4233-954d-191a10b5c39d"
  description: "If the target of this axe\'s attack is suffering from the effect of <b>Expose Weakness</b>, all {g|Encyclopedia:EnergyDamage}energy damage{/g} dealt to the target is increased by +{uip|Debuff|6ceac4db06434d3eae9c7839290aaf1d}% until the end of combat.\\nIf the target of the attack is not suffering from both {g|Encyclopedia:Exploit}exploit{/g} and <b>Expose Weakness</b>, both of these effects are inflicted on the target after the attack."
  category: Melee
  family: Power
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 45
  penetration: 50
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OmnissiahAxeTwoHandedAxe_Ability"
    ability_bp: "5e35e29dfa8e4133a9d10b3070d20c0b"
    fx_bp_name: "OmnissiahAxe_AoE_AbilityFXSettings"
    fx_bp: "12258b3764a3417baf819b851360ac2b"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "MacesMeleeAttack_AbilityFXSettings"
    fx_bp: "091e9300299b4b97bb9c414f10520fd8"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "fb02c043f8e84ae1b777779e75fa4cd2"
  extra_fact: "6ceac4db06434d3eae9c7839290aaf1d"
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "WeaponSkill15_Feature"
  extra_fact_name: "OmnissiahAxeCH04Unique_Feature"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 136PF"
}
weapon {
  guid: "35238915b39b49a6aa8b568201a802d7"
  blueprint_name: "PowerAxeCH04Unique2_Item"
  name_key: "7e8c8117-148c-4af2-8956-1474b69ea8e4"
  name: "Bolstering Resolve"
  description_key: "ae387895-f71a-487b-8995-6dcbbea09afc"
  description: "Each successful {g|Encyclopedia:HitSequenceGlossary}hit{/g} by this power axe increases the {g|Encyclopedia:WarhammerStrength}Strength{/g} of its wielder by +5 until the end of combat."
  category: Melee
  family: Power
  heavy: false
  two_handed: false
  min_damage: 12
  max_damage: 19
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
}
weapon {
  guid: "36e46c77f00f4a5b98af33842cafebf1"
  blueprint_name: "PowerAxeCH04Unique_Item"
  name_shared_key: "fed5a5c6-ae60-4582-aeda-2c932e6c802d"
  name: "Tearing Vengeance"
  description_shared_key: "28d0efde-981c-448a-8c7d-993cb781f283"
  description: "This power axe deals an additional +{uip|Damage|89a56b94dbac479f961ee8727040b945} {g|Encyclopedia:DamageGlossary}damage{/g}. The first attack each {g|Encyclopedia:Round}round{/g} against a {g|Encyclopedia:BleedingEffect}bleeding{/g} target restores +1 {g|Encyclopedia:ActionPoints}AP{/g} to the wielder.\\nThe wielder suffers 6 damage every {g|Encyclopedia:Turn}turn{/g}."
  category: Melee
  family: Power
  heavy: false
  two_handed: false
  min_damage: 25
  max_damage: 40
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "89a56b94dbac479f961ee8727040b945"
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "PowerAxeCH04Unique_Feature"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Chest - Lair1: Lair1_RelicLoot"
}
weapon {
  guid: "0d864d6cca6a4233a3f68e62e5883a34"
  blueprint_name: "PowerAxeCH5Unique_Item"
  name_shared_key: "3ac288d6-48eb-4d6b-8ab8-94b202b0f44d"
  name: "Sanguine Thirst"
  description_shared_key: "40b99a82-1171-4d1b-81f2-04d364609cfa"
  description: "This power axe deals +{uip|Damage|cdd3a569389d4a90b4b4c859652b3e19} {g|Encyclopedia:DamageGlossary}damage{/g} to {g|Encyclopedia:BleedingEffect}bleeding{/g} targets. If it is the first attack against a bleeding target, this attack has no {g|Encyclopedia:Cooldown}cooldown{/g}."
  category: Melee
  family: Power
  heavy: false
  two_handed: false
  min_damage: 31
  max_damage: 41
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MeleeAttack_ability"
    ability_bp: "be721a48e3614ddbb86bf18503511c2c"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedAxe_AoEAbility"
    ability_bp: "a4e6fe4661514cddb05ec43db1b7c296"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Axe_BleedAbility"
    ability_bp: "a270dbb75ea44128b951b5d18d0b6bed"
    fx_bp_name: "PowerAxe_AbilityFXSettings"
    fx_bp: "5a72a93ee3bd4a049aa4ddef1e4c7f84"
    on_hit_actions: "33bf9dffa6fd42c2af0edd0e045ea5c6"
    on_hit_action_name: "Axe_BleedAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "cdd3a569389d4a90b4b4c859652b3e19"
  extra_fact: "9962dd8fa12e4c8f8b6fe4832ae356c7"
  extra_fact_name: "PowerAxeCH5Unique_Feature"
  extra_fact_name: "Bleeding_Power10_ForWeapon_Feature"
  sources: "Chest - EpitaphEntrance: AdeptusMechanicus_Corpse"
}

