# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "87c135cffa7747e1894bdb8207f28ae3"
  blueprint_name: "AstartesChainswordT2_Item"
  name_key: "42a85de1-27fe-4191-89ae-e157d3680542"
  name: "[Ryza-Pattern] Astartes Chainsword"
  description_shared_key: "df75d986-d2a4-4554-a7e7-021d0b88178f"
  description: "This chainsword grants +10% critical {g|Encyclopedia:HitSequenceGlossary}hit chance{/g}."
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 35
  max_damage: 52
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: false
    negate: false
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "6c89da054cfe4ceaacd5e23c6f978549"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "AstartesChainsword_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Unit - ExportedPregens: UlfarCompanion_Level38_ValladinParty_ExportedPregen"
  sources: "Vendor - LiegeChapter4_VendorTable_Base 102PF"
}
weapon {
  guid: "4b461fdf754d4a338a939f34be00ca44"
  blueprint_name: "AstartesChainswordT2_Item_Ghost"
  description_shared_key: "df75d986-d2a4-4554-a7e7-021d0b88178f"
  description: "This chainsword grants +10% critical {g|Encyclopedia:HitSequenceGlossary}hit chance{/g}."
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 35
  max_damage: 52
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: false
    negate: false
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "6c89da054cfe4ceaacd5e23c6f978549"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "AstartesChainsword_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Unit - Ch05_UlfarQ2: GhostSpaceMarine_ChainSword_Melee_UlfarQ2"
}
weapon {
  guid: "4d820ce4c3134a44bc83bc72af32638c"
  blueprint_name: "AstartesChainsword_Item"
  name_key: "e74f88db-17fc-4321-972e-dad14e6d0533"
  name: "Astartes Chainsword"
  description_shared_key: "df75d986-d2a4-4554-a7e7-021d0b88178f"
  description: "This chainsword grants +10% critical {g|Encyclopedia:HitSequenceGlossary}hit chance{/g}."
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 19
  max_damage: 30
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: false
    negate: false
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "6c89da054cfe4ceaacd5e23c6f978549"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "AstartesChainsword_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Chest - Prison: Drukhari_PrisonPitOwnChest01"
  sources: "Unit - Ch02_ForgeWorldAndHeart: FriendlySpacewolfMarine_Pistol"
  sources: "Unit - Ch02_ForgeWorldAndHeart: RegindSpacewolfMarine_Melee"
  sources: "Unit - Ch04_Eufrates: Halbrandt_MeleeRanged_UlfarQuest"
  sources: "Unit - SpaceMarineFight: Spacemarine_axe"
  sources: "Unit - ExportedPregens: Sayonara_39lvl_Ulfar_ExportedPregen"
  sources: "Unit - ExportedPregens: UlfarCompanion_Lvl40_Bakula_ExportedPregen"
}
weapon {
  guid: "658a4de07b894b67915121ab2f590c6a"
  blueprint_name: "ChainSwordT1CH01_Item"
  name_shared_key: "89bb85c3-0050-4f41-bf2c-81f44cd29fb1"
  name: "Chainsword"
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 8
  max_damage: 12
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - ExportedPregens: PlayerRT_Level15_BladeDancer_ExportedPregen"
  sources: "Vendor - PirateChapter1_VendorTable_Base 10PF"
}
weapon {
  guid: "6336cfb70e63414eab3d0182cf4e5d17"
  blueprint_name: "ChainSwordT2CH4_Item"
  name_key: "b3c55783-a23a-4021-87ab-a22642c701b3"
  name: "[Ryza-Pattern] Chainsword"
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 20
  max_damage: 30
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - Ch02_VoidshipOfficersDeck: GenestealerDanrok_Melee_PatriarchVisions"
  sources: "Unit - Ch04_FootfallSewersCh04: FootfallSewers_Bandit_MeleeSwarm"
  sources: "Unit - DLC1_LowerTunnels: InfernusCH04LTState1_Melee_Swarm"
  sources: "Unit - Ch04_Canteena: Ch04Vladaym_MeleeThug_unit"
  sources: "Unit - Ch04_SalisPrine_ItsTime: ItsTime_Afterlight_Boss"
  sources: "Unit - Ch04_VoidshipBridgeBoarding: HumanRavor_MeleeRanged_Boarding"
  sources: "Unit - Ch04_VoidshipBridgeBoarding: InquisitorAishara_MeleeRanged_Boarding"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level42_OlegParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level38_ArbitratorOfficer_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level38_ArbitratorOfficer_ForTrailer"
  sources: "Unit - ExportedPregens: PlayerRT_Level38_OfficerOverseer_ExportedPregen"
}
weapon {
  guid: "d1fcb447486c4163b178e248f9ebc929"
  blueprint_name: "ChainSword_Item"
  name_shared_key: "89bb85c3-0050-4f41-bf2c-81f44cd29fb1"
  name: "Chainsword"
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 7
  max_damage: 9
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Chest - Lair1: Lair1_AmmoBox"
  sources: "Unit - Ch02_VoidshipOfficersDeck: GenestealerDanrok_Melee_PatriarchVisions"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Grenadir"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Sniper"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldRebelMeleeTough"
  sources: "Unit - Ch02_DaringHeirGuttedShip: HalfCrazyServicemanEnforcer"
  sources: "Unit - Ch02_FootFallAtrium: FootfallPirateEnforcer"
  sources: "Unit - Ch02_FootFallAtrium: SideQuestPirate_Techpriest"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverFrenzy2_Melee_Common"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverFrenzy_Melee_Common"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverKnivesOutLeader_MeleeRanged_Elite"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverKnivesOutLeutenant_MeleeRanged_Common"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverKnivesOutLeutenant_MeleeRanged_CommonQS"
  sources: "Unit - Ch02_FootfallDock: FootfallAnver_MeleeRanged_Swarm"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditBloodbath"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditKnivesOut_AnverLair_Ranged"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditPeacefull1"
  sources: "Unit - Ch02_FootfallDock: FootfallBandit_Quicksilver"
  sources: "Unit - Ch02_FootfallDock: FootfallBandit_Quicksilver2"
  sources: "Unit - Ch02_FootfallDock: FootfallPeacefullBandit"
  sources: "Unit - Ch02_FootfallDock: Footfall_JaeCanteenaSceneBandit1"
  sources: "Unit - Ch02_FootfallDock: Footfall_JaeCanteenaSceneBandit2"
  sources: "Unit - Ch02_FootfallDock: JaeGuard"
  sources: "Unit - Ch02_FootfallDock: JaeGuard_Kor"
  sources: "Unit - Ch02_FootfallDock: JaeGuard_Torra"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedTechPriestMelee"
  sources: "Unit - Ch02_Lair3: Lair3RebelMelee"
  sources: "Unit - Ch02_Lair3: Lair3RebelMeleeKnife"
  sources: "Unit - Ch02_RandomEncounters: CultisthNurgleRangeRandomEncounter"
  sources: "Unit - Ch02_RogueTraderPalace: Gladiator"
  sources: "Unit - Ch02_RogueTraderPalace: NaviRepresentive"
  sources: "Unit - Ch02_RogueTraderPalace: NaviRepresentiveFemale"
  sources: "Unit - Ch02_RogueTraderPalace: RadicalBodyguardFighter"
  sources: "Unit - Ch02_RogueTraderPalace: RadicalFakeGuardFighter"
  sources: "Unit - Ch02_RogueTraderPalace: RogueTraderGuardPeacefulWMeleWeapon"
  sources: "Unit - Ch02_VoidshipBridge: BridgeCrewMemberBloodGuard"
  sources: "Unit - Ch02_VoidshipBridge: BridgeCrewMemberGuard"
  sources: "Unit - Ch02_VoidshipBridge: BridgeCrewMemberGuard_Chaos"
  sources: "Unit - Ch02_VoidshipBridge: BridgeCrewMemberGuard_Medic"
  sources: "Unit - Ch02_VoidshipBridge: BridgeCrewMemberGuard_Timeline_Bolter"
  sources: "Unit - Ch02_VoidshipTemple: HumanZeke_MeleeRanged_VoidshipTempleAmbush"
  sources: "Unit - Ch03_AchilleasAbduction: AchilleasAbdBridgeCrewMemberGuard"
  sources: "Unit - Ch04_FootfallAtrium: FootfallCrewMemberGuard"
  sources: "Unit - Ch04_FootfallSewersCh04: JaeGuy3"
  sources: "Unit - Ch05_Epitaph: InquisitorGuardGhostCutsceneMelee"
  sources: "Unit - Ch_00_VoidshipOfficerDeck_AfterPorlogue: DeathCultist_GuardWBanner"
  sources: "Unit - Ch_00_VoidshipOfficerDeck_AfterPorlogue: DeathCultist_Guard_Female"
  sources: "Unit - Ch_00_VoidshipOfficerDeck_AfterPorlogue: DeathCultist_Prisoner"
  sources: "Unit - Ch_00_VoidshipOfficerDeck_AfterPorlogue: DeathCultist_Prisoner_Female"
  sources: "Unit - Ch_00_VoidshipOfficerDeck_AfterPorlogue: DeathCultist_Prisoner_Male"
  sources: "Unit - DLC1_LowerTunnels: LT_ImpatientEnforcer"
  sources: "Unit - DLC1_LowerTunnels: LT_Intendant"
  sources: "Unit - DLC1_LowerTunnels: LT_SickEnforcer"
  sources: "Unit - DLC2_FeudalWorld: FW_CrewMemberGuard"
  sources: "Unit - Ch02_RandomEncounters: NurgleAmbushZombieChainsword_RandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: OfficerMeleeMutantRandomEncounter"
  sources: "Unit - Ch00_OfficersDeck: Candidate"
  sources: "Unit - Ch01_StarPort: StarPortGovernor"
  sources: "Unit - Ch02_AgriWorldTown: GovernorGuardCaptain"
  sources: "Unit - Ch02_ForgeWorldSpaceHulk: MadTechPriest_melee"
  sources: "Unit - Ch02_ForgeWorldSpaceHulk: MadTechPriest_MutantCutscene"
  sources: "Unit - Ch02_ForgeWorldSpaceHulk: TechpriestMelee_TrailerCinematic"
  sources: "Unit - Ch02_RogueTraderPalace: NaviLeader"
  sources: "Unit - Ch04_Canteena: Ch04Vladaym_Pirate_unit"
  sources: "Unit - Ch04_SalisPrine_ItsTime: ItsTime_Afterlight_BossSummon"
  sources: "Unit - Ch04_Eufrates: Eufrates_CorruptedTechPriestAxe_unit"
  sources: "Unit - FootfallAtrium: FootfallArmorer"
  sources: "Unit - FootfallAtrium: FootfallSmugglerCompanionNPC"
  sources: "Unit - FootfallAtrium: SideQuestFirstMate"
  sources: "Unit - FootfallAtrium: SideQuestPirateScion"
  sources: "Unit - FootfallAtrium: SideQuestSlyOfficial2"
  sources: "Unit - FootfallAtrium: SideQuestSlyOfficial3"
  sources: "Unit - Companions: CompanionJaePrototype"
  sources: "Unit - ExportedPregens: JaeCompanion_Level39_SolarParty_ExportedPregen"
}
weapon {
  guid: "9564b8420c724609b96bb3cb77cef4a3"
  blueprint_name: "EldarChainSwordT2CH5_Item"
  name_key: "6be0c950-25e6-4906-a423-56eb342d2240"
  name: "Master-Crafted Aeldari Chainsword"
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 30
  max_damage: 52
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 10
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "Eldar_MeleeAttack_ability"
    ability_bp: "16a14f412b85431d8d0481abc53ef3c3"
    fx_bp_name: "EldarChainSword_AbilityFXSettings"
    fx_bp: "d13366d5047b4d06b92386632be490c7"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "EliteChainSword_AoE_AbilityFXSettings"
    fx_bp: "668f0a1a7a2443c9a832653305e9eff0"
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Chest - Marazhai_Bloodright: Drukhari_Betreyal"
}
weapon {
  guid: "a9320f6175c9449f8edefc7f0e4baaea"
  blueprint_name: "EldarChainSword_Item"
  name_key: "b25afbb1-a202-4b87-98b4-25b10d5a537a"
  name: "Aeldari Chainsword"
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 12
  max_damage: 24
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 10
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "Eldar_MeleeAttack_ability"
    ability_bp: "16a14f412b85431d8d0481abc53ef3c3"
    fx_bp_name: "EldarChainSword_AbilityFXSettings"
    fx_bp: "d13366d5047b4d06b92386632be490c7"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "EliteChainSword_AoE_AbilityFXSettings"
    fx_bp: "668f0a1a7a2443c9a832653305e9eff0"
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Chest - CR0: Forest_ClimbLoot"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldEldarMeleeUnit"
  sources: "Unit - Ch03_ReavingTempestSpire: BloodthirstyExperiment_Melee_ReavingTempestSpire"
  sources: "Unit - Ch04_CrownWorld: CrownWorldHarlequin"
  sources: "Unit - Ch04_Quetza-al_khet: Quetza_EldarStormGuardianMelee"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_Yrliet"
  sources: "Unit - ExportedPregens: Gusev_RT_26lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_Jae_23lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: Yanus19Jae_ExportedPregen"
  sources: "Unit - JaeCompanion: JaeCompanion"
  sources: "Unit - JaeCompanion: SmugglerCompanion_JaeQ1"
}
weapon {
  guid: "c5d8f6b15c7c48b78c5bf7440565be45"
  blueprint_name: "EliteChainSword_Item"
  name_key: "efb3d952-8950-4a73-ba20-8472e6ce0a5c"
  name: "Elite Chainsword"
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 14
  max_damage: 17
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "EliteChainSword_AbilityFXSettings"
    fx_bp: "9f58180359664bbebaef1e4e0bfc5a38"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "EliteChainSword_AoE_AbilityFXSettings"
    fx_bp: "668f0a1a7a2443c9a832653305e9eff0"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Chest - CR33: ImperiumMilitary_ComisarChest"
  sources: "Unit - Ch02_Lair3: Lair3RebelEliteAssault"
  sources: "Unit - DLC2_Ch04_TreasureWorld: TreasureWorld_FeralGuard_Commissar"
  sources: "Unit - Ch03_Prison: HumanCommissar_MeleeRanged_Prison_Fake"
  sources: "Unit - Ch03_Prison: HumanCommissar_MeleeRanged_Prison_True"
  sources: "Unit - ExportedPregens: 4y6_Abelar_22lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: Kibellah20lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: zin_22_KibellahCompanion_ExportedPregen"
  sources: "Vendor - DrusianChapter2_VendorTable_Base 21PF"
}
weapon {
  guid: "af978f6d159b464d9fd6cf71ce056993"
  blueprint_name: "Eviscerator_Item"
  name_shared_key: "ffd668ad-388b-4388-8a85-fedad0d20a0b"
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: true
  min_damage: 31
  max_damage: 41
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "MeleeAoESTwoHandedSword_ability"
    ability_bp: "163013a18e9c46419b2311454ad2b2c8"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Parry10_Feature"
}
weapon {
  guid: "5f9136fdcb6846288046825103057caa"
  blueprint_name: "AnverChainSword_Item"
  name_shared_key: "843813ed-50c1-464b-8676-cd2838d6486f"
  name: "Anver Chainsword"
  description_shared_key: "530ffb0f-adf6-46ae-8c4b-46973f68ce13"
  description: "When {g|Encyclopedia:HitSequenceGlossary}hit{/g} by this weapon, the target suffers a \342\210\2225% {g|Encyclopedia:Penalty}penalty{/g} to {g|Encyclopedia:WarhammerArmourGlossary}armour{/g}. Stacks."
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 12
  max_damage: 16
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_actions: "39e4625815ac4803abbb474f17b38031"
    on_hit_action_name: "AnwerChainSword_AbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "4321a14a265b422f8d2c1c82d8fa355e"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "AnverChainSword_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Unit - Ch02_FootFallSlums: FootfallAnverCommanderLeader_Melee_Elite"
  sources: "Unit - Ch02_FootFallSlums: FootfallAnverCommanderLeader_Melee_EliteQS"
  sources: "Unit - ExportedPregens: AbelardCompanion_level27_VasyaParty_ExportedPregen"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level42_OlegParty_ExportedPregen"
  sources: "Unit - ExportedPregens: CassiaCompanion_Level47_ExportedPregen"
  sources: "Unit - ExportedPregens: Kibellah20lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: Kibellah32lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT19Chapel_ExportedPregen"
  sources: "Unit - ExportedPregens: Yanus19RTT_ExportedPregen"
  sources: "Unit - ExportedPregens: zin_22_AbelardCompanion_ExportedPregen"
}
weapon {
  guid: "40244487985946b6891ad3ddff905146"
  blueprint_name: "ChainSwordCH1Unique_Item"
  name_shared_key: "d2e873aa-ea31-443e-962d-feaf3017de41"
  name: "Wrath of Saint Drusus"
  description_shared_key: "adb6656e-a966-41ad-a9e9-42e4aa320b8b"
  description: "Does not have an {g|Encyclopedia:AreaOfEffect}area attack{/g}. Increases {g|Encyclopedia:DamageGlossary}damage{/g} from all sources against any {g|Encyclopedia:HitSequenceGlossary}hit{/g} targets by +15% until the end of combat. Does not stack."
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 8
  max_damage: 12
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "3e247257cbf84f39a16484e3d07977fd"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainSwordCH1Unique_Feature"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level42_OlegParty_ExportedPregen"
  sources: "Unit - ExportedPregens: Kibellah12lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level15_BladeDancer_ExportedPregen"
  sources: "Unit - ExportedPregens: RT10CSM_ExportedPregen"
}
weapon {
  guid: "4d87435ddfa042269c1fe35df0430f8b"
  blueprint_name: "EvisceratorCH5Unique_Item"
  name_shared_key: "c92a9df9-498b-408a-9042-51901adfeeca"
  name: "Saint Katherine\'s Adulation"
  description_shared_key: "c33fc8d3-5907-4691-9fbd-71142629cd47"
  description: "Grants +80% {g|Encyclopedia:CritChancesAndCritDamageGlossary}critical damage{/g} and a special {g|Encyclopedia:Ability}ability{/g} that allows the wielder to perform three consecutive attacks on an enemy."
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: true
  min_damage: 34
  max_damage: 59
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "MeleeAoESTwoHandedSword_ability"
    ability_bp: "163013a18e9c46419b2311454ad2b2c8"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "EvisceratorCH5Unique_Ability"
    ability_bp: "a6ec10d23b0f49698e17f30e70423615"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_actions: "e1649b252e6d4ff6b12e4fe207989feb"
    on_hit_action_name: "e1649b252e6d4ff6b12e4fe207989feb"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "f70e4a5d21ba4bc9a7fce7e3e84bb59f"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "EvisceratorCH5Unique_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Chest - CR0: ImperiumMilitary_GoodLoot"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch05_Finale"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch05_TrueStart"
}
weapon {
  guid: "972a0a2ec40944a8ad313f931f42febb"
  blueprint_name: "HarbingerOfCarnage_item"
  name_shared_key: "a95d5cf3-10f7-4e04-ba60-475aaed97bac"
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 26
  max_damage: 39
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "EliteChainSword_AbilityFXSettings"
    fx_bp: "9f58180359664bbebaef1e4e0bfc5a38"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "EliteChainSword_AoE_AbilityFXSettings"
    fx_bp: "668f0a1a7a2443c9a832653305e9eff0"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fb7efcba2dcc427da2324d4066daf2d5"
    bp_name: "CorruptionSoulMark_1"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_Archmilitant"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_ArchmilitantOutpost"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_ArchmilitantVillage"
  sources: "Unit - FakeAndWeak_WinterscaleParty: Quetza_Fake_Archmilitant"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level42_OlegParty_ExportedPregen"
}
weapon {
  guid: "8f0075ae61de45d38a572f8ffb43927a"
  blueprint_name: "NullifyingAstartesChainsword_Item"
  name_shared_key: "13b94549-676d-4cda-98be-c9764a8f8a96"
  name: "Untainted Sacrament"
  description_key: "e8eab615-9207-4c3b-a963-71b915af81e3"
  description: "The wielder suffers \342\210\22275% less mental and {g|Encyclopedia:WarpDamage}warp damage{/g}."
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 26
  max_damage: 45
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: false
    negate: false
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "6c89da054cfe4ceaacd5e23c6f978549"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "f09d98beaa3847d6a301735fac81f47e"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "AstartesChainsword_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "NullifyingAstartesChainsword_Feature"
  sources: "Chest - NewTrashLoot: AdeptusMechanicus_SecretRoomChest"
}
weapon {
  guid: "649a9d18b18e45708c13514f501103b9"
  blueprint_name: "OfficerChainSword_Item"
  name_key: "e85cc91c-51cd-4ca0-a733-75d4956ad8b1"
  name: "Officer\'s Chainsword"
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 8
  max_damage: 12
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  sources: "Chest - CR4: TaintedStreets_GoodLoot06"
  sources: "Unit - ExportedPregens: Kibellah20lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT19ChapelPsyker_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT19Chapel_ExportedPregen"
  sources: "Unit - ExportedPregens: RT10CSM_ExportedPregen"
  sources: "Unit - ExportedPregens: Yanus19RTT_ExportedPregen"
}
weapon {
  guid: "badeb1a822a94e448202cac8c249627e"
  blueprint_name: "Scorpion_EldarChainSword_Item"
  name_key: "d2042f6f-bb92-4fb9-b87b-9fac334b9159"
  name: "Scorpion Chainsword"
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 15
  max_damage: 25
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 10
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "Eldar_MeleeAttack_ability"
    ability_bp: "16a14f412b85431d8d0481abc53ef3c3"
    fx_bp_name: "EldarChainSword_AbilityFXSettings"
    fx_bp: "d13366d5047b4d06b92386632be490c7"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "EldarChainSword_AbilityFXSettings"
    fx_bp: "d13366d5047b4d06b92386632be490c7"
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "b7616fa9ada14c3588cf157271fb2632"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Scorpion_EldarChainSword_Feature"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
}
weapon {
  guid: "91ab9da13b8848aab46bd885a0199db3"
  blueprint_name: "Chapter2_Common_VindictorFlamer_HiddenMelee_Item"
  name_shared_key: "060b6a4a-7528-4e02-a713-e15a154b4c2e"
  name: "Vindictor Flamer"
  description_shared_key: "72187f34-9de1-4c81-8c86-9360cc46b211"
  description: "A hybrid of a flamer and a {g|Encyclopedia:MeleeAttacksGlossary}melee{/g} chain weapon. Thanks to the latter, the wielder can {g|Encyclopedia:Parry}parry{/g} with this weapon. Their melee {g|Encyclopedia:CritChancesAndCritDamageGlossary}critical damage{/g} is also increased by +25%."
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 15
  max_damage: 20
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
}
weapon {
  guid: "255395006be0406bbdb653d55993a022"
  blueprint_name: "Chapter4_Unique_LastRitesVindictorFlamer_HiddenMelee_Item"
  name_shared_key: "3a6b5f36-1e01-40bd-bdfb-9a0b9b89a88b"
  name: "Undertaker"
  description_shared_key: "d4ffdea8-a0ff-4223-bf91-043f19efecc4"
  description: "Whenever any creature in combat suffers lethal damage from {g|Encyclopedia:BurningEffect}burning{/g}, the wielder deals +30% more damage with this weapon for 1 {g|Encyclopedia:Round}round{/g}. Does not stack."
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 30
  max_damage: 45
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
}
weapon {
  guid: "f6f8f23745344a3298d9489028247ff1"
  blueprint_name: "Chapter5_Unique_BurnAndSlashVindictorFlamer_HiddenMelee_Item"
  name_shared_key: "3a6b5f36-1e01-40bd-bdfb-9a0b9b89a88b"
  name: "Undertaker"
  description_shared_key: "d4ffdea8-a0ff-4223-bf91-043f19efecc4"
  description: "Whenever any creature in combat suffers lethal damage from {g|Encyclopedia:BurningEffect}burning{/g}, the wielder deals +30% more damage with this weapon for 1 {g|Encyclopedia:Round}round{/g}. Does not stack."
  category: Melee
  family: Chain
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 35
  max_damage: 50
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
}

