# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "52a21c0ec9e447cba63c6c50a6c52fdc"
  blueprint_name: "AstartesFlamerT2_Item"
  name_key: "7a7b1010-b9d7-4d66-8fbb-dcd5f75647e4"
  name: "[Mars-Pattern] Astartes Flamer"
  description_shared_key: "d310b61f-7ff9-4f67-afe5-cca478f9df72"
  description: "Flame weapons have 2 special area attacks with different areas of effect."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 40
  max_damage: 55
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate_Ability"
    ability_bp: "2e4bd45d989549a4ac235be748314b02"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: true
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "FlameProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "1b622a1337c142a2a3825744ec1d1e63"
  extra_fact_name: "Burning_Power12_ForWeapon_Feature"
  sources: "Unit - Ch04_Eufrates: EufratesCSM_HeavyFlamer_unit"
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 124PF"
}
weapon {
  guid: "8003fbd84d5c44b0808440983a34b6d5"
  blueprint_name: "AstartesFlamer_Item"
  name_key: "cf90f404-e566-4870-ba91-8a5fd3cee994"
  name: "Astartes Flamer"
  description_shared_key: "d310b61f-7ff9-4f67-afe5-cca478f9df72"
  description: "Flame weapons have 2 special area attacks with different areas of effect."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 23
  max_damage: 34
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 10
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate_Ability"
    ability_bp: "2e4bd45d989549a4ac235be748314b02"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: true
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "FlameProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "1b622a1337c142a2a3825744ec1d1e63"
  extra_fact_name: "Burning_Power12_ForWeapon_Feature"
  sources: "Chest - Test: TestRaritiesLoot"
  sources: "Unit - SpaceMarineFight: Spacemarine_flamer"
}
weapon {
  guid: "7c9a03c5f43f470fb62de3742a39d0d5"
  blueprint_name: "FlamerCutscene_Item"
  name_shared_key: "75efdeea-cc0a-43df-8905-eae1960ca59f"
  name: "Flamer"
  description_shared_key: "d310b61f-7ff9-4f67-afe5-cca478f9df72"
  description: "Flame weapons have 2 special area attacks with different areas of effect."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 9
  max_damage: 14
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "FlamerCutscene_Line_AbilityFXSettings"
    fx_bp: "dec921cfde4942e28bd329526dd75feb"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate_Ability"
    ability_bp: "2e4bd45d989549a4ac235be748314b02"
    fx_bp_name: "FlamerCutscene_Line_AbilityFXSettings"
    fx_bp: "dec921cfde4942e28bd329526dd75feb"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "FlamerCutscene_Line_AbilityFXSettings"
    fx_bp: "dec921cfde4942e28bd329526dd75feb"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  sources: "Unit - DLC1_LowerTunnels: LT_EnforcerFlamer"
}
weapon {
  guid: "2c80ec5d25de4a1ea2672f98898cbe34"
  blueprint_name: "FlamerDragonsBreath_Item"
  name_key: "1a5b6379-42d6-4045-9f87-331b3ef9a679"
  description_key: "18faaf4c-36bd-4bca-abac-2115326991b5"
  category: Basic
  family: Flame
  heavy: false
  two_handed: false
  min_damage: 15
  max_damage: 18
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "FlamerDragonsBreath_LinearTemplate_Ability"
    ability_bp: "b4d660f34bef442fb7c5774741464ebe"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "FlamerDragonsBreath_WideTemplate_Ability"
    ability_bp: "d1b0f6c238814800a126f7657ac89f03"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "FlameProficiencyFeature"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
}
weapon {
  guid: "5e66561885884f72921b37cd57773443"
  blueprint_name: "FlamerPistolT1CH2_Item"
  name_key: "959f90ab-2c4b-4b2d-925e-b7e0e672ae06"
  name: "[Mezoa-Pattern] Hand Flamer"
  description_shared_key: "7d4104fa-75c1-411e-8eae-0c72b100f855"
  category: Pistol
  family: Flame
  heavy: false
  two_handed: false
  min_damage: 13
  max_damage: 21
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 4
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "FlamePistol_LinearTemplate_Ability"
    ability_bp: "fae6e41d51ad410099d92ccc8f342f91"
    fx_bp_name: "Flamer4_Line_AbilityFXSettings"
    fx_bp: "dd92a14ad60f4525a8769f50d209eed2"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "FlamerPistol_WideTemplate_Ability"
    ability_bp: "ad7bde40de224aeca7c9807e67f5c16b"
    fx_bp_name: "Flamer4_Wide_AbilityFXSettings"
    fx_bp: "6164b3fd57c740b2be556342911aecbb"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  sources: "Chest - CR22: AdeptusMechanicus_QuicksilverLootBag"
  sources: "Unit - ExportedPregens: Argenta19Chapel_ExportedPregen"
}
weapon {
  guid: "aa1a84f831014dfca9076170990e7887"
  blueprint_name: "FlamerPistolT2CH4_Item"
  name_key: "7736339e-0e0e-4cc4-a689-4fe2368cf8cf"
  name: "[Mars-Pattern] Hand Flamer"
  description_shared_key: "7d4104fa-75c1-411e-8eae-0c72b100f855"
  category: Pistol
  family: Flame
  heavy: false
  two_handed: false
  min_damage: 27
  max_damage: 40
  penetration: 5
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 0
  max_range: 4
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "FlamePistol_LinearTemplate_Ability"
    ability_bp: "fae6e41d51ad410099d92ccc8f342f91"
    fx_bp_name: "Flamer4_Line_AbilityFXSettings"
    fx_bp: "dd92a14ad60f4525a8769f50d209eed2"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "FlamerPistol_WideTemplate_Ability"
    ability_bp: "ad7bde40de224aeca7c9807e67f5c16b"
    fx_bp_name: "Flamer4_Wide_AbilityFXSettings"
    fx_bp: "6164b3fd57c740b2be556342911aecbb"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "a2c7cb49c86749b3b9fa7381bc17875c"
  extra_fact_name: "Burning_Power15_ForWeapon_Feature"
  sources: "Unit - Ch04_VoidshipBridgeBoarding: InquisitorAishara_MeleeRanged_Boarding"
  sources: "Unit - Ch05_ArcShip: BrassWhisper"
}
weapon {
  guid: "ac421717dfd84b8f9a2381e7bcbec4f9"
  blueprint_name: "FlamerPistol_Item"
  name_key: "6d467458-1d87-40ee-9b13-ec5a92d63b5d"
  name: "Hand Flamer"
  description_shared_key: "7d4104fa-75c1-411e-8eae-0c72b100f855"
  category: Pistol
  family: Flame
  heavy: false
  two_handed: false
  min_damage: 5
  max_damage: 9
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 4
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "FlamePistol_LinearTemplate_Ability"
    ability_bp: "fae6e41d51ad410099d92ccc8f342f91"
    fx_bp_name: "Flamer4_Line_AbilityFXSettings"
    fx_bp: "dd92a14ad60f4525a8769f50d209eed2"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "FlamerPistol_WideTemplate_Ability"
    ability_bp: "ad7bde40de224aeca7c9807e67f5c16b"
    fx_bp_name: "Flamer4_Wide_AbilityFXSettings"
    fx_bp: "6164b3fd57c740b2be556342911aecbb"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  sources: "Chest - CR4: AdeptusMechanicus_TaintedStreets_GoodLoot07"
  sources: "Chest - TheLure_Lair4: Loot_Poor_SecretChest (2) - 150"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsCultistFlamer"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsRebelFlamer"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverFlamer_Ranged_Swarm"
  sources: "Unit - Ch02_FootFallSlums: FootfallAnverFlamer_Ranged_Common"
  sources: "Unit - Ch02_SantielsPrideUnderhive: WildCannibalHeatmaster"
  sources: "Unit - Ch02_VoidshipTemple: HumanZeke_MeleeRanged_VoidshipTempleAmbush"
  sources: "Unit - Ch02_RandomEncounters: RE_PossessedOfficer_Flamer"
  sources: "Unit - Ch02_SantielsPrideUnderhive: Prisoner"
  sources: "Unit - Ch02_SantielsPrideUnderhive: SurvivorLeaderBoy"
  sources: "Unit - JaeCompanion: JaeCompanion_Gamescom"
}
weapon {
  guid: "17c9cb57629b4c82b22be55b8f6d5b94"
  blueprint_name: "FlamerT2CH4_Item"
  name_key: "8ee57d0f-14bc-4769-966e-dba2c252f0ac"
  name: "[Mars-Pattern] Flamer"
  description_shared_key: "d310b61f-7ff9-4f67-afe5-cca478f9df72"
  description: "Flame weapons have 2 special area attacks with different areas of effect."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 29
  max_damage: 44
  penetration: 5
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate_Ability"
    ability_bp: "2e4bd45d989549a4ac235be748314b02"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "a2c7cb49c86749b3b9fa7381bc17875c"
  extra_fact_name: "Burning_Power15_ForWeapon_Feature"
  sources: "Unit - Ch04_FootfallSewersCh04: FootfallSewers_Bandit_Flamer"
  sources: "Unit - Ch04_VoidshipBridgeBoarding: InquisitorFlamer_Ranged_Boarding"
}
weapon {
  guid: "2c8b2e940be549fbb322adff722200f0"
  blueprint_name: "Flamer_Item"
  name_shared_key: "75efdeea-cc0a-43df-8905-eae1960ca59f"
  name: "Flamer"
  description_shared_key: "d310b61f-7ff9-4f67-afe5-cca478f9df72"
  description: "Flame weapons have 2 special area attacks with different areas of effect."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 9
  max_damage: 14
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate_Ability"
    ability_bp: "2e4bd45d989549a4ac235be748314b02"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  sources: "Chest - Prison: Drukhari_PrisonPitOwnChest01"
  sources: "Unit - Ch02_AgriWorldTown: GovernorGuard_TrailerCinematicFlamer"
  sources: "Unit - Ch02_DestroyedBlackShip: BlackshipCrew_Flamer"
  sources: "Unit - Ch02_FootFallAtrium: FootfallPirateCapellan"
  sources: "Unit - Ch02_FootFallSlums: Footfall_Deraziter"
  sources: "Unit - Ch02_FootFallSlums: Footfall_DeraziterMain"
  sources: "Unit - Ch02_Lair3: Lair3RebelFlamethrougher"
  sources: "Unit - Ch02_RandomEncounters: CultistRangeKhorneRandomEncounter_Flamer"
  sources: "Unit - Ch05_ArcShip: InquisitionMob"
  sources: "Unit - Ch05_ArcShip: MechanicusMob"
  sources: "Unit - DLC1_Ch02_VoidshipCrypt: EnforcersFlamer_Ranged_VoidshipCrypt1"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedMagus"
  sources: "Unit - Ch04_Canteena: Footfall_Chaplain_Ch04"
  sources: "Unit - Ch05_Epitaph: Ch05Inquisitor_Argenta_unit"
  sources: "Unit - Ch04: Footfall_ChordaEnforcer"
  sources: "Unit - Ch04: Footfall_ChordaEnforcer01"
  sources: "Unit - Ch04: Footfall_ChordaEnforcer02"
  sources: "Unit - Ch04: Footfall_CommonerFemaleFlamer"
  sources: "Unit - Ch04: Footfall_CommonerFlamer"
  sources: "Unit - Ch04: Footfall_InquisitorAgent"
  sources: "Unit - FootfallAtrium: SideQuestChaplain"
  sources: "Unit - Companions: CompanionArgentaPrototype"
  sources: "Unit - ArgentaCompanion: ArgentaCompanion"
  sources: "Unit - ArgentaCompanion: ArgentaCompanion_Ch02_TrueStart"
  sources: "Unit - ExportedPregens: ArgentaCompanion_Level19_HarmonParty_ExportedPregen"
  sources: "Unit - ExportedPregens: ArgentaCompanion_Level22_NeiliusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: ArgentaCompanion_Level27_CyrusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: Executioner_ForMarketing_Pregen_ExportedPregen"
  sources: "Unit - ExportedPregens: VasiliyArgenta_15LvL_ExportedPregen"
  sources: "Unit - HeinrixCompanion: FighterPsykerQA_AllDoTs"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Gamescom"
  sources: "Vendor - PirateChapter1_VendorTable_Base 4PF"
}
weapon {
  guid: "7faebaad0c8e412b888b9189abb308e9"
  blueprint_name: "HeavyFlamer_Item"
  name_shared_key: "a475098e-b892-4e92-bebb-da7b06ca7440"
  name: "Heavy Flamer"
  description_shared_key: "d310b61f-7ff9-4f67-afe5-cca478f9df72"
  description: "Flame weapons have 2 special area attacks with different areas of effect."
  category: Heavy
  family: Flame
  heavy: true
  two_handed: true
  min_damage: 18
  max_damage: 26
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "HeavyFlamer_LinearTemplate_Ability"
    ability_bp: "afffd113dbb44e6485e3b3dd9c93856b"
    fx_bp_name: "Flamer10_Line_AbilityFXSettings"
    fx_bp: "03a31179363d464c9b3170034fe22967"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability2 {
    type: AOE
    ability_bp_name: "HeavyFlamer_WideTemplate_Ability"
    ability_bp: "06a5e88cd20048c1a5a220be09b940f7"
    fx_bp_name: "Flamer10_Wide_AbilityFXSettings"
    fx_bp: "117bf8fcfede4e38b090bf8cdc1b8f5b"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer10_Wide_AbilityFXSettings"
    fx_bp: "117bf8fcfede4e38b090bf8cdc1b8f5b"
    on_hit_action_name: ""
    ap: 3
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 50
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  sources: "Unit - ExportedPregens: Argenta35Yremeris_ExportedPregen"
  sources: "Vendor - DrusianChapter2_VendorTable_Base 32PF"
}
weapon {
  guid: "8369796a78424d92bd72f0cbf2f8139b"
  blueprint_name: "FlamerCH05Unique_Item"
  name_key: "4bf792dc-338d-4759-876a-d2954f879c6d"
  name: "Purging Fury"
  description_key: "0f3a990f-f1fa-4d57-a689-8845b698bbe7"
  description: "The first attack with this flamer in combat deals additional {g|Encyclopedia:DirectDamage}direct damage{/g} to xenos, psykers, and daemons, equal to 10% of the target\'s {g|Encyclopedia:MaxWounds}maximum wounds{/g}. The {g|Encyclopedia:BurningEffect}burning{/g} effect applied by this flamer deals additional {g|Encyclopedia:DamageGlossary}damage{/g} equal to 2% of the target\'s maximum {g|Encyclopedia:HitPoints}wounds{/g} to xenos, psykers, and daemons."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 45
  max_damage: 74
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate10_Ability"
    ability_bp: "cebf3742b4c741eb8fce62225fded78b"
    fx_bp_name: "Flamer10_Line_AbilityFXSettings"
    fx_bp: "03a31179363d464c9b3170034fe22967"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate10_Ability"
    ability_bp: "efba953e48a94d588b7e08d6eb9240a6"
    fx_bp_name: "Flamer10_Wide_AbilityFXSettings"
    fx_bp: "117bf8fcfede4e38b090bf8cdc1b8f5b"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "9f105cd46de04830923b93a43c6ea385"
  extra_fact: "a64e828581ae47d1a2e0cba2da34a719"
  extra_fact: "1b622a1337c142a2a3825744ec1d1e63"
  extra_fact_name: "FlamerCH05UniqueBurnPower_Feature"
  extra_fact_name: "FlamerCH05Unique_Feature"
  extra_fact_name: "Burning_Power12_ForWeapon_Feature"
  sources: "Chest - NecronLair_3: ImperiumMilitary_GoodCorpse"
  sources: "Unit - ArgentaCompanion: ArgentaCompanion_Ch05_Finale"
  sources: "Unit - ArgentaCompanion: ArgentaCompanion_Ch05_TrueStart"
}
weapon {
  guid: "360ff901df844a93bcf8a806fda974dc"
  blueprint_name: "FlamerDragonsBreath_Item"
  name_key: "41b39147-4c93-4337-b5c2-d85d3754489b"
  name: "Breath of Purgation"
  description_key: "56896866-c7fe-4b44-a4cf-a2a24612e32d"
  description: "For each target {g|Encyclopedia:HitSequenceGlossary}hit{/g} by this flamer\'s attack, the power of {g|Encyclopedia:BurningEffect}burning{/g} inflicted by this flamer\'s attacks is increased by +3 until the end of combat."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 23
  max_damage: 34
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "a6e4dd826ffe4a3ab29d070d0c73f967"
  extra_fact: "1b622a1337c142a2a3825744ec1d1e63"
  extra_fact_name: "FlamerDragonsBreath_Feature"
  extra_fact_name: "Burning_Power12_ForWeapon_Feature"
  sources: "Vendor - LiegeChapter4_VendorTable_Base 86PF"
}
weapon {
  guid: "66c1d85de9c3439eb49c488954fafe45"
  blueprint_name: "FlamerPistolCH2Unique_Item"
  name_shared_key: "d771d890-1898-4d27-ac7f-5b7291f50136"
  name: "Reconstructed Flamer Pistol"
  description_shared_key: "8a556d43-5e65-45d3-90d3-0e2f699b1c00"
  description: "When {g|Encyclopedia:HitSequenceGlossary}hit{/g} by this weapon, all {g|Encyclopedia:MeleeAttacksGlossary}melee attacks{/g} against the target gain +10% {g|Encyclopedia:CritChancesAndCritDamageGlossary}critical hit chance{/g} and +15% critical {g|Encyclopedia:DamageGlossary}damage{/g} for 2 {g|Encyclopedia:Turn}turns{/g}."
  category: Pistol
  family: Flame
  heavy: false
  two_handed: false
  min_damage: 13
  max_damage: 19
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 4
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "FlamePistol_LinearTemplate_Ability"
    ability_bp: "fae6e41d51ad410099d92ccc8f342f91"
    fx_bp_name: "Flamer4_Line_AbilityFXSettings"
    fx_bp: "dd92a14ad60f4525a8769f50d209eed2"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "FlamerPistol_WideTemplate_Ability"
    ability_bp: "ad7bde40de224aeca7c9807e67f5c16b"
    fx_bp_name: "Flamer4_Wide_AbilityFXSettings"
    fx_bp: "6164b3fd57c740b2be556342911aecbb"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3d3df0c7785e43c8a936b9e1cc7157d3"
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "FlamerPistolCH2Unique_Feature"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  sources: "Vendor - DrusianChapter2_VendorTable_Base 35PF"
}
weapon {
  guid: "10ad84f2802347feb90c93c79486308e"
  blueprint_name: "FlamerPistolExploder_Item"
  name_shared_key: "25b2c329-b5e4-49e0-b715-372e2f4d80f0"
  name: "The Exploder"
  description_shared_key: "12789b38-d521-4e8f-af71-1e4d6bd3ccf2"
  description: "Whenever the wielder kills a target with this hand flamer, the target explodes, dealing {uip|Damage|867dd79aad8443dd9b978a99f6dfe744} {g|Encyclopedia:FireDamage}fire damage{/g} to all creatures in a 2-cell radius and applies {g|Encyclopedia:BurningEffect}burning{/g} (9)."
  category: Pistol
  family: Flame
  heavy: false
  two_handed: false
  min_damage: 19
  max_damage: 28
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 4
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "FlamePistol_LinearTemplate_Ability"
    ability_bp: "fae6e41d51ad410099d92ccc8f342f91"
    fx_bp_name: "Flamer4_Line_AbilityFXSettings"
    fx_bp: "dd92a14ad60f4525a8769f50d209eed2"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "FlamerPistol_WideTemplate_Ability"
    ability_bp: "ad7bde40de224aeca7c9807e67f5c16b"
    fx_bp_name: "Flamer4_Wide_AbilityFXSettings"
    fx_bp: "6164b3fd57c740b2be556342911aecbb"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "867dd79aad8443dd9b978a99f6dfe744"
  extra_fact: "1b622a1337c142a2a3825744ec1d1e63"
  extra_fact_name: "FlamerPistolExploder_Feature"
  extra_fact_name: "Burning_Power12_ForWeapon_Feature"
  sources: "Chest - CR33: ImperiumMilitary_PrisonPit01"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch04_TrueStart"
}
weapon {
  guid: "04e5bc8c187a4f5dafd9f7d15d6bfa2d"
  blueprint_name: "Focus_Flamer_Item"
  name_shared_key: "38240b3e-0576-4b4c-ae23-5502a4bfa759"
  description_key: "96f72d8d-7f9c-4164-8ef1-0c42b3db1f46"
  description: "The {g|Encyclopedia:ArmourPenetration}armour penetration{/g} of this flamer is increased by +4%, but it does not inflict the {g|Encyclopedia:BurningEffect}burning{/g} effect."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 22
  max_damage: 33
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "FocusFlamer_LinearTemplate_Ability"
    ability_bp: "6b7bc5391f604f07846db1ae4688dc30"
    fx_bp_name: "Flamer10_Line_AbilityFXSettings"
    fx_bp: "03a31179363d464c9b3170034fe22967"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - ArgentaCompanion: ArgentaCompanion_Ch02_TrueMid"
  sources: "Unit - ExportedPregens: ArgentaCompanion_Level25_TesseraParty_ExportedPregen"
}
weapon {
  guid: "a7b71b397d8f437cad9442b53cc6fdad"
  blueprint_name: "GenocideAstartesFlamer_Item"
  name_shared_key: "5a942656-7445-4c89-97f7-90e381f0e188"
  name: "The Pyre"
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 60
  max_damage: 90
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 10
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate_Ability"
    ability_bp: "2e4bd45d989549a4ac235be748314b02"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: true
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "FlameProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "1b622a1337c142a2a3825744ec1d1e63"
  extra_fact_name: "Burning_Power12_ForWeapon_Feature"
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 164PF"
}
weapon {
  guid: "4033a49bac8c4355a364b971b6f600e1"
  blueprint_name: "HeavyFlamerArsonist_Item"
  name_shared_key: "f43c53d2-2b32-49ab-a88f-544aa4d39afe"
  name: "Fiery Retribution"
  description_shared_key: "5f4fbbea-b6c7-43fe-8672-489b0dfd2c0d"
  description: "This heavy flamer has an additional area attack called {g|f:0da2cd0110bf4264b6e118c8ae894930}Scorching Retribution{/g}."
  category: Heavy
  family: Flame
  heavy: true
  two_handed: true
  min_damage: 16
  max_damage: 24
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "HeavyFlamer_LinearTemplate_Ability"
    ability_bp: "afffd113dbb44e6485e3b3dd9c93856b"
    fx_bp_name: "Flamer10_Line_AbilityFXSettings"
    fx_bp: "03a31179363d464c9b3170034fe22967"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability2 {
    type: AOE
    ability_bp_name: "HeavyFlamer_WideTemplate_Ability"
    ability_bp: "06a5e88cd20048c1a5a220be09b940f7"
    fx_bp_name: "Flamer10_Wide_AbilityFXSettings"
    fx_bp: "117bf8fcfede4e38b090bf8cdc1b8f5b"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 3
  }
  ability3 {
    type: AOE
    ability_bp_name: "HeavyFlamerArsonist_WideTemplate_Ability"
    ability_bp: "0da2cd0110bf4264b6e118c8ae894930"
    fx_bp_name: "FlamerArsonist_Wide_AbilityFXSettings"
    fx_bp: "7614411c4f904128a156f8e376546055"
    on_hit_action_name: ""
    ap: 3
  }
  ability4 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 50
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  sources: "Unit - Ch02_VoidshipTemple: HumanPreacher_Ranged_VoidshipTempleAmbush"
}
weapon {
  guid: "9376156b879442d6a33f3c5bf71d7aef"
  blueprint_name: "HolyAstartesFlamer_Item"
  name_key: "4646fea9-5dde-4715-a7f9-75ed1ed6aa4f"
  name: "Triumph of the Stalwart"
  description_key: "c49d8d02-355a-4481-8ac9-d837b78305d7"
  description: "When attacking xenos and daemons with this flamer, the power of {g|Encyclopedia:BurningEffect}burning{/g} inflicted by its attacks is increased by +20."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 50
  max_damage: 75
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 10
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "44654c2484224588bb644568509ec308"
    on_hit_action_name: "HolyAstartesFlamer_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate_Ability"
    ability_bp: "2e4bd45d989549a4ac235be748314b02"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "44654c2484224588bb644568509ec308"
    on_hit_action_name: "HolyAstartesFlamer_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: true
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "FlameProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "1b622a1337c142a2a3825744ec1d1e63"
  extra_fact_name: "Burning_Power12_ForWeapon_Feature"
  sources: "Chest - NewTrashLoot: AdeptusMechanicus_SecretRoom_BigContainer_Locked"
}
weapon {
  guid: "c95453a5410547ee9c30866de2dbe960"
  blueprint_name: "JudexHeavyFlamer_Item"
  name_shared_key: "42508909-4bb9-4577-8537-a2ad37b08ffc"
  name: "Judex"
  description_shared_key: "ea9141e0-df07-4246-808a-708e1890a2f8"
  description: "If a target hit by this flamer\'s attack is suffering from burning at the end of its turn, that target explodes, inflicting burning of the same level on all enemies in a 3-cell radius. That target must pass a Willpower resistance test with a \342\210\22215 penalty or fall unconscious for 1 round."
  category: Heavy
  family: Flame
  heavy: true
  two_handed: true
  min_damage: 40
  max_damage: 44
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "HeavyFlamer_LinearTemplate_Ability"
    ability_bp: "afffd113dbb44e6485e3b3dd9c93856b"
    fx_bp_name: "Flamer10_Line_AbilityFXSettings"
    fx_bp: "03a31179363d464c9b3170034fe22967"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability2 {
    type: AOE
    ability_bp_name: "HeavyFlamer_WideTemplate_Ability"
    ability_bp: "06a5e88cd20048c1a5a220be09b940f7"
    fx_bp_name: "Flamer10_Wide_AbilityFXSettings"
    fx_bp: "117bf8fcfede4e38b090bf8cdc1b8f5b"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 60
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "da8501983ae04981b97dd9a8106be061"
  extra_fact: "1b622a1337c142a2a3825744ec1d1e63"
  extra_fact_name: "JudexHeavyFlamer_Feature"
  extra_fact_name: "Burning_Power12_ForWeapon_Feature"
  sources: "Unit - ExportedPregens: UlfarCompanion_Level47_ExportedPregen"
  sources: "Vendor - DrusianChapter4_VendorTable_Base 95PF"
}
weapon {
  guid: "a47a20d8edf14cc7bed8dba67c57d85b"
  blueprint_name: "Toxic_Flamer_Item"
  name_key: "502b9eff-568b-45e9-b606-ad91cb60a0a4"
  name: "Toxic Flamer"
  description_key: "797bd8d1-a5f7-4d41-86dd-a477aaf56236"
  description: "This flamer\'s attacks also inflict {g|Encyclopedia:ToxinEffect}toxin{/g} at the same level as {g|Encyclopedia:BurningEffect}burning{/g} is inflicted."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 35
  max_damage: 52
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "ToxicFlamerFlamer_LinearTemplate_Ability"
    ability_bp: "86ee572901334404ba66b356f1fe7dd7"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "1caeb8f07f384d1d90cd670f69f858cc"
    on_hit_action_name: "Toxic_Flamer_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "ToxicFlamer_WideTemplate_Ability"
    ability_bp: "5e78a082ee4c449cafe33592c3cba133"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "1caeb8f07f384d1d90cd670f69f858cc"
    on_hit_action_name: "Toxic_Flamer_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  sources: "Chest - CR35: ImperiumMilitary_Loot1"
  sources: "Unit - ExportedPregens: AgentaCompanion_Level47_ExportedPregen"
  sources: "Unit - ExportedPregens: Argenta_level47_Gamescom2024_ExportedPregen"
  sources: "Unit - ExportedPregens: Uralon41Argenta_ExportedPregen"
}
weapon {
  guid: "6259eb20b70a4eb7909a84b38c2faaf1"
  blueprint_name: "UnstableFlamer_Item"
  name_key: "757214e2-9d57-4471-a489-c0cf33537074"
  name: "Unstable Flamer"
  description_shared_key: "d310b61f-7ff9-4f67-afe5-cca478f9df72"
  description: "Flame weapons have 2 special area attacks with different areas of effect."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 12
  max_damage: 18
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "UnstableFlamer_Template_Ability"
    ability_bp: "283bf36967614c45b1d727504a0a5749"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  sources: "Unit - Ch02_Lair3: Lair3RebelLeader1"
  sources: "Unit - ArgentaCompanion: ArgentaCompanion_Ch03_TrueStart"
}
weapon {
  guid: "0a5e8b407f9940589d44675f42783581"
  blueprint_name: "Chapter2_Common_VindictorFlamer_Item"
  name_shared_key: "060b6a4a-7528-4e02-a713-e15a154b4c2e"
  name: "Vindictor Flamer"
  description_shared_key: "d310b61f-7ff9-4f67-afe5-cca478f9df72"
  description: "Flame weapons have 2 special area attacks with different areas of effect."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 15
  max_damage: 20
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate_Ability"
    ability_bp: "2e4bd45d989549a4ac235be748314b02"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Chapter2_Common_VindictorFlamer_MeleeSingle_Ability"
    ability_bp: "84c32baad3f14585a32f5747d721dfc3"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability4 {
    type: AOE
    ability_bp_name: "Chapter2_Common_VindictorFlamer_MeleeAOE_Ability"
    ability_bp: "9098215cb3aa482d9c44b9c03a17b8cb"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  ability5 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "b7a0ef61a3f14a67a799c30312c5b85b"
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Chapter2_Common_VindictorFlamer_Feature"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
}
weapon {
  guid: "a8eb7db3500143878aa27e1ef5aee342"
  blueprint_name: "Chapter4_Unique_LastRitesVindictorFlamer_Item"
  name_shared_key: "3a6b5f36-1e01-40bd-bdfb-9a0b9b89a88b"
  name: "Undertaker"
  description_shared_key: "d4ffdea8-a0ff-4223-bf91-043f19efecc4"
  description: "Whenever any creature in combat suffers lethal damage from {g|Encyclopedia:BurningEffect}burning{/g}, the wielder deals +30% more damage with this weapon for 1 {g|Encyclopedia:Round}round{/g}. Does not stack."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 45
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 4
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate_Ability"
    ability_bp: "2e4bd45d989549a4ac235be748314b02"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Chapter4_Unique_LastRitesVindictorFlamer_MeleeSingle_Ability"
    ability_bp: "04a11e3c9d2545ea8c3cba0c7f162e76"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability4 {
    type: AOE
    ability_bp_name: "Chapter4_Unique_LastRitesVindictorFlamer_MeleeAOE_Ability"
    ability_bp: "a5b3218e633d48abadb4d0622edf8ad9"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  ability5 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact: "b7a0ef61a3f14a67a799c30312c5b85b"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "324c90b27fe64ab9b1f76e039b574a91"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  extra_fact_name: "Chapter2_Common_VindictorFlamer_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Chapter4_Unique_LastRitesVindictorFlamer_Feature"
  sources: "Vendor - DrusianChapter4_VendorTable_Base 100PF"
}
weapon {
  guid: "f0cad68a42934b6c81c5311446194009"
  blueprint_name: "Chapter5_Unique_BurnAndSlashVindictorFlamer_Item"
  name_shared_key: "7ee87ef5-492e-432f-b88a-12dd39ac7a06"
  name: "Insatiable"
  description_shared_key: "1889feb0-9931-4ad9-87d0-797020144a67"
  description: "{g|Encyclopedia:MeleeAttacksGlossary}Melee attacks{/g} from this weapon against {g|Encyclopedia:BurningEffect}burning{/g} targets deal +<u>(5 \303\227 target\'s burning level)</u>% more damage."
  category: Basic
  family: Flame
  heavy: false
  two_handed: true
  min_damage: 35
  max_damage: 50
  penetration: 5
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Flamer_LinearTemplate_Ability"
    ability_bp: "28c50008a37043aea3e69248daf653f3"
    fx_bp_name: "Flamer7_Line_AbilityFXSettings"
    fx_bp: "4cbceb122a4346be8236f63ddf6db744"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Flamer_WideTemplate_Ability"
    ability_bp: "2e4bd45d989549a4ac235be748314b02"
    fx_bp_name: "Flamer7_Wide_AbilityFXSettings"
    fx_bp: "46e4984e71c64599b29f2ecc72bbb7fa"
    on_hit_actions: "208c51ecc500499c969c92db7d2b8488"
    on_hit_action_name: "FlamersBurning_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Chapter5_Unique_BurnAndSlashVindictorFlamer_MeleeSingle_Ability"
    ability_bp: "bca8e6d20b364e73997ccf6adaa3f0e8"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 1
  }
  ability4 {
    type: AOE
    ability_bp_name: "Chapter5_Unique_BurnAndSlashVindictorFlamer_MeleeAOE_Ability"
    ability_bp: "260eb1616c7b47e8b5c09c830315a288"
    fx_bp_name: "ChainSword_AbilityFXSettings"
    fx_bp: "046cf83ca27244998b0603750d4a833e"
    on_hit_action_name: ""
    ap: 2
  }
  ability5 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "fc6d24dc538f45dc97f10f8b6486c043"
    bp_name: "FlameProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "e6bed806d0c24fc891f60afe7202dd32"
  extra_fact: "37439b2ae5a74baab9fd188c0f8521b2"
  extra_fact: "903bb235e56d4dbebbfaf9372976b66f"
  extra_fact: "b7a0ef61a3f14a67a799c30312c5b85b"
  extra_fact_name: "Chapter5_Unique_BurnAndSlashVindictorFlamer_Feature"
  extra_fact_name: "Burning_Power10_ForWeapon_Feature"
  extra_fact_name: "ChainCritDamage50_Feature"
  extra_fact_name: "Chapter2_Common_VindictorFlamer_Feature"
  sources: "Chest - TechArcGrave_Lair: AdeptusMechanicus_ExploratorConfession_DLC2"
}

