# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "24db44debaed469386fad90088c20ee9"
  blueprint_name: "AncientForceSword_Item"
  name_shared_key: "21c82e5f-ca0b-437d-ada3-22f07133c668"
  name: "Ancient Force Sword"
  description_shared_key: "b46bde42-706b-4b66-8d77-2dadeb27de78"
  description: "Whenever the wielder suffers energy, fire, power, or warp damage, this sword absorbs a part of that damage, reducing it by \342\210\222{uip|Damage|3ccf46b177184d7b886568fa5451c43b}%. The wielder gains +{uip|Range|3ccf46b177184d7b886568fa5451c43b}% armour penetration for their next attack. Stacks."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 14
  max_damage: 20
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "AncientForceSword_AbilityFXSettings"
    fx_bp: "7fa8cbc4cc964efca690ac8fa000b2d5"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "AncientForceSword_AbilityFXSettings"
    fx_bp: "7fa8cbc4cc964efca690ac8fa000b2d5"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "AncientForceSword_AbilityFXSettings"
    fx_bp: "7fa8cbc4cc964efca690ac8fa000b2d5"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "3ccf46b177184d7b886568fa5451c43b"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "AncientForceSword_Feature"
  sources: "Chest - Test: TestRaritiesLoot"
  sources: "Chest - CR0: KhraveRuinsPuzzle01"
  sources: "Unit - Ch05_Epitaph: Ch05Inquisitor_Heinrix_unit"
  sources: "Unit - Ch05_Epitaph: Ch05Inquisitor_Melee_unit"
  sources: "Unit - ExportedPregens: 4y6_Heinrix_22lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_level27_VasyaParty_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level29_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level47_ExportedPregen"
  sources: "Unit - ExportedPregens: Heinrix_level47_Gamescom2024_ExportedPregen"
  sources: "Unit - ExportedPregens: Henrix35Yremeris_ExportedPregen"
}
weapon {
  guid: "73dfc37152024206b3994abd34347da8"
  blueprint_name: "ChaosSword_Item"
  name_shared_key: "4fb9ad5c-639d-42d5-a423-cbdff941b01b"
  name: "Edge of the Irrevocable"
  description_shared_key: "b78eac69-4f0c-4355-ba92-e2899f297c05"
  description: "Requires {g|Encyclopedia:SoulMarkCorruption}Heretical{/g} \342\200\224 Zealot\\nEach successful attack with Edge of the Irrevocable raises {g|Encyclopedia:VeilThickness}veil degradation{/g} by +<u>(from 1 to 5)</u> and deals an additional +{uip|Damage|cce8d529e407406695a7cc7dde1ebe70} {g|Encyclopedia:WarpDamage}warp damage{/g}. It also grants:\\n-<indent=5%>All allies deal +{uip|AllyDamage|cce8d529e407406695a7cc7dde1ebe70}% additional {g|Encyclopedia:DamageGlossary}damage{/g}.</indent>\\n-<indent=5%>The wielder gains +{uip|PsyRating|cce8d529e407406695a7cc7dde1ebe70} (minimum of +1) additional {g|Encyclopedia:PsyRating}psy rating{/g}.</indent>\\n-<indent=5%>If veil degradation reaches 20, successful attacks with Edge of the Irrevocable trigger {g|Encyclopedia:PerilsOfWarp}perils of the warp{/g}.</indent>\\n-<indent=5%>If veil degradation ever drops to 0, Edge of the Irrevocable loses all its powers until the end of combat.</indent>"
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: true
  min_damage: 40
  max_damage: 50
  penetration: 45
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "AncientForceSword_AbilityFXSettings"
    fx_bp: "7fa8cbc4cc964efca690ac8fa000b2d5"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "MeleeAoESTwoHandedSword_ability"
    ability_bp: "163013a18e9c46419b2311454ad2b2c8"
    fx_bp_name: "AncientForceSword_AbilityFXSettings"
    fx_bp: "7fa8cbc4cc964efca690ac8fa000b2d5"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "AncientForceSword_AbilityFXSettings"
    fx_bp: "7fa8cbc4cc964efca690ac8fa000b2d5"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "cbcf86f7262b4445958da0e2541b8c64"
    bp_name: "CorruptionSoulMark_4"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "cce8d529e407406695a7cc7dde1ebe70"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "ChaosSword_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "Parry10_Feature"
}
weapon {
  guid: "7d145260c96243869af97d0b300d420a"
  blueprint_name: "ForceSword_Item"
  name_shared_key: "2cf7fd6c-6852-4fae-9c32-a68202ecc180"
  name: "Force Sword"
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 7
  max_damage: 11
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - Ch04_LairCliff: ChaosCultist_Melee"
  sources: "Unit - Ch02_ForgeWorldAndHeart: HeinrixCompanionCopy"
  sources: "Unit - Companions: CompanionHeinrixPrototype"
  sources: "Unit - ExportedPregens: Heinrix19Chapel_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level19_HarmonParty_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level22_NeiliusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level27_CyrusParty_ExportedPregen"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion"
  sources: "Unit - HeinrixCompanion: HeinrixCompanionNPC"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch02_TrueMid"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch02_TrueStart"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch03_TrueStart"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Gamescom"
}
weapon {
  guid: "ffec3e6ca92043b29c435d677985fc8c"
  blueprint_name: "ForceSwordCH1Unique1_Item"
  name_shared_key: "a7b08498-b2f6-4fd5-a281-ace68d7f875d"
  name: "Soulsiphon"
  description_shared_key: "e536efd0-b286-4f58-960d-ffafa2d30b9a"
  description: "If used by a psyker, whenever this sword hits an enemy, veil degradation is reduced by \342\210\2221."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 8
  max_damage: 12
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "dc4bf5a9f7cd4fe0a572313115f46177"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH1Unique1_Feature"
  sources: "Vendor - ExploratorChapter1_VendorTable_Base 10PF"
}
weapon {
  guid: "4dbd3d83e1f542d5b1b35dbc9a3ce6e9"
  blueprint_name: "ForceSwordCH1Unique2_Item"
  name_shared_key: "263ca05e-7343-4c85-8986-591deb807f96"
  name: "Veilrender"
  description_shared_key: "ec3dcd59-0d8a-4448-a54a-c8cd5aa6cecd"
  description: "Each critical hit scored with this sword increases veil degradation by +{uip|Range|b80f6440487547fb8f3ab4e85bed493a}. The next attack with this sword deals +{uip|Damage|b80f6440487547fb8f3ab4e85bed493a} more damage."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 8
  max_damage: 12
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "b80f6440487547fb8f3ab4e85bed493a"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH1Unique2_Feature"
  sources: "Unit - ExportedPregens: VasiliyHeinrix_15LvL_ExportedPregen"
  sources: "Vendor - PirateChapter1_VendorTable_Base 9PF"
}
weapon {
  guid: "48ad9b97df454a6193d03ce18a54512d"
  blueprint_name: "ForceSwordCH2Unique1_Item"
  name_shared_key: "870cae04-35e1-4124-bbf5-016b9f866363"
  name: "Triumph of Retribution"
  description_shared_key: "1dda13af-e1bd-4758-b428-fcbf47f03681"
  description: "Whenever the wielder kills an enemy with this weapon, veil degradation is reduced by \342\210\222{uip|Damage|141f119fbbc54b08abc49f74786e9ca5}."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 12
  max_damage: 16
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "141f119fbbc54b08abc49f74786e9ca5"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH2Unique1_Feature"
  sources: "Vendor - DrusianChapter2_VendorTable_Base 36PF"
}
weapon {
  guid: "b6e69939220e4338bc07519cae3c860e"
  blueprint_name: "ForceSwordCH2Unique2_Item"
  name_shared_key: "0ee7799a-45ff-4a8f-af23-d4d6c415cb3a"
  name: "Awakened Nightmare"
  description_shared_key: "a43cf916-e42b-48a4-9eca-fd37d08ac1b7"
  description: "Each area attack made with this weapon increases veil degradation by +{uip|Range|d1bd880bf4944374aefe0fe6ce5082dd} and deals +{uip|Damage|d1bd880bf4944374aefe0fe6ce5082dd}% more damage."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 13
  max_damage: 18
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "d1bd880bf4944374aefe0fe6ce5082dd"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH2Unique2_Feature"
  sources: "Vendor - PirateChapter2_VendorTable_Base 49PF"
}
weapon {
  guid: "3620f05386b44a0d86f2ffc6ee4ab0b3"
  blueprint_name: "ForceSwordCH2Unique3_Item"
  name_shared_key: "7ae9cccc-defd-45d9-8818-cb8d3f307e47"
  name: "Will to Live"
  description_shared_key: "a58993d5-fb92-4d3e-bbca-ab1489ed5ae1"
  description: "Enemies adjacent to the wielder have their Toughness reduced by \342\210\222{uip|Range|c88058271fb1472c8c54a63b68f43a40}. The wielder gains +{uip|Range|c88058271fb1472c8c54a63b68f43a40} Toughness for each adjacent enemy."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 10
  max_damage: 15
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "c88058271fb1472c8c54a63b68f43a40"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH2Unique3_Feature"
  sources: "Unit - ExportedPregens: 4y6_Heinrix_27lvl_ExportedPregen_ExportedPregen"
  sources: "Vendor - ExploratorChapter2_VendorTable_Base 31PF"
}
weapon {
  guid: "6e959928644941898894055a95dcc199"
  blueprint_name: "ForceSwordCH2Unique4_Item"
  name_shared_key: "31980b8b-d08e-4206-9275-1bddc245bbdb"
  name: "Cursebringer"
  description_shared_key: "47dfddfc-dde6-4e70-a783-902aa958e484"
  description: "When this weapon hits, the target must pass a Willpower resistance test or suffer {uip|Damage|02095d0bf4604c7ea77d876cb876256d} levels of {g|f:3ddbf131cbd54087a665d4b2e026b0f2}warp burn{/g}."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 14
  max_damage: 20
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "02095d0bf4604c7ea77d876cb876256d"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH2Unique4_Feature"
  sources: "Vendor - LiegeChapter2_VendorTable_Base 62PF"
}
weapon {
  guid: "75d5aa9e45b9440ca68d8ffaa99146ea"
  blueprint_name: "ForceSwordCH3Unique1_Item"
  name_shared_key: "83bf8a2a-6c3e-4731-a0b3-c4c134ae1b4c"
  name: "The Distortion"
  description_shared_key: "c97dbe32-f0c9-4990-a4b1-142dd2407481"
  description: "Each area attack made with this weapon increases veil degradation by +{uip|Range|4f53637d66ef4414a96f50a7a22b7026} and deals +{uip|Damage|4f53637d66ef4414a96f50a7a22b7026}% more damage."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 17
  max_damage: 22
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedForceSwordCH3Unique1_AoEAbility"
    ability_bp: "fb0a6b00969f4bf088f3ad33d19dadb2"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "4f53637d66ef4414a96f50a7a22b7026"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH3Unique1_Feature"
  sources: "Vendor - PitBossChapter3_VendorTable_Base 0PF"
}
weapon {
  guid: "602f13303c9345e7b6887b09d6cbf85f"
  blueprint_name: "ForceSwordCH3Unique2_Item"
  name_shared_key: "cd9e626c-79d6-47a2-80d9-ec6c2209c2d9"
  name: "Renunciation of Weakness"
  description_shared_key: "4dd70ad5-6e9c-40d8-a076-862e030c9449"
  description: "Each critical hit scored with this weapon reduces veil degradation by \342\210\222{uip|Range|525bb3514e67472fa05ff18a304117d6} and increases the wielder\'s Willpower by +{uip|Damage|525bb3514e67472fa05ff18a304117d6} for 1 round."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 18
  max_damage: 23
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "525bb3514e67472fa05ff18a304117d6"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH3Unique2_Feature"
  sources: "Vendor - HaemunculiChapter3_VendorTable_Advanced 0PF"
}
weapon {
  guid: "d38487db90974273bdede761e07c1aac"
  blueprint_name: "ForceSwordCH4Unique1_Item"
  name_shared_key: "13d58f21-c9f6-4660-903e-fae1bc1def70"
  name: "Sacrifice"
  description_shared_key: "37d5ff19-24e4-4537-a244-61cd39e1b5d8"
  description: "Whenever the wielder kills an enemy with this weapon, veil degradation is reduced by the \342\210\222<u>Wielder\'s psy rating<u>. After that, the wielder gains +1 psy rating for 1 round."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 26
  max_damage: 34
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "dee57b493ba84dc8ad1c5ac03485a901"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH4Unique1_Feature"
  sources: "Vendor - DrusianChapter4_VendorTable_Base 86PF"
}
weapon {
  guid: "9b29810b0c1148639fd7aa1a3f5f313c"
  blueprint_name: "ForceSwordCH4Unique2_Item"
  name_shared_key: "a7407697-76c6-4423-9ec0-0e18ae0eee1c"
  name: "Dark Providence"
  description_shared_key: "e6b36a3e-1d93-4866-88bc-287245743676"
  description: "If the wielder is a psyker, they can immediately re-roll a failed parry attempt once per attack with a chance of success equal to their Willpower."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 20
  max_damage: 28
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "864a1b3d2f6244dc84cf573c98d4d864"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH4Unique2_Feature"
  sources: "Unit - ExportedPregens: HeinrixCompanion_35_DLC2_ExportedPregen"
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 74PF"
}
weapon {
  guid: "e933a559b09b45e3a89c51e2cb122062"
  blueprint_name: "ForceSwordCH4Unique3_Item"
  name_shared_key: "146ec524-33fa-4913-809c-18c5ae47cd38"
  name: "Immaterium\'s Channeller"
  description_shared_key: "1a662c03-285a-48ac-9c89-de882126a7a8"
  description: "If the wielder\'s psy rating is 9 or higher, this sword has its damage, dodge reduction, and armour penetration increased by a percentage equal to veil degradation."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 32
  max_damage: 40
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "fa0ba3e0311b416cae0b3a62fbf023d3"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH4Unique3_Feature"
  sources: "Vendor - PirateChapter4_VendorTable_Base 106PF"
}
weapon {
  guid: "dfcbb13715bd45d59fc09df3d95cc535"
  blueprint_name: "ForceSwordCH4Unique4_Item"
  name_shared_key: "5539b06a-857d-4e5a-a1cd-57eecb4a7d43"
  name: "Incinerator"
  description_shared_key: "21c578b0-8760-49e8-86e4-ee7a38932c24"
  description: "Each critical hit scored with this weapon inflicts {uip|Damage|dcd22529be0d4481982b04f2a4ae9fc3} levels of {g|f:3ddbf131cbd54087a665d4b2e026b0f2}warp burn{/g}."
  category: Melee
  family: Force
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 28
  max_damage: 36
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "ForceSword_AoE_AbilityFXSettings"
    fx_bp: "afab945f59b349268fca5f44e81c06ab"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "SwordsMeleeAttack_ForceAbility"
    ability_bp: "8f63a3008a614bc085b6fb56443d3f92"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "fd5c99b0b98543938875fa3c17294b71"
  extra_fact: "dcd22529be0d4481982b04f2a4ae9fc3"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "ForceSword_Feature"
  extra_fact_name: "ForceSwordCH4Unique4_Feature"
  sources: "Vendor - LiegeChapter4_VendorTable_Base 99PF"
}

