# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "b9676cf1f0554d81873f78f38087baca"
  blueprint_name: "GeneStealerHammerT1CH2_Item"
  name_shared_key: "0644eeaf-a751-4c46-b90b-c69f90b25718"
  name: "Industrial Hammer"
  category: Melee
  family: Primitive
  classification: MaulOrHammer
  heavy: false
  two_handed: true
  min_damage: 22
  max_damage: 33
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "9ecf3efd49ac4ef69d09ba08b4e6b97e"
    on_hit_action_name: "GenestealerHammer_AbilityAdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "ThunderHammer_AoE_Ability"
    ability_bp: "e986d8ac76f74d96852bfd34d71c211d"
    fx_bp_name: "ThunderHammer_AoE_AbilityFXSettings"
    fx_bp: "850188dd808741928ba92e6e3b3c5285"
    on_hit_actions: "9ecf3efd49ac4ef69d09ba08b4e6b97e"
    on_hit_action_name: "GenestealerHammer_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Vendor - PirateChapter2_VendorTable_Base 53PF"
}
weapon {
  guid: "aeff3c3f2e8d4c3f97219deecef3b3fe"
  blueprint_name: "GeneStealerHammerUnique_Item"
  name_key: "8c3eeb05-82c3-494b-a328-e175eb9e0991"
  name: "Bonecracker"
  description_key: "937e3649-8a9a-48b9-8720-53b9e26e63d9"
  description: "Every successful basic attack made with this mace inflicts a random trauma on the target."
  category: Melee
  family: Primitive
  classification: MaulOrHammer
  heavy: false
  two_handed: true
  min_damage: 28
  max_damage: 39
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "9ecf3efd49ac4ef69d09ba08b4e6b97e"
    on_hit_action_name: "GenestealerHammer_AbilityAdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "ThunderHammer_AoE_Ability"
    ability_bp: "e986d8ac76f74d96852bfd34d71c211d"
    fx_bp_name: "ThunderHammer_AoE_AbilityFXSettings"
    fx_bp: "850188dd808741928ba92e6e3b3c5285"
    on_hit_actions: "9ecf3efd49ac4ef69d09ba08b4e6b97e"
    on_hit_action_name: "GenestealerHammer_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - DLC1_VoidshipBridge: InfernusSister"
}
weapon {
  guid: "7287e2663dff4a43878d391f7a0e33a1"
  blueprint_name: "IndustrialHammer_Item"
  name_shared_key: "0644eeaf-a751-4c46-b90b-c69f90b25718"
  name: "Industrial Hammer"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 18
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "ThunderHammer_AoE_Ability"
    ability_bp: "e986d8ac76f74d96852bfd34d71c211d"
    fx_bp_name: "ThunderHammer_AoE_AbilityFXSettings"
    fx_bp: "850188dd808741928ba92e6e3b3c5285"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Vendor - PirateChapter2_VendorTable_Base 20PF"
}
weapon {
  guid: "3c24e67069b34b0bab9dada2f3d36af7"
  blueprint_name: "PowerMaulT1CH2_Item"
  name_key: "bdc6b127-d15c-4ea1-8c64-b4d962592fe2"
  name: "[Retobi-Pattern] Power Maul"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 14
  max_damage: 16
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - CR0: Forest_Chest"
  sources: "Unit - DLC2_Ch04_PenalWorld: PenalWorld_WardenMelee_NPC"
}
weapon {
  guid: "c1b16b0bec6745d39be840d75b89ef11"
  blueprint_name: "PowerMaulT1CH3_Item"
  name_key: "c5d30a4f-0003-4863-83b3-9b1e14cb40d1"
  name: "[Ryza-Pattern] Power Maul"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 16
  max_damage: 25
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
}
weapon {
  guid: "ca2cd1e5ab1a4f7eb50052be3a64e5d7"
  blueprint_name: "PowerMaulT2CH4_Item"
  name_key: "3627eaf0-c291-48b9-9992-d87de6fcbf8d"
  name: "[Mars-Pattern] Power Maul"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 25
  max_damage: 35
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - VigilCastle: ImperiumMilitary_VC_AfterBattle"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_Emelina"
}
weapon {
  guid: "79f164d848f8449396579c8d05300fe5"
  blueprint_name: "PowerMaulT2CH4_Item1"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 25
  max_damage: 35
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
}
weapon {
  guid: "bf944ffc9d0d4c7085263a866ef57905"
  blueprint_name: "PowerMaulT2CH4_variation2_Item"
  name_key: "b944a73d-8b4e-4af4-8c28-4831a3bc265d"
  name: "[Sol-Pattern] Power Maul"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 27
  max_damage: 41
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - ExportedPregens: PlayerRT_Level47_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level47_PetEagle_ExportedPregen"
  sources: "Vendor - DrusianChapter4_VendorTable_Base 77PF"
}
weapon {
  guid: "9cb620541c2847d4829aec6cf61bf2a2"
  blueprint_name: "PowerMaulT2CH5_Item"
  name_shared_key: "9dff5e78-8373-46fe-a8bf-8fca1e6f2bb7"
  name: "Power Maul"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 32
  max_damage: 49
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - DLC1_LowerTunnels: EnforcerNeofitCH04LT_Melee_Common_Uniq"
}
weapon {
  guid: "4e020e39ed9149f2913e0350d850c6fd"
  blueprint_name: "PowerMaulT2_Item"
  name_shared_key: "d05dd4a9-2e26-4ca0-ae60-ea511343bfe7"
  name: "Master-Crafted Power Maul"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 10
  max_damage: 17
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - CR19: AdeptusMechanicus_Hidden2"
  sources: "Chest - CR22: Forge_PuzzleRoomLoot"
  sources: "Unit - ExportedPregens: 4y6_Heinrix_22lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level47_ExportedPregen"
  sources: "Unit - ExportedPregens: zin_22_KibellahCompanion_ExportedPregen"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_22lvl_Overseer"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_22lvl_WithGlaito"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_27lvl_Overseer"
}
weapon {
  guid: "33170608963441409d260ff82b74ae42"
  blueprint_name: "PowerMaul_Item"
  name_shared_key: "9dff5e78-8373-46fe-a8bf-8fca1e6f2bb7"
  name: "Power Maul"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 7
  max_damage: 10
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedSkitariiPower_Melee"
  sources: "Unit - Ch02_Lair3: Lair3RebelMeleeSwarm"
  sources: "Unit - Ch02_PascalEvent: Tarzus_Skitarii_Melee"
  sources: "Unit - Ch03_Prison: ImperialZealot_Melee_Prison"
  sources: "Unit - Ch04_LairCliff: ChaosCultist_HeavyMelee"
  sources: "Unit - Companions: CompanionAbelardPrototype"
  sources: "Unit - AbelardCompanion: AbelardCompanion"
  sources: "Unit - AbelardCompanion: AbelardCompanion_SoundTest"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level19_HarmonParty_ExportedPregen"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level22_NeiliusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level27_CyrusParty_ExportedPregen"
  sources: "Vendor - PirateChapter1_VendorTable_Base 12PF"
}
weapon {
  guid: "1dba99207b45494f96a9a4d6ffa23c5f"
  blueprint_name: "ShockBatonT2_Item"
  name_shared_key: "6125429b-99ae-4363-a0b0-87906c08d41e"
  name: "Heavy Shock Baton"
  description_shared_key: "cb66fdfc-8f8a-442d-a413-ada924ef07c1"
  description: "Maces and hammers have a special attack that {g|Encyclopedia:PushGlossary}pushes{/g} enemies away."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 19
  max_damage: 20
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - DLC1_LowerTunnels: EnforcerNeofitCH04LT_Melee_Common"
  sources: "Unit - DLC1_OfficerDeckPeacefull: ChirurgeonMajoris"
  sources: "Unit - DLC1_OfficerDeckPeacefull: MasterofDiscipline"
  sources: "Unit - DLC1_OfficerDeckPeacefull: MasterofDiscipline_Prologue"
  sources: "Unit - DLC1_VoidshipReactor: MDLadyOfSteel"
}
weapon {
  guid: "aa877cb85c9b48918907fdb562b718bf"
  blueprint_name: "ShockBaton_Item"
  name_key: "ea7e1966-b7d0-4981-b0fc-848574b5492f"
  name: "Shock Baton"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 6
  max_damage: 11
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - Ch00_OfficersDeck: OfficersDeckGuard_Baton"
  sources: "Unit - Ch01_JailPlanetoid: JailPlanetoidEnforcerBatton"
  sources: "Unit - Ch01_Starport: StarportRebelMeleeBaton"
  sources: "Unit - Ch01_Starport: StarportRebelMeleeBully"
  sources: "Unit - Ch01_Starport: StarportRebelMeleeBully1"
  sources: "Unit - Ch01_Starport: StarportRebelMeleeBullyWithGrenade"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsRebelMelee"
  sources: "Unit - Ch02_FootfallDock: Footfall_Enforcer"
  sources: "Unit - Ch02_FootfallDock: Footfall_EnforcerDelegation"
  sources: "Unit - Ch02_FootfallDock: Footfall_EnforcerFemale"
  sources: "Unit - Ch02_FootfallDock: Footfall_RiotGuard"
  sources: "Unit - Ch02_FootfallDock: Footfall_TestVendor"
  sources: "Unit - Ch02_FootfallDock: Footfall_TestVendor_ReputationTest"
  sources: "Unit - Ch02_FootfallDock: Footfall_ValadaimAgent"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_Guard"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_Guard1"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_Guard2"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_GuardF"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_Miner"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_MinerNaked"
  sources: "Unit - DLC1_LowerTunnels: LT_AngryEnforcer_Unique"
  sources: "Unit - DLC1_LowerTunnels: LT_EnforcerGuard"
  sources: "Unit - DLC1_LowerTunnels: LT_EnforcerMed"
  sources: "Unit - DLC1_LowerTunnels: LT_Fighter_Faith"
  sources: "Unit - DLC1_LowerTunnels: LT_Foreman"
  sources: "Unit - DLC2_BoardedShip_Bridge: BoardedShip_Bridge_Melee_Ally_Swarm"
  sources: "Unit - DLC2_BoardedShip_Bridge: BoardedShip_Bridge_Melee_Swarm"
  sources: "Unit - Ch02_DestroyedBlackShip: PsykerAlphaShip"
  sources: "Unit - Ch02_LowerDecks: RabbleLeaderStrong"
  sources: "Unit - Ch04_Canteena: Ch04Hieronimus_Enforcer_unit"
  sources: "Unit - DLC1_VoidshipReactor: EnforcerPDChambers"
  sources: "Unit - DLC1_VoidshipReactor: EnforcerPDChambersBefore"
  sources: "Unit - DLC1_VoidshipReactor: Naij"
  sources: "Unit - DLC1_VoidshipReactor: PDSparkMan"
  sources: "Unit - DLC1_VoidshipReactor: PDSparkManBefore"
  sources: "Unit - DLC1_VoidshipReactor: PDSparkWoman"
  sources: "Unit - DLC1_VoidshipReactor: PDSparkWomanBefore"
  sources: "Unit - DLC1_VoidshipReactor: TalkerPDChambers"
  sources: "Unit - DLC1_VoidshipReactor: TalkerPDChambersBefore"
  sources: "Unit - Ch04: Footfall_ChordaEnforcer02_Melee"
  sources: "Unit - Ch04: Footfall_ChordaEnforcer03"
  sources: "Unit - Ch04: Footfall_ChordaEnforcer04"
  sources: "Unit - Ch04: Footfall_ChordaEnforcer_Melee"
  sources: "Unit - Ch04: Footfall_VladaymEnforcer"
  sources: "Unit - Ch04: Footfall_VladaymEnforcerFemale"
  sources: "Unit - Ch02_Footfall: SideQuestFidelio_Servitor"
}
weapon {
  guid: "23977cb9890d46658c394d31406cb236"
  blueprint_name: "ThunderHammerT1CH3_Item"
  name_key: "b7c47b8d-94e8-45aa-9cc0-b55153387fb5"
  name: "[Ryza-Pattern] Thunder Hammer"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: true
  min_damage: 18
  max_damage: 26
  penetration: 50
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "ThunderHammer_AoE_Ability"
    ability_bp: "e986d8ac76f74d96852bfd34d71c211d"
    fx_bp_name: "ThunderHammer_AoE_AbilityFXSettings"
    fx_bp: "850188dd808741928ba92e6e3b3c5285"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - CR33: ImperiumMilitary_ComisarChest"
}
weapon {
  guid: "795423d6d4de42359b3c2325129d13bd"
  blueprint_name: "ThunderHammerT2CH4_Item"
  name_key: "9f0aed23-fff8-4625-b960-0a48901061d6"
  name: "[Mars-Pattern] Thunder Hammer"
  description_key: "473eb243-58df-40eb-b53f-0f38c825ecc6"
  description: "Attacks with this hammer always critically {g|Encyclopedia:HitSequenceGlossary}hit{/g} against {g|Encyclopedia:Stun}stunned{/g} and {g|Encyclopedia:ProneEffect}prone{/g} targets. The {g|Encyclopedia:CritChancesAndCritDamageGlossary}critical damage{/g} is increased by +80%."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: true
  min_damage: 28
  max_damage: 39
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "ThunderHammer_AoE_Ability"
    ability_bp: "e986d8ac76f74d96852bfd34d71c211d"
    fx_bp_name: "ThunderHammer_AoE_AbilityFXSettings"
    fx_bp: "850188dd808741928ba92e6e3b3c5285"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "f05fea51b44d4176a2ddff963fdbdc4f"
  extra_fact_name: "ThunderHammerT2CH4_Feature"
  sources: "Unit - Ch02_VoidshipOfficersDeck: GenestealerSeneschal_Melee_PatriarchVisions"
  sources: "Unit - Ch02_VoidshipOfficersDeck: GenestealerZealot_Melee_PatriarchVisions"
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 144PF"
}
weapon {
  guid: "a346d0ed1a074155a9d06bb4ffac13e7"
  blueprint_name: "ThunderHammerT2_Item"
  name_shared_key: "fabc5cf4-4117-4fb7-b723-c248bd96028a"
  name: "Emperor\'s Will"
  description_key: "c5d88ee0-6a4c-45ac-a35a-bf7b28cd3dcf"
  description: "On a successful {g|Encyclopedia:HitSequenceGlossary}hit{/g} with this weapon, the target must pass a {g|Encyclopedia:WarhammerToughness}Toughness{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} with a \342\210\22210 {g|Encyclopedia:Penalty}penalty{/g} or become {g|Encyclopedia:Stun}stunned{/g}. If the target fails the test, this attack has no {g|Encyclopedia:Cooldown}cooldown{/g}."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: true
  min_damage: 25
  max_damage: 35
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "ThunderHammer_AoE_Ability"
    ability_bp: "e986d8ac76f74d96852bfd34d71c211d"
    fx_bp_name: "ThunderHammer_AoE_AbilityFXSettings"
    fx_bp: "850188dd808741928ba92e6e3b3c5285"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "1144257bb4744767b6918f861d665acf"
  extra_fact_name: "ThunderHammerT2_Feature"
}
weapon {
  guid: "2c8ce78dacb04e7da9190cc5dd443874"
  blueprint_name: "ThunderHammer_Item"
  name_key: "d873b68c-083c-49dc-bccb-6c10d5e4cb57"
  name: "Thunder Hammer"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: true
  min_damage: 11
  max_damage: 17
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "ThunderHammer_AoE_Ability"
    ability_bp: "e986d8ac76f74d96852bfd34d71c211d"
    fx_bp_name: "ThunderHammer_AoE_AbilityFXSettings"
    fx_bp: "850188dd808741928ba92e6e3b3c5285"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - Ch02_FootfallDock: FootfallAnverChargerLeader_Melee_Elite"
  sources: "Unit - Ch02_RogueTraderPalace: GladiatorWHammer"
  sources: "Unit - ExportedPregens: PascalCompanion_Level25_TesseraParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_level27_VasyaParty_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_23_Abelard_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_Abelar_23lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: Yanus19Hen_ExportedPregen"
}
weapon {
  guid: "1e8a09ba6138475c9f105761ba245afb"
  blueprint_name: "BonebreakingMaul_PowerMaul_Item"
  name_shared_key: "98d0969a-7a07-4784-b983-fe9d1cfc19f6"
  name: "Bonebreaker Maul"
  description_shared_key: "c5823d3d-6b7a-4ff9-842b-3d57434922fa"
  description: "When you {g|Encyclopedia:HitSequenceGlossary}hit{/g} an enemy with the bonebreaker maul, the target must pass a {g|Encyclopedia:WarhammerToughness}Toughness{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} with a \342\210\22210 {g|Encyclopedia:Penalty}penalty{/g} or fall {g|Encyclopedia:ProneEffect}prone{/g} and gain random {g|Encyclopedia:Traumas}trauma{/g}."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 25
  max_damage: 30
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "5656c3af34764b4985aaf0ddef31f1f4"
  extra_fact_name: "BonebreakingMaul_PowerMaul_Feature"
  sources: "Chest - CR0: AdeptusMechanicus_SignedOrder"
  sources: "Unit - Ch05_Epitaph: AbelardAlternative"
  sources: "Unit - ExportedPregens: AbelardCompanion_lvl38_treasureworld_ExportedPregen"
  sources: "Unit - ExportedPregens: abelard_lv38_chordafight_ExportedPregen"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_38lvl_Overseer"
}
weapon {
  guid: "e5b1ed9d266c43a5a56b514529001c14"
  blueprint_name: "CognatineHammer_Item"
  name_shared_key: "d8360a86-b4ba-41d1-8f60-2229ec221195"
  description_shared_key: "aa1f3359-9677-48ca-a042-fcbd8f8a8bb8"
  description: "All {g|Encyclopedia:DamageGlossary}damage{/g} dealt when this weapon {g|Encyclopedia:PushGlossary}pushes{/g} an enemy is increased by +100%."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: true
  min_damage: 15
  max_damage: 20
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "ThunderHammer_AoE_Ability"
    ability_bp: "e986d8ac76f74d96852bfd34d71c211d"
    fx_bp_name: "ThunderHammer_AoE_AbilityFXSettings"
    fx_bp: "850188dd808741928ba92e6e3b3c5285"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "e962ba49198b4911856d6585354f5ed1"
  extra_fact_name: "CognatineHammer_Feature"
}
weapon {
  guid: "3ae1104c65ed44448e61a181bf527885"
  blueprint_name: "PowerMaulCH1Unique_Item"
  name_key: "6e0df5ce-b04e-431c-99ef-c669f3039fe4"
  name: "Unquenchable Fury"
  description_key: "c436046d-7593-44e5-81fd-c8c4d0173faa"
  description: "The maximum {g|Encyclopedia:PushGlossary}push{/g} distance of this maul is 5 cells, and any collision damage is increased by +50%."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 8
  max_damage: 9
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "2c8a705e21f748a18e57169c837c967e"
    on_hit_action_name: "Hammer_Push5AbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "619f5ea9a75b40ad8c491a63780d6c9b"
  extra_fact_name: "PowerMaulCH1Unique_Feature"
  sources: "Chest - VoidshipReliquary: AdeptusMechanicus_SwordLoot"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level15_ExportedPregen"
}
weapon {
  guid: "ade735e5ee0047c8928404c26bf90333"
  blueprint_name: "PowerMaulCH2Unique_Item"
  name_shared_key: "64366ef9-3062-41c2-a913-67ebaa1134dd"
  name: "Earthbreaker"
  description_shared_key: "2dabc311-c05e-4ea2-ac76-f1278b6c90d8"
  description: "Each attack with this weapon decreases the target\'s {g|Encyclopedia:WarhammerAgility}Agility{/g}, {g|Encyclopedia:WarhammerToughness}Toughness{/g}, and {g|Encyclopedia:WarhammerStrength}Strength{/g} by \342\210\2224, even when parried or {g|Encyclopedia:DodgeGlossary}dodged{/g}."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 16
  max_damage: 23
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "e5da9cad65d243caa7337fbc97bdc4d7"
  extra_fact_name: "PowerMaulCH2Unique_Feature"
  sources: "Vendor - PirateChapter2_VendorTable_Base 51PF"
}
weapon {
  guid: "86970d2bac284aecae61ff4865b4af01"
  blueprint_name: "RoaringThunder_ThunderHammer_Item"
  name_key: "eaf1aaa9-90dc-415f-a117-706d801020e3"
  name: "Roaring Thunder"
  description_key: "e0dad650-6846-4769-af05-456a5e5f1159"
  description: "This thunder hammer deals +3 {g|Encyclopedia:DamageGlossary}damage{/g} and grants a +10% stacking chance to stun an enemy for one {g|Encyclopedia:Turn}turn{/g} for each point of the enemy\'s {g|Encyclopedia:Deflection}deflection{/g}.\\nA successful {g|Encyclopedia:WarhammerToughness}Toughness{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} negates this effect.\\n<i>Maces and hammers have a special attack that {g|Encyclopedia:PushGlossary}pushes{/g} enemies away.</i>"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: true
  min_damage: 20
  max_damage: 25
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "RoaringThunder_AoEAbility"
    ability_bp: "9a65564e4c9b4bf8841560feec4f110f"
    fx_bp_name: "AberrantHammerStrike03_AbilityFXSettings"
    fx_bp: "8a6d92bc247f4feda1d649d4d21db900"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "cffbdaadf80e4ee095fe845ddc41e98c"
  extra_fact_name: "RoaringThunder_Feature"
  sources: "Unit - Ch05_Epitaph: InquisitorCh5"
  sources: "Unit - ExportedPregens: Abelard35Yremeris_ExportedPregen"
  sources: "Unit - ExportedPregens: PascalCompanion_Level47_ExportedPregen"
  sources: "Vendor - DrusianChapter2_VendorTable_Base 47PF"
}
weapon {
  guid: "754ac64896a24d5cb3e829725e3ff012"
  blueprint_name: "ShockBatonCH3Unique_Item"
  name_shared_key: "3378390c-77c3-4619-a2c5-1e9810a8ed59"
  name: "Lawbringer"
  description_shared_key: "72ffed70-eb0b-4c21-80b9-e66d1e73ee21"
  description: "Grants an additional {g|Encyclopedia:Ability}ability{/g} that ends the attacker\'s {g|Encyclopedia:Turn}turn{/g} and deals an additional +30 {g|Encyclopedia:MachineDamage}machine damage{/g} with 50% {g|Encyclopedia:ArmourPenetration}armour penetration{/g}."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 16
  max_damage: 24
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  ability4 {
    type: SingleShot
    ability_bp_name: "ShockBatonCH3Unique_Ability"
    ability_bp: "c8598cbd88b04d7997a2750ab99d3b42"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - CR33: ImperiumMilitary_PrisonBottom02"
}
weapon {
  guid: "a922a79edfc849ddba568bd152fa9f3e"
  blueprint_name: "ThunderHammerCognatius_Item"
  name_shared_key: "08c82abc-81a6-43e2-8e47-4d0bba9ad55b"
  description_key: "fff58819-30f5-4df1-9979-67282333a601"
  description: "All collisions caused by the thunder hammer\'s {g|Encyclopedia:PushGlossary}pushing{/g} attacks deal +300% more {g|Encyclopedia:DamageGlossary}damage{/g}.\\nAll targets {g|Encyclopedia:HitSequenceGlossary}hit{/g} by this thunder hammer must pass an {g|Encyclopedia:WarhammerAgility}Agility{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} with a +10 {g|Encyclopedia:Bonus}bonus{/g} or fall {g|Encyclopedia:ProneEffect}prone{/g}."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: true
  min_damage: 28
  max_damage: 42
  penetration: 45
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "ThunderHammer_AoE_Ability"
    ability_bp: "e986d8ac76f74d96852bfd34d71c211d"
    fx_bp_name: "ThunderHammer_AoE_AbilityFXSettings"
    fx_bp: "850188dd808741928ba92e6e3b3c5285"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "ThunderHammer_AbilityFXSettings"
    fx_bp: "6256056e200842b2af3a637fb37d6331"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "f47ad413323b4594bff7eaca1a3b5bff"
  extra_fact_name: "ThunderHammerCognatius_Feature"
  sources: "Unit - ExportedPregens: Uralon41Abel_ExportedPregen"
}
weapon {
  guid: "d97225a9905b44b898b021b7f1984277"
  blueprint_name: "Chapter1_Unique_PneumaticMaul_Item"
  name_shared_key: "2b549f84-4944-4d11-997c-7f7368a07d75"
  name: "Balanced Maul"
  description_shared_key: "eac841d3-540a-4379-9090-2d5987a6ed61"
  description: "This maul\'s {g|f: bd5f109c46684a09b07fb13743d2a6d7}Harsh Shove{/g} {g|Encyclopedia:Ability}ability{/g} costs 1 {g|Encyclopedia:ActionPoints}AP{/g}.\\nAdditionally, the wielder can use {g|f:0ff8e6e3f2ac4b94a24ef8623d286084}Shoving Strike{/g}, which costs 2 AP against multiple enemies in an area."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 6
  max_damage: 11
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 1
  }
  ability4 {
    type: AOE
    ability_bp_name: "Chapter1_Unique_PneumaticMaul_AoE_Ability"
    ability_bp: "0ff8e6e3f2ac4b94a24ef8623d286084"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "619f5ea9a75b40ad8c491a63780d6c9b"
  extra_fact_name: "PowerMaulCH1Unique_Feature"
  sources: "Unit - ExportedPregens: Solomorne_LvL28_Varl1n_v2_ExportedPregen"
  sources: "Unit - ExportedPregens: Solomorne_LvL28_Varl1n_v2_ExportedPregen_OLD"
  sources: "Vendor - ExploratorChapter1_VendorTable_Base 14PF"
}
weapon {
  guid: "e7b66906f6b24f9da7375b29a44f63e4"
  blueprint_name: "Chapter2_Pattern_ShockBaton_Item"
  name_shared_key: "f2f2a45c-d941-4428-b2e4-8517af001ba9"
  name: "Excruciator Maul"
  description_shared_key: "cb66fdfc-8f8a-442d-a413-ada924ef07c1"
  description: "Maces and hammers have a special attack that {g|Encyclopedia:PushGlossary}pushes{/g} enemies away."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 15
  max_damage: 20
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - DLC2_CH01_StarPort: ArbitratorBryce_Subductor"
  sources: "Unit - DLC2_CH01_StarPort: ArbitratorStein_Subductor"
  sources: "Unit - DLC2_CH01_StarPort: SolomorneCompanion_22lvl_OverseerNPC"
  sources: "Vendor - DrusianChapter2_VendorTable_Base 20PF"
}
weapon {
  guid: "0203a8e5aa8d4c44bc165bada7b1fe37"
  blueprint_name: "Chapter2_Unique_BashingMaul_Item"
  name_shared_key: "d8cefade-7f85-405f-b5b5-cce324f3ba00"
  name: "Heavy Maul"
  description_shared_key: "da5111ce-f03c-43a6-969a-1ff394e00e6d"
  description: "If the wielder has a shield equipped, whenever they {g|Encyclopedia:HitSequenceGlossary}hit{/g} the target with this maul, they immediately make a {g|f:1c5f4edca9f64fe0911bc946e0b4ea4a}Shield Bash{/g} against that target. If it hits, the target must pass a {g|Encyclopedia:WarhammerToughness}Toughness{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} with a +20 bonus or become {g|Encyclopedia:Stun}stunned{/g} for 1 {g|Encyclopedia:Round}round{/g}."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 14
  max_damage: 18
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "1ee8a1907c0844e2a3441b24c9469c34"
  extra_fact_name: "Chapter2_Unique_BashingMaul_Feature"
  sources: "Unit - DLC2_FeudalWorld: FW_KnightCaptain_ Melee_Hard"
}
weapon {
  guid: "ea71896d85034e1491b1caac80aed31a"
  blueprint_name: "Chapter2_Unique_CenserHeadPowerMaul_Item"
  name_shared_key: "14fe7c3e-d3a4-4464-b4d0-a20bc2e27d31"
  name: "Bloody Sacrament"
  description_shared_key: "1d0d19b3-fd8b-430e-aac5-56082e0a4b85"
  description: "{g|Encyclopedia:AreaOfEffect}Area attacks{/g} with this maul create a smoke cloud. All creatures that enter that area must pass {g|Encyclopedia:WarhammerToughness}Toughness{/g}, {g|Encyclopedia:WarhammerStrength}Strength{/g}, and {g|Encyclopedia:WarhammerWillpower}Willpower{/g} {g|Encyclopedia:ResistanceTest}resistance tests{/g} with a \342\210\222{uip|Penalty|0eaf58bc6d7d487e8b78c6a2c31bd2fb} penalty.\\n-<indent=5%>On a failed Toughness {g|Encyclopedia:Test}test{/g} the target becomes {g|Encyclopedia:BlindedEffect}blinded{/g} for 2 {g|Encyclopedia:Round}rounds{/g}.</indent>\\n-<indent=5%>On a failed Strength test \342\200\224 {g|Encyclopedia:SlowedEffect}slowed{/g} for 2 rounds.</indent>\\n-<indent=5%>On a failed Willpower test \342\200\224 {g|Encyclopedia:DisturbedEffect}disturbed{/g} for 2 rounds.</indent>"
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 15
  max_damage: 19
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "0eaf58bc6d7d487e8b78c6a2c31bd2fb"
  extra_fact_name: "Chapter2_Unique_CenserHeadPowerMaul_Feature"
  sources: "Chest - FeudalWorld: UnhideBox_1"
}
weapon {
  guid: "1ef9b17a0f8b4d109dfdae757f0c8ab8"
  blueprint_name: "Chapter2_Unique_EboniteMaul_Item"
  name_shared_key: "9003b67a-c576-475e-9520-ad938bb94053"
  name: "Ebonite Maul"
  description_shared_key: "009951b2-712a-45f9-b6eb-de986dfacd7d"
  description: "Targets {g|Encyclopedia:HitSequenceGlossary}hit{/g} with this sword suffer a number of {g|f:45bce77d4a7d458781177cf9353cd462}static charge{/g} stacks equal to damage dealt by the attack. When a creature with those stacks is killed, all creatures adjacent to it (except the wielder) suffer {g|Encyclopedia:ShockDamage}shock damage{/g} equal to <u>number of {g|f:45bce77d4a7d458781177cf9353cd462}static charge{/g} stacks</u>."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 13
  max_damage: 19
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "1a0cccd12b104548b2b52780ece5b0c5"
  extra_fact_name: "Chapter2_Unique_EboniteMaul_Feature"
  sources: "Unit - ExportedPregens: RT_FORTEASER_1_ExportedPregen"
}
weapon {
  guid: "7ba0567a0f5a4548935a197713eb6d52"
  blueprint_name: "Chapter4_Unique_EmptyPromiseMaul_Item"
  name_shared_key: "65932806-a65c-47ce-ae0a-757fc86d2d33"
  name: "Torturer"
  description_shared_key: "d0d60c33-7db7-4de8-94da-aca6e51ce09d"
  description: "This weapon deals +30% more damage to {g|Encyclopedia:Stun}stunned{/g} targets and +20% more damage to {g|Encyclopedia:StaggeredEffect}staggered{/g} targets."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 23
  max_damage: 37
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "598130b95d5d4ae48ce5f5911a2a7397"
  extra_fact_name: "Chapter4_Unique_EmptyPromiseMaul_Feature"
  sources: "Unit - ExportedPregens: Solomorne_LvL38_Varl1n_v2_ExportedPregen"
  sources: "Unit - ExportedPregens: Solomorne_LvL38_Varl1n_v2_ExportedPregen_OLD"
  sources: "Unit - ExportedPregens: Solomorne_LvL40_Varl1n_v2_ExportedPregen"
  sources: "Unit - ExportedPregens: Solomorne_LvL40_Varl1n_v2_ExportedPregen_OLD"
  sources: "Vendor - PirateChapter4_VendorTable_Base 70PF"
}
weapon {
  guid: "d9209d5fede5429ab606d621e5c100cf"
  blueprint_name: "Chapter4_Unique_OrganDamageMaul_Item"
  name_shared_key: "cf8e1152-ddbf-4e79-9d74-176c2226761a"
  name: "Coffinmaker\'s Sledge"
  description_shared_key: "fc204231-35fe-4776-a8d5-66b09e0fcae4"
  description: "This weapon\'s single-target attacks deal additional {g|Encyclopedia:DirectDamage}direct damage{/g} equal to <u>5% of target\'s {g|Encyclopedia:MaxWounds}maximum wounds{/g}</u> (up to a maximum of 300)."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 25
  max_damage: 40
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - TreasureWorld: Loot_Demoliton_Door_Hidden"
}
weapon {
  guid: "acf8d47444144e40a5cd57cad201468b"
  blueprint_name: "Chapter5_Unique_OverlordMercyMaul_Item"
  name_shared_key: "f0186e65-48f5-4bb9-abdd-197fd3adf67f"
  name: "Tormentor of the Chastened"
  description_shared_key: "9f86364d-52ac-411a-8be6-1b5a2f695a02"
  description: "This weapon deals an additional +1 base damage for each common {g|Encyclopedia:NegativeEffectTypesGlossary}negative effect{/g} and each {g|Encyclopedia:Traumas}trauma{/g} on the target."
  category: Melee
  family: Power
  classification: MaulOrHammer
  heavy: false
  two_handed: false
  min_damage: 30
  max_damage: 45
  penetration: 45
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "HammersMeleeAttack_Ability"
    ability_bp: "a39a31f8f11445cba7e420dce565babc"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "PowerMaul_AoE_Ability"
    ability_bp: "fc9fcd12873c4be9bdcf9659a9b28c27"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: SingleShot
    ability_bp_name: "Hammer_PushAbility"
    ability_bp: "bd5f109c46684a09b07fb13743d2a6d7"
    fx_bp_name: "PowerMaul_AbilityFXSettings"
    fx_bp: "c4ebb100b9e44bb5a82f1403726b0158"
    on_hit_actions: "1b19d696bfb0417a9ba9b93b85474b76"
    on_hit_action_name: "Hammer_PushAbilityAdditionalEffect"
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "981064ae32fb4f19a34a01111268d761"
  extra_fact_name: "Chapter5_Unique_OverlordMercyMaul_Item_Feature"
  sources: "Chest - TechArcGrave_Lair: AdeptusMechanicus_Chests_DLC2"
}

