# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "001c1a9ce35d48249539010b054cc1eb"
  blueprint_name: "HellgunNecron_Item"
  name_shared_key: "b82ee348-9519-433f-a37b-9bb1b47d1ad3"
  name: "Necrontech Hot Shot Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 35
  penetration: 50
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 16
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "NecronGauss_Shot_AbilityFXSettings"
    fx_bp: "aeb1d1f9b1774ab88cb398bf5e58b07f"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "NecronGauss_Shot_AbilityFXSettings"
    fx_bp: "aeb1d1f9b1774ab88cb398bf5e58b07f"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Hellgun_Shot_AbilityFXSettings"
    fx_bp: "c3960cf4b54a4caab4a5ee628ad740e4"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "5de2d70b4ac9468ca723e84c57524eae"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "XenosWeaponProficiencyFeature"
  sources: "Chest - EpitaphEntrance: AdeptusMechanicus_Crate"
}
weapon {
  guid: "94f54f0e70aa4d6c8f0d6cb0ffdd14f9"
  blueprint_name: "HellgunT2CH04_Item"
  name_shared_key: "6092b4ff-ab00-44a7-afe4-82cda703a706"
  name: "Hot Shot Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 8
  max_damage: 10
  penetration: 25
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 16
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Hellgun_Shot_AbilityFXSettings"
    fx_bp: "c3960cf4b54a4caab4a5ee628ad740e4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Hellgun_Shot_AbilityFXSettings"
    fx_bp: "c3960cf4b54a4caab4a5ee628ad740e4"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Hellgun_Shot_AbilityFXSettings"
    fx_bp: "c3960cf4b54a4caab4a5ee628ad740e4"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact_name: "LaserCoverReduce_Feature"
  sources: "Chest - VigilCastle: ImperiumMilitary_VC_AfterBattle"
  sources: "Unit - Ch05_Epitaph: InquisitorGuard"
}
weapon {
  guid: "aacdd9b948cf4ae2b7b17617837ff6be"
  blueprint_name: "Hellgun_Item"
  name_shared_key: "6092b4ff-ab00-44a7-afe4-82cda703a706"
  name: "Hot Shot Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 9
  max_damage: 11
  penetration: 40
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 16
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Hellgun_Shot_AbilityFXSettings"
    fx_bp: "c3960cf4b54a4caab4a5ee628ad740e4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Hellgun_Shot_AbilityFXSettings"
    fx_bp: "c3960cf4b54a4caab4a5ee628ad740e4"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Hellgun_Shot_AbilityFXSettings"
    fx_bp: "c3960cf4b54a4caab4a5ee628ad740e4"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact_name: "LaserCoverReduce_Feature"
  sources: "Chest - CR22: AdeptusMechanicus_OutdorWeaponCrate"
  sources: "Unit - Ch02_Lair3: Lair3RebelLeader"
  sources: "Unit - Ch03_Prison: Comissar"
  sources: "Unit - Ch04: Footfall_InquisitorEnforcer"
  sources: "Unit - Ch04: Footfall_InquisitorEnforcer_DoorGuard"
  sources: "Unit - JaeCompanion: JaeCompanion_Gamescom"
}
weapon {
  guid: "130e8a68f5ca4bda9049f035e3baaa58"
  blueprint_name: "LasgunScrappy_Item"
  name_key: "91a99b08-df10-4c14-be9d-fc0a10d9b6a5"
  name: "Scrappy Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 6
  penetration: 5
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 20
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - CR15: AdeptusMechanicus_BSW_Lasgun2_level"
  sources: "Unit - Ch01_Starport: StarportRebelRangeNoMoveSwarm"
  sources: "Unit - Ch01_Starport: StarportRebelRangeSwarm"
}
weapon {
  guid: "7c87f37bc5b1470dad58941f6777452c"
  blueprint_name: "LasgunT1CH02_Item"
  name_shared_key: "25925e25-66f4-4c7a-ae37-0c99ae0914f7"
  name: "Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 6
  max_damage: 8
  penetration: 0
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 20
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact_name: "LaserCoverReduce_Feature"
  sources: "Unit - Ch02_VoidshipOfficersDeck: GenestealerRanger_Ranged_PatriarchVisions_Swarm"
  sources: "Unit - Ch01_ArcheotechReactor: Cultist_ArcheotechReactor_Range"
  sources: "Unit - Ch01_JailPlanetoid: JailPlanetoidEnforcerPistol"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobiliteLasgun_Guard"
  sources: "Unit - Ch02_DestroyedBlackShip: PossessedTechnomat"
  sources: "Unit - Ch02_FootFallAtrium: FootfallPirate"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverBodyguard_Ranged_Hard"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverBodyguard_Ranged_Swarm"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditRingleader"
  sources: "Unit - DLC2_FeudalWorld: FW_CorruptedNoble_Ranged_Swarm"
  sources: "Unit - Ch04: Footfall_ChordaGuard"
}
weapon {
  guid: "f25abdb26bff4108ac5aee678034fd0d"
  blueprint_name: "LasgunT1Tutorial_Item"
  name_key: "a6e0287f-96fc-4078-9738-25492ee79577"
  name: "Well-Maintained Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 6
  max_damage: 8
  penetration: 5
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 15
  max_range: 20
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - VoidshipOfficersDeck: ImperiumMilitary_PrologueOD_CorridorChestSolder"
}
weapon {
  guid: "cb95bd7280854a2bbe358a872aadd6ee"
  blueprint_name: "LasgunT2CH2_Item"
  name_shared_key: "25925e25-66f4-4c7a-ae37-0c99ae0914f7"
  name: "Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 14
  penetration: 10
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 20
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - Ch02_VoidshipOfficersDeck: GenestealerRanger_Ranged_PatriarchVisions_Common"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedTechnomat_Ranged"
  sources: "Unit - Ch02_VoidshipTemple: TheAlly_MeleeRanged_VoidshipTempleAmbush"
  sources: "Unit - Ch03_Prison: ImperialSoldierFemale_Ranged_Prison"
}
weapon {
  guid: "015e4b1b239c41259fc6ee30817cea69"
  blueprint_name: "LasgunT2CH4_Item"
  name_key: "511b6d05-0cf6-4f19-82d6-4c4544f9ab16"
  name: "[Mezoa-Pattern] Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 14
  max_damage: 21
  penetration: 20
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 20
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - SalisPrime_ItsTime: Loot_Poor_LongLas"
  sources: "Unit - Ch02_VoidshipOfficersDeck: GenestealerRanger_Ranged_PatriarchVisions_Hard"
  sources: "Unit - Ch04_CrownWorld: NaviTraditionalistBodyguard"
  sources: "Unit - Ch04_CrownWorld: NaviTraditionalistBodyguardFemale"
  sources: "Unit - Ch04_SalisPrine_ItsTime: ItsTime_CultistsSwarm"
  sources: "Unit - Ch04_VoidshipBridgeBoarding: InquisitorMarksman_Ranged_Boarding"
  sources: "Unit - DLC1_LowerTunnels: InfernusCH04LTState1_Ranged_Swarm"
  sources: "Unit - Ch04_Canteena: Ch04Vladaym_RangeGuard_unit"
}
weapon {
  guid: "997b51ad463942f78763dd2aab2b73b0"
  blueprint_name: "LasgunTrophy_Item"
  name_key: "1314c246-c0ae-442d-ab93-00f90c183356"
  name: "Trophy Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 14
  penetration: 20
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 20
  ammo: 30
  rate_of_fire: 3
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - Ch03_Prison: ArenaRanger_Ranged_Prison"
  sources: "Unit - Ch03_Prison: ImperialMedic_Ranged_Prison"
  sources: "Unit - Ch03_Prison: SergeantVigastis"
  sources: "Unit - DLC2_Ch04_TreasureWorld: TreasureWorld_FeralGuard_Ranged"
  sources: "Unit - DLC2_Ch04_TreasureWorld: TreasureWorld_FeralGuard_Ranged_NoExp"
  sources: "Unit - DLC2_Ch04_TreasureWorld: TreasureWorld_FeralGuard_Ranged_Weak"
}
weapon {
  guid: "d40596aa846a4b5d926814ccb64939b9"
  blueprint_name: "Lasgun_Item"
  name_shared_key: "25925e25-66f4-4c7a-ae37-0c99ae0914f7"
  name: "Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 5
  max_damage: 7
  penetration: 5
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 20
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - CR0: ImperiumMilitary_PrologueAP_Patent_Chest02"
  sources: "Chest - CR0: ImperiumMilitary_PrologueAP_Patent_Chest04"
  sources: "Chest - CR15: AdeptusMechanicus_LootChes_LasgunSpecial"
  sources: "Chest - CR33: ImperiumMilitary_PrisonPitTrashWeapon"
  sources: "Chest - DrukhariAttackOnShip: DrukhariAttack_WeaponLootLasgun"
  sources: "Chest - EE_DestroyedBlackShip: Loot_Poor - BlackShipArmoury"
  sources: "Chest - EE_DestroyedBlackShip: Loot_Poor_Locked - Weapon"
  sources: "Chest - EE_DestroyedBlackShip: Loot_Trash_CorpseFrozenV1"
  sources: "Chest - JailPlanetoid: Loot_Poor_Locked  - Arsenal"
  sources: "Chest - LastStand_Lair1: Loot_Poor_AmmoBox - 100"
  sources: "Chest - LastStand_Lair1: Loot_Poor_AmmoBox_Loot (1) - 100#1"
  sources: "Chest - LastStand_Lair1: Loot_Poor_AmmoBox_Loot (1) - 100"
  sources: "Chest - LowerTunnels: Military_Loot_Good"
  sources: "Chest - SantielsPride_Surface: FathersDataslate"
  sources: "Chest - VoidshipCrypt: Loot_SecretRoom_N1_Arsenal"
  sources: "Chest - CR26: Forest_Trash1"
  sources: "Unit - Ch01_ArcheotechReactor: Guard_Male"
  sources: "Unit - Ch01_ArcheotechReactor: Guard_Serjant_Male"
  sources: "Unit - Ch01_JailPlanetoid: JailPlanetoidArturGuardM"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobiliteLasgun_GuardFemale"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Commander_CassiaRoom"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Grenadir"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Guard"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Ranged_LasgunGuard"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Ranged_LasgunGuardFemale"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Rifler"
  sources: "Unit - Ch01_Starport: StarportRebelAgitator"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsTriumphGuardF"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsTriumphGuardM"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldRebel"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldRebelWeakGrenede"
  sources: "Unit - Ch02_AgriWorldTown: GovernorGuardPeaceful"
  sources: "Unit - Ch02_AgriWorldTown: GovernorGuardPeacefulFemale"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditBodyguard"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditHitman"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditRingleaderPalace"
  sources: "Unit - Ch02_FootfallDock: Footfall_BadTrader"
  sources: "Unit - Ch02_FootfallDock: Footfall_ColdTrader"
  sources: "Unit - Ch02_FootfallDock: Footfall_JaeCanteenaSceneBandit2"
  sources: "Unit - Ch02_FootfallDock: Footfall_ShipCrew"
  sources: "Unit - Ch02_FootfallDock: JaeGuard"
  sources: "Unit - Ch02_FootfallDock: JaeGuard_Kor"
  sources: "Unit - Ch02_FootfallDock: JaeGuard_Torra"
  sources: "Unit - Ch02_FootFallSlums: FootfallAnverDoubleTap_Ranged_Hard"
  sources: "Unit - Ch02_FootFallSlums: Footfall_Generic_BanditHitman"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CultistRange"
  sources: "Unit - Ch02_ForgeWorldAndHeart: HeretekMagiUralonSidekick"
  sources: "Unit - Ch02_ForgeWorldSpaceHulk: MadTechPriest_Final"
  sources: "Unit - Ch02_Lair4_TheLure: Lair4GenestealerCultSoldier"
  sources: "Unit - Ch02_Lair4_TheLure: Lair4OurCrewCutSc"
  sources: "Unit - Ch02_LowerDecks: SpecialGuard"
  sources: "Unit - Ch02_RandomEncounters: CultistTzeentchRangeRandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: PossessedGuardLasgunRandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: VoidshipGuardRandomEncounter"
  sources: "Unit - Ch02_RogueTraderPalace: NobleInPalaceWRifle"
  sources: "Unit - Ch02_RogueTraderPalace: RogueTraderGuardPeaceful"
  sources: "Unit - Ch02_RogueTraderPalace: RTPalaceGuardPeaceful_Female"
  sources: "Unit - Ch02_RogueTraderPalace: RTPalaceGuardPeaceful_FemaleCutsceneNeutral"
  sources: "Unit - Ch02_RogueTraderPalace: RTPalaceGuardPeaceful_Male"
  sources: "Unit - Ch02_RogueTraderPalace: RTPalaceGuardPeaceful_MaleCutsceneNeutral"
  sources: "Unit - Ch02_SantielsPrideUnderhive: SurvivorGuard"
  sources: "Unit - Ch02_VoidshipBridge: BridgeCrewMemberGuard_Lasgun"
  sources: "Unit - Ch02_VoidshipBridge: RE_BridgeUnique_Guard"
  sources: "Unit - Ch02_VoidshipBridge: RogueTraderShipSoldier"
  sources: "Unit - Ch03_Prison: ImperialSoldier_Ranged_Prison"
  sources: "Unit - Ch04_FootfallSewersCh04: JaeGuy4"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_Guard1"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_Guard2"
  sources: "Unit - DLC2_BoardedShip_Bridge: BoardedShip_Bridge_Range_Ally_Swarm"
  sources: "Unit - DLC2_BoardedShip_Bridge: BoardedShip_Bridge_Range_Swarm"
  sources: "Unit - Ch02_ForgeWorldSpaceHulk: ShipServicemanMutantGuard"
  sources: "Unit - Ch02_Macrocannon_Psyker_Q1: MacrocannonMutantPsyker"
  sources: "Unit - Ch02_RandomEncounters: MutantPsyker02RandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: RE_DemonTransform_Gunner"
  sources: "Unit - Ch02_RandomEncounters: RE_PossessedOfficer_Gunner"
  sources: "Unit - Ch02_AgriWorldTown: RemainingRebel"
  sources: "Unit - CH02_DrukhariAttackOnShip: CrewHumanTraitor"
  sources: "Unit - Ch02_ForgeWorldAndHeart: FabricatorsLeutenant2"
  sources: "Unit - Ch02_ForgeWorldAndHeart: FabricatorsLeutenantTechPriest"
  sources: "Unit - Ch02_ForgeWorldSpaceHulk: TechpriestRanged_TrailerCinematic"
  sources: "Unit - Ch02_LowerDecks: SpecialGuard"
  sources: "Unit - Ch02_SantielsPride_Surface: Scout"
  sources: "Unit - Ch02_SantielsPride_Surface: Scout2"
  sources: "Unit - OurShipCrew: OurCrewPilot"
  sources: "Unit - OurShipCrew: OurShipCrew"
}
weapon {
  guid: "ad57f94e09524be28ac484ac1213f217"
  blueprint_name: "ModifiedLasgun_Item"
  name_key: "5929dda3-6dab-4e90-98e0-125f9bdda57c"
  name: "Modified Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 5
  max_damage: 12
  penetration: 10
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 20
  max_range: 20
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Vendor - ExploratorChapter1_VendorTable_Base 16PF"
}
weapon {
  guid: "6c14b094a1484d87860e701941f644f2"
  blueprint_name: "SunfireGun_Item"
  category: Basic
  family: Laser
  heavy: false
  two_handed: false
  min_damage: 6
  max_damage: 8
  penetration: 20
  dodge_reduction: 20
  additional_hit_chance: 0
  recoil: 10
  max_range: 20
  ammo: 60
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SunfireGun_Shot_AbilityFXSettings"
    fx_bp: "8e18de10b06544cbb858241fc6b14435"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "SunfireGun_Shot_AbilityFXSettings"
    fx_bp: "8e18de10b06544cbb858241fc6b14435"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SunfireGun_Shot_AbilityFXSettings"
    fx_bp: "8e18de10b06544cbb858241fc6b14435"
    on_hit_action_name: ""
    ap: 3
  }
}
weapon {
  guid: "90e9298313da45f282588ca233afa65e"
  blueprint_name: "AntiqueLasgun_Item"
  name_key: "2515960e-53d6-4d66-8688-f64d801d1dd8"
  name: "Archeotech Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 12
  max_damage: 17
  penetration: 5
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 20
  max_range: 18
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
}
weapon {
  guid: "be4e56de5bf341db9927c01207134a1b"
  blueprint_name: "Assault_Lasgun_Item"
  name_shared_key: "ed975816-1b5e-4d5f-b579-4bab5cebb203"
  name: "Assault Lasgun"
  description_key: "7f6f279c-722c-4d55-b931-521757eb76f5"
  description: "Every {g|Encyclopedia:HitSequenceGlossary}hit{/g} reduces {g|Encyclopedia:Deflection}deflection{/g} by \342\210\2221. Stacks up to 3 times."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 15
  penetration: 10
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 20
  ammo: 40
  rate_of_fire: 5
  ability1 {
    type: SingleShot
    ability_bp_name: "AssaultLasgun_SingleShot_Ability"
    ability_bp: "fc9b96b6283f42968554d6be959394f6"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "AssaultLasgun_BurstFire_Ability"
    ability_bp: "2688289278f34ca99746239ebd1ed235"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - ExportedPregens: Sayonara_23_Argenta_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_39lvl_Argenta_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_Argenta_23lvl_ExportedPregen"
}
weapon {
  guid: "e0a0a605a35d4a69b40f27ecbd7b886b"
  blueprint_name: "HellgunHope_Item"
  name_key: "6846e042-9adc-4e8e-801a-92e5c4839d47"
  name: "Sworn Protector"
  description_key: "b24d1514-3f43-40a7-a891-4ae687a85d04"
  description: "Requires {g|Encyclopedia:SoulMarkHope}Iconoclast{/g} \342\200\224 Adherent.\\nGrants the wielder +1 to {g|Encyclopedia:Resolve}resolve{/g} for each enemy killed until the end of combat."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 13
  penetration: 30
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 16
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Hellgun_Shot_AbilityFXSettings"
    fx_bp: "c3960cf4b54a4caab4a5ee628ad740e4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Hellgun_Shot_AbilityFXSettings"
    fx_bp: "c3960cf4b54a4caab4a5ee628ad740e4"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Hellgun_Shot_AbilityFXSettings"
    fx_bp: "c3960cf4b54a4caab4a5ee628ad740e4"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "0aa5d74b00c74c4fa751a9060f057ee7"
    bp_name: "HopeSoulMark_2"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "73c23bb8b61c4557bb9250e3692884be"
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact_name: "HellgunHope_Feature"
  extra_fact_name: "LaserCoverReduce_Feature"
  sources: "Chest - CR26: Forest_Good1"
}
weapon {
  guid: "3b76f2679fe040d89ed07b1d1e97787b"
  blueprint_name: "HighVoltage_Lasgun_Item"
  name_shared_key: "f4364880-6e7f-402f-afde-e94030d451ac"
  name: "Implacable Tempest"
  description_shared_key: "c78f7a20-5b8b-441f-b692-632cac85e294"
  description: "This lasgun deals an additional +{uip|Damage|71d06b927ac34b68810cdfcac273c221} {g|Encyclopedia:DamageGlossary}damage{/g} to enemies with more than 60% {g|Encyclopedia:WarhammerArmourGlossary}armour{/g}."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 15
  max_damage: 24
  penetration: 15
  dodge_reduction: 30
  additional_hit_chance: 0
  recoil: 10
  max_range: 20
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "71d06b927ac34b68810cdfcac273c221"
  extra_fact_name: "HighVoltage_Lasgun_Feature"
  sources: "Unit - ExportedPregens: PlayerRT_level47_Gamescom2024_ExportedPregen"
  sources: "Vendor - LiegeChapter4_VendorTable_Base 110PF"
}
weapon {
  guid: "ba7fa6b44b8642bab33ba029ad24e950"
  blueprint_name: "PreciseLasgun_Item"
  name_key: "ac017223-8f4a-4829-b89e-282b2f0ac695"
  name: "Precise Lasgun"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 11
  max_damage: 12
  penetration: 10
  dodge_reduction: 30
  additional_hit_chance: 10
  recoil: 10
  max_range: 20
  ammo: 40
  rate_of_fire: 4
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_WinterscaleVoxMaster"
  sources: "Vendor - ExploratorChapter2_VendorTable_Base 35PF"
}

