# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "c9d56611363b4a13a6012b500c7afa33"
  blueprint_name: "CorruptedInfernoPistol_Item"
  name_key: "40a7ffac-de89-45bd-807a-3d0cfc33f1bc"
  name: "Corrupted Inferno Pistol"
  description_key: "9d751c7c-0496-44bd-b4b3-48bf4da8fae2"
  description: "This pistol increases the wielder\'s {g|Encyclopedia:SkillCoercion}Coercion{/g} by +10 and does not require weapon proficiency to be wielded."
  category: Pistol
  family: Melta
  heavy: false
  two_handed: false
  min_damage: 10
  max_damage: 16
  penetration: 50
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 8
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_PistolAbility"
    ability_bp: "6a7f0c4523c34de7829c088556b62f11"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "InfernoPistolAoEAbility"
    ability_bp: "34dcb0024d5a4ed9877e3b6fd5760dca"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 1
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: true
    negate: false
    bp: "fb7efcba2dcc427da2324d4066daf2d5"
    bp_name: "CorruptionSoulMark_1"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "ed9e883966ed4e20ada226d32100a6cc"
  extra_fact_name: "Coercion10_Feature"
  sources: "Chest - CR0: PrologueAP_GoodLoot02_corruption"
  sources: "Unit - ExportedPregens: Yanus19RT_ExportedPregen"
}
weapon {
  guid: "ac81e67ac2874517b406c8008559a5a9"
  blueprint_name: "FusionGunT1_Item"
  name_shared_key: "7539b67a-3b56-4128-925c-e639bfc3c442"
  description_shared_key: "7d4104fa-75c1-411e-8eae-0c72b100f855"
  category: Basic
  family: Melta
  heavy: false
  two_handed: true
  min_damage: 20
  max_damage: 30
  penetration: 40
  dodge_reduction: 20
  additional_hit_chance: 0
  recoil: 0
  max_range: 16
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "FusionGun_AbilityFXSettings"
    fx_bp: "f54cb2903bed4b5d8ffa74f8d5016f9b"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "FusionGun_AbilityFXSettings"
    fx_bp: "f54cb2903bed4b5d8ffa74f8d5016f9b"
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
}
weapon {
  guid: "a6ad7d7ecf2c4f8ebac00998f9aa5946"
  blueprint_name: "FusionGun_Item"
  name_key: "943b9da8-5ee2-4210-9402-089dc44c8caf"
  name: "Fusion Gun"
  description_shared_key: "7d4104fa-75c1-411e-8eae-0c72b100f855"
  category: Basic
  family: Melta
  heavy: false
  two_handed: true
  min_damage: 16
  max_damage: 26
  penetration: 60
  dodge_reduction: 20
  additional_hit_chance: 0
  recoil: 0
  max_range: 16
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "FusionGun_AbilityFXSettings"
    fx_bp: "f54cb2903bed4b5d8ffa74f8d5016f9b"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "FusionGun_AbilityFXSettings"
    fx_bp: "f54cb2903bed4b5d8ffa74f8d5016f9b"
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  sources: "Vendor - LiegeChapter2_VendorTable_Base 38PF"
}
weapon {
  guid: "e5d24d0226c04e98abe895ad32b1be76"
  blueprint_name: "InfernoPistolCH05Unique_Item"
  name_key: "270d79fd-0733-416f-a5d3-84f18589a3a7"
  name: "Virtuous Vindication"
  description_key: "8185d855-0e48-4ea8-ad97-11ac83a756fe"
  description: "On {g|Encyclopedia:HitSequenceGlossary}hit{/g}, targets must perform a {g|Encyclopedia:WarhammerToughness}Toughness{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} with a +10 {g|Encyclopedia:Bonus}bonus{/g}.\\nIf they fail, they suffer {g|Encyclopedia:BurningEffect}burning{/g} (24) and {g|Encyclopedia:MeltingEffect}melting{/g}. Additionally, they are {g|Encyclopedia:Stun}stunned{/g} for 1 {g|Encyclopedia:Turn}turn{/g}.\\nIf they pass, they suffer burning (8) and melting."
  category: Pistol
  family: Melta
  heavy: false
  two_handed: false
  min_damage: 35
  max_damage: 50
  penetration: 80
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 8
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_PistolAbility"
    ability_bp: "6a7f0c4523c34de7829c088556b62f11"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "InfernoPistolAoEAbility"
    ability_bp: "34dcb0024d5a4ed9877e3b6fd5760dca"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 1
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: true
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "ed9e883966ed4e20ada226d32100a6cc"
  extra_fact: "fa3b851a46ab4e3aa056e621e1d05b97"
  extra_fact_name: "Coercion10_Feature"
  extra_fact_name: "InfernoPistolCH05Unique_Feature"
  sources: "Chest - CR0: ImperiumMilitary_GoodLoot_Bag"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch05_Finale"
}
weapon {
  guid: "7db1e12a9ddd4eaf8c0ca0e5642f27cd"
  blueprint_name: "InfernoPistolT2CH04_Item"
  name_key: "327b076a-cc02-4ba9-80e7-643c5431f773"
  name: "[Mezoa-Pattern] Inferno Pistol"
  description_shared_key: "7d4104fa-75c1-411e-8eae-0c72b100f855"
  category: Pistol
  family: Melta
  heavy: false
  two_handed: false
  min_damage: 30
  max_damage: 40
  penetration: 60
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 9
  ammo: 6
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_PistolAbility"
    ability_bp: "6a7f0c4523c34de7829c088556b62f11"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "InfernoPistolAoEAbility"
    ability_bp: "34dcb0024d5a4ed9877e3b6fd5760dca"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 1
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - Ch04_Canteena: Chorda_JudgementOfFootfall"
  sources: "Unit - Ch05_Epitaph: Ch05Inquisitor_Leader_unit"
  sources: "Unit - ExportedPregens: PlayerMercenary_Level42_OlegParty_ExportedPregen"
  sources: "Unit - FinalCompanions: Chorda_Companion"
  sources: "Unit - FinalCompanions: Hope_Chorda_Companion"
}
weapon {
  guid: "bf521dfa014e473b800ef28bdc8e6ae9"
  blueprint_name: "InfernoPistol_Item"
  name_key: "d4ebd98c-cc74-4d23-a51f-16546559d1e8"
  name: "Inferno Pistol"
  description_shared_key: "7d4104fa-75c1-411e-8eae-0c72b100f855"
  category: Pistol
  family: Melta
  heavy: false
  two_handed: false
  min_damage: 10
  max_damage: 17
  penetration: 50
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 8
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_PistolAbility"
    ability_bp: "6a7f0c4523c34de7829c088556b62f11"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "InfernoPistolAoEAbility"
    ability_bp: "34dcb0024d5a4ed9877e3b6fd5760dca"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 1
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - EE_DestroyedBlackShip: Loot_Uniq_Locked  - InquisitionArsenal"
  sources: "Unit - Ch02_AgriWorldTown: MutantAristocrate"
  sources: "Unit - Ch02_ForgeWorldAndHeart: HeinrixCompanionCopy"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level29_ExportedPregen"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion"
  sources: "Unit - HeinrixCompanion: HeinrixCompanionNPC"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch02_TrueMid"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch02_TrueStart"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch03_TrueStart"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Gamescom"
}
weapon {
  guid: "07a10a4940d540f09a36878ad011431d"
  blueprint_name: "MeltaT2CH3_Item"
  name_key: "d9662f91-e011-4f8c-b93b-b788116e7f50"
  name: "[Ryza-Pattern] Meltagun"
  description_shared_key: "d4a48032-4132-4099-8b5d-d9e594444c50"
  category: Basic
  family: Melta
  heavy: false
  two_handed: true
  min_damage: 25
  max_damage: 32
  penetration: 75
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 4
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Melta_SingleShot_AbilityFXSettings"
    fx_bp: "290fe4c47736467492f5f2b1d06ca2f9"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: AOE
    ability_bp_name: "Melta_AoEAbility"
    ability_bp: "5aea484f7db34742be65dd7e0fab5505"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  sources: "Chest - CR33: ImperiumMilitary_ComisarChest"
  sources: "Unit - ArgentaCompanion: ArgentaCompanion_Ch04_TrueStart"
}
weapon {
  guid: "3fa8b12d58f44652badec627a7a3de67"
  blueprint_name: "MeltaT2CH4_Item"
  name_key: "b5406b2c-e8e1-49d1-ad88-7523776e442a"
  name: "[Mars-Pattern] Meltagun"
  description_shared_key: "d4a48032-4132-4099-8b5d-d9e594444c50"
  category: Basic
  family: Melta
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 46
  penetration: 85
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 4
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Melta_SingleShot_AbilityFXSettings"
    fx_bp: "290fe4c47736467492f5f2b1d06ca2f9"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: AOE
    ability_bp_name: "Melta_AoEAbility"
    ability_bp: "5aea484f7db34742be65dd7e0fab5505"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 156PF"
}
weapon {
  guid: "b68f8b7e89f44ea0b255408e694c6c63"
  blueprint_name: "MeltaT2CH4_variation2_Item"
  name_key: "ea217491-93be-45ba-8cda-bb017a3be117"
  name: "[Sol-Pattern] Meltagun"
  description_shared_key: "d4a48032-4132-4099-8b5d-d9e594444c50"
  category: Basic
  family: Melta
  heavy: false
  two_handed: true
  min_damage: 25
  max_damage: 46
  penetration: 85
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 4
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Melta_SingleShot_AbilityFXSettings"
    fx_bp: "290fe4c47736467492f5f2b1d06ca2f9"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: AOE
    ability_bp_name: "Melta_AoEAbility"
    ability_bp: "5aea484f7db34742be65dd7e0fab5505"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Vendor - DrusianChapter4_VendorTable_Base 85PF"
}
weapon {
  guid: "15fff32aea5d499b92d037144f8eaef8"
  blueprint_name: "MeltaUltima_Item"
  name_key: "64614539-b1cd-47e0-a4fe-bb2f11958d74"
  name: "Melta Ultima"
  description_key: "adf0c0bd-99a2-4ad1-b8c3-1d5b98cc51d5"
  description: "This melta weapon modified by the Adeptus Mechanicus has increased firepower and range."
  category: Basic
  family: Melta
  heavy: false
  two_handed: false
  min_damage: 20
  max_damage: 26
  penetration: 75
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Melta_SingleShot_AbilityFXSettings"
    fx_bp: "290fe4c47736467492f5f2b1d06ca2f9"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Reload
    ability_bp_name: "Melta_AoEAbility"
    ability_bp: "5aea484f7db34742be65dd7e0fab5505"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - ForgeWorld: AdeptusMechanicus_MeltaUltima_Item_Loot"
  sources: "Unit - ExportedPregens: Abelard35Yremeris_ExportedPregen"
  sources: "Unit - ExportedPregens: Abelard_level47_Gamescom2024_ExportedPregen"
  sources: "Unit - ExportedPregens: abelard_lv38_chordafight_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_Heinrix_23lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: Uralon41Abel_ExportedPregen"
}
weapon {
  guid: "e3c064c362884cd699844699b478ac69"
  blueprint_name: "Melta_Item"
  name_key: "2e8d85bb-2433-45fa-ad7a-c8ac7f78c029"
  name: "Meltagun"
  description_shared_key: "d4a48032-4132-4099-8b5d-d9e594444c50"
  category: Basic
  family: Melta
  heavy: false
  two_handed: true
  min_damage: 18
  max_damage: 24
  penetration: 50
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 4
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Melta_SingleShot_AbilityFXSettings"
    fx_bp: "290fe4c47736467492f5f2b1d06ca2f9"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: AOE
    ability_bp_name: "Melta_AoEAbility"
    ability_bp: "5aea484f7db34742be65dd7e0fab5505"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldRebelElite"
  sources: "Unit - Companions: CompanionAbelardPrototype"
  sources: "Unit - AbelardCompanion: AbelardCompanion"
  sources: "Unit - AbelardCompanion: AbelardCompanion_SoundTest"
  sources: "Unit - ExportedPregens: 4y6_Argenta_27lvl_ExportedPregen_ExportedPregen"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level19_HarmonParty_ExportedPregen"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level22_NeiliusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level27_CyrusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: Gusev_Abelard_26lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: zin_22_AbelardCompanion_ExportedPregen"
  sources: "Unit - PascalCompanion: PascalCompanion_TrailerCinematic"
}
weapon {
  guid: "bf78cfe92a754f7298c9acf88c4a1935"
  blueprint_name: "MultiMelta_LongRangeCutsene"
  category: Heavy
  family: Melta
  heavy: true
  two_handed: true
  min_damage: 21
  max_damage: 28
  penetration: 60
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 100
  ammo: 999
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "MultiMelta_AoEAbility"
    ability_bp: "ae2ca6f5827949d89c87c62ed21ec2e2"
    fx_bp_name: "MultiMelta00_shot_AbilityFXSettings"
    fx_bp: "b8ab5cbae1a9467aaf82676d9c9ff31f"
    on_hit_action_name: ""
    ap: 0
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: true
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  sources: "Unit - Ch02_ForgeWorldAndHeart: FriendlySpacewolfMarine_Melta"
}
weapon {
  guid: "51cef9a165014130a5b3293ecc9e0ed0"
  blueprint_name: "EruptionMultiMelta_Item"
  name_shared_key: "5a52c1a0-bd09-40e5-b713-975db0a84024"
  name: "Eruption"
  description_shared_key: "1afa86e1-b365-401f-8461-d04f3b7f4b03"
  description: "All targets {g|Encyclopedia:HitSequenceGlossary}hit{/g} by this weapon\'s {g|Encyclopedia:AreaOfEffect}area attack{/g} deal 25 {g|Encyclopedia:EnergyDamage}energy damage{/g} to everyone in a 2-cell radius."
  category: Heavy
  family: Melta
  heavy: true
  two_handed: true
  min_damage: 45
  max_damage: 60
  penetration: 90
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 8
  ammo: 1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_EruptionMultiMelta_Ability"
    ability_bp: "d84c583aad004f9588260dbd0f7fbd41"
    fx_bp_name: "MultiMelta00_shot_AbilityFXSettings"
    fx_bp: "b8ab5cbae1a9467aaf82676d9c9ff31f"
    on_hit_action_name: ""
    ap: 3
  }
  ability2 {
    type: AOE
    ability_bp_name: "EruptionMultiMelta_AoEAbility"
    ability_bp: "0e58a2648e214bb68e7a578f1529b837"
    fx_bp_name: "MultiMelta00_shot_AbilityFXSettings"
    fx_bp: "b8ab5cbae1a9467aaf82676d9c9ff31f"
    on_hit_action_name: ""
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: true
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
}
weapon {
  guid: "768d7be5dfa9454fa3d0493b869c7093"
  blueprint_name: "FocusMelta_Item"
  name_key: "8a6e22af-9781-4f29-9025-6cd1590785da"
  name: "Focus Meltagun"
  category: Basic
  family: Melta
  heavy: false
  two_handed: true
  min_damage: 25
  max_damage: 32
  penetration: 70
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 4
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Melta_SingleShot_AbilityFXSettings"
    fx_bp: "290fe4c47736467492f5f2b1d06ca2f9"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: AOE
    ability_bp_name: "FocusMelta_AoEAbility"
    ability_bp: "89e4b492d38248fa8aaf79ca9d585e5c"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Unit - ExportedPregens: ArgentaCompanion_Lvl40_Bakula_ExportedPregen"
  sources: "Unit - ExportedPregens: Pascal35Yremeris_ExportedPregen"
  sources: "Unit - ExportedPregens: Uralon41Pascal_ExportedPregen"
  sources: "Vendor - ExploratorChapter2_VendorTable_Base 60PF"
}
weapon {
  guid: "c23be4f018454e8985b227a7992ed68d"
  blueprint_name: "FusionGunCH4Unique_Item"
  name_key: "9117e94c-0fff-4a0a-867e-72af5d4e506d"
  name: "Archeotech Fusion Gun"
  description_key: "326a6e3f-528f-4bd3-9cd6-570608cf1830"
  description: "Deals an additional +60% {g|Encyclopedia:DamageGlossary}damage{/g} to {g|Encyclopedia:BurningEffect}burning{/g} enemies."
  category: Basic
  family: Melta
  heavy: false
  two_handed: true
  min_damage: 25
  max_damage: 38
  penetration: 80
  dodge_reduction: 20
  additional_hit_chance: 0
  recoil: 0
  max_range: 16
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "FusionGun_AbilityFXSettings"
    fx_bp: "f54cb2903bed4b5d8ffa74f8d5016f9b"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "8760eadc769145baa0c00a14d8484a34"
  extra_fact_name: "FusionGunCH4Unique_Feature"
}
weapon {
  guid: "6082f1eef046489ab4f3b34cf0f0cf1b"
  blueprint_name: "MeltaCH4Unique_Item"
  name_shared_key: "9c08779f-231b-421c-b6a1-f9ee03d6efd3"
  name: "Cinder"
  description_shared_key: "fd92b76a-20a1-4245-ae50-81f1d49ccadf"
  description: "Single target attack only. Ignores 7 {g|Encyclopedia:Deflection}deflection{/g}."
  category: Basic
  family: Melta
  heavy: false
  two_handed: true
  min_damage: 40
  max_damage: 60
  penetration: 80
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 5
  ammo: 4
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "Melta_UniqueSingleAbility"
    ability_bp: "caa2f3c3dfc64485a8930aea881c3c16"
    fx_bp_name: "Melta_Shot_AbilityFXSettings"
    fx_bp: "9efe7a95d738459ea52734715c1439e5"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "9e546f9cdd5147ea84822e275d1ed06d"
  extra_fact_name: "MeltaCH4Unique_Feature"
  sources: "Unit - ExportedPregens: AbelardCompanion_lvl38_treasureworld_ExportedPregen"
}
weapon {
  guid: "3ef5c9b1be5c44ef900d06f78ef1c641"
  blueprint_name: "MultiMelta_Item"
  name_key: "67be997d-155a-4a73-ad9a-0b7da3238467"
  name: "Multi-Melta"
  category: Heavy
  family: Melta
  heavy: true
  two_handed: true
  min_damage: 21
  max_damage: 28
  penetration: 60
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 8
  ammo: 4
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "MultiMelta00_SingleShot_AbilityFXSettings"
    fx_bp: "9fce4d1e156f42b7b962157080bc595a"
    on_hit_action_name: ""
    ap: 3
  }
  ability2 {
    type: AOE
    ability_bp_name: "MultiMelta_AoEAbility"
    ability_bp: "ae2ca6f5827949d89c87c62ed21ec2e2"
    fx_bp_name: "MultiMelta00_shot_AbilityFXSettings"
    fx_bp: "b8ab5cbae1a9467aaf82676d9c9ff31f"
    on_hit_action_name: ""
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 55
  }
  fact_requirement {
    all: true
    negate: false
    bp: "2818d76d82b341adb2b792ed52f4c203"
    bp_name: "MeltaProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: true
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - CR28: AdeptusMechanicus_LootSafe_HardLocked"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_Techpriest"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_TechpriestVillage"
  sources: "Unit - SpaceMarineFight: Spacemarine_melta"
  sources: "Unit - ExportedPregens: ArgentaCompanion_level27_VasyaParty_ExportedPregen"
}

