# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "3ca6a5ac041843e387be01edff1ea1be"
  blueprint_name: "AstartesPowerSword_Item"
  name_key: "564f5fd4-38f4-4f0c-82e9-b25af24f8f5f"
  name: "Astartes Power Sword"
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 33
  max_damage: 49
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "Parry10_Feature"
  sources: "Chest - CR0: ImperiumMilitary_GoodLoot_Bag"
}
weapon {
  guid: "50630c218e7744cd9233e3fa58b04b82"
  blueprint_name: "DrukhariPowerSword_Item"
  name_shared_key: "d8f85547-9b13-4cd0-9142-d25dac9956b8"
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: true
  min_damage: 16
  max_damage: 20
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 10
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "Venom_MeleeAttack_ability"
    ability_bp: "0d12543ea570415a9e320d8a5627d097"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "VenomBlade_AoEAbility"
    ability_bp: "80e6345949784370b20b24d75bcd4c30"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "b5fe044e47604f47bf99ebd14440b579"
    bp_name: "DrukhariWeaponProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "Parry10_Feature"
  sources: "Chest - CR0: SantielUnderhiveLaboratory02"
  sources: "Unit - Ch04_FootfallSewersCh04: FootfallSewersPatrol1"
  sources: "Unit - Ch02_PenalWorld: Marazhai"
  sources: "Unit - Ch03_CommorraghArena: YrlietAbductionMarazhai"
  sources: "Unit - Ch03_Prison: MarazhaiNeutral"
  sources: "Unit - Ch03_VectTh: HarlequinZanni"
  sources: "Unit - FinalCompanions: HarlequinZanni_Companion"
  sources: "Unit - FinalCompanions: HarlequinZanni_Summon"
}
weapon {
  guid: "a0c8b0eba36043fbb89d12226db59cfa"
  blueprint_name: "GhostSword_Item"
  name_key: "815ad9b7-8d5f-42c6-82ee-3fe4db391dac"
  name: "Ghost Sword"
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 12
  max_damage: 18
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "Parry10_Feature"
}
weapon {
  guid: "4ec59f09523148f98cb05d63f63e5d4f"
  blueprint_name: "JaeQuest_DrukhariKlaivePlaceholder_Item"
  name_shared_key: "3fff279e-0d21-4a0b-8a5e-2a540eabfc42"
  name: "Bloodseeker Klaive"
  description_key: "a444c1d4-dcb1-4108-9b97-db5378e42c60"
  description: "This klaive\'s {g|Encyclopedia:AreaOfEffect}area attack{/g} has an increased area of effect."
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 17
  max_damage: 25
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 15
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "Sword_AbilityFXSettings"
    fx_bp: "a29d9b4bce7449d78fc33c1e5797d028"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "JaeQuestKlaive_AoEAbility"
    ability_bp: "08da2d70329a40a98c2e89ae8afce397"
    fx_bp_name: "Sword_AbilityFXSettings"
    fx_bp: "a29d9b4bce7449d78fc33c1e5797d028"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "b5fe044e47604f47bf99ebd14440b579"
    bp_name: "DrukhariWeaponProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level25_TesseraParty_ExportedPregen"
}
weapon {
  guid: "5d389a568e664fbea78c84c3daa51284"
  blueprint_name: "PlasmaSword_Item"
  name_shared_key: "162494e9-0331-48a6-a695-8bef3335fe37"
  description_key: "3415be74-eede-4326-9795-89b7c73afc70"
  description: "This sword ignores {g|Encyclopedia:Deflection}deflection{/g}."
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 30
  max_damage: 35
  penetration: 50
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "b96d9296d85946f692e05abe6d4c2cf8"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "PlasmaSword_Feature"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - ExportedPregens: Heinrix_level47_Gamescom2024_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level47_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level47_PetEagle_ExportedPregen"
  sources: "Unit - ExportedPregens: Uralon41Heinrix_ExportedPregen"
  sources: "Vendor - DrusianChapter4_VendorTable_Base 87PF"
}
weapon {
  guid: "b7b4b9a224b64d27a9dc89ca40b84fa0"
  blueprint_name: "PowerSwordEldar_Item"
  name_shared_key: "6bdac590-1a4f-42f3-a909-14927fb57d4e"
  name: "Craftworld Power Sword"
  description_key: "f8e398b7-fa59-435e-b727-cddd34671882"
  description: "Decreases the target\'s weapon {g|Encyclopedia:DamageGlossary}damage{/g} by \342\210\2223 for 2 {g|Encyclopedia:Round}rounds{/g} after the wielder has parried an attack.\\n<indent=5%>+30% {g|Encyclopedia:Parry}parry{/g}</indent>"
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 20
  max_damage: 30
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  stat_restriction {
    stat: "WarhammerStrength"
    requirement: 35
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "de67188c81e14025a3c34dc76bd9a6ed"
  extra_fact: "be598c125d5147c990f31909c704ef84"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "PowerSwordEldar_Feature"
  extra_fact_name: "Parry30_Feature"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - Ch04_CrownWorld: CrownWorldHarlequin_MourningChoir"
  sources: "Vendor - HaemunculiChapter3_VendorTable_Advanced 0PF"
}
weapon {
  guid: "bd1ffcfed2fe48ad9ad2d447a85e55bd"
  blueprint_name: "PowerSwordT1CH02_Item"
  name_shared_key: "d82e40f0-64a9-4fb5-b6da-917fb4f747da"
  name: "Power Sword"
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 14
  max_damage: 24
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - ExportedPregens: Gusev_RT_26lvl_ExportedPregen"
}
weapon {
  guid: "24a537db1f8847a496975ebf6994623e"
  blueprint_name: "PowerSwordT2CH04_Item"
  name_shared_key: "80b889c7-9379-4d05-89fd-969650105950"
  name: "Elite Power Sword"
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 29
  max_damage: 43
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - Ch04_ForgeHeart: CorruptedSkitariiSwarm_Melee_ForgeHeart"
  sources: "Unit - Ch05_ArcShip: ImmortalSkitariiMelee_ArcShip"
  sources: "Unit - ExportedPregens: Uralon41Pascal_ExportedPregen"
}
weapon {
  guid: "9392f467945145f484be823d5efc5889"
  blueprint_name: "PowerSword_Item"
  name_shared_key: "d82e40f0-64a9-4fb5-b6da-917fb4f747da"
  name: "Power Sword"
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 10
  max_damage: 14
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - Ch02_FootFallSlums: FootfallBanditSupport_AnverLair_LeaderHeavy"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedSkitariiAlphaPower_Melee"
  sources: "Unit - Ch02_Lair3: Lair3RebelMeleeTough"
  sources: "Unit - Ch02_PascalEvent: TarzusSkitariiActual_Melee"
  sources: "Unit - Ch05_Epitaph: InquisitorGuardSargeant"
  sources: "Unit - Ch00_OfficersDeck: FakeIdira"
  sources: "Unit - Ch00_OfficersDeck: FakeTeodora"
  sources: "Unit - Ch00_OfficersDeck: Teodora"
}
weapon {
  guid: "8c304b20633145f39577a392201d2047"
  blueprint_name: "AutoStriking_PowerSword_Item"
  name_key: "853da21b-9745-4d92-8498-e76e9d45962c"
  name: "Auto-Striking Power Sword"
  description_key: "91792d02-6d27-45d0-b125-2b3208892ca6"
  description: "When the wielder successfully {g|Encyclopedia:Parry}parries{/g} with this power sword, they immediately counter-attack with whichever attack costs the least {g|Encyclopedia:ActionPoints}AP{/g}. It also grants:\\n-<indent=5%>+30% {g|Encyclopedia:Bonus}bonus{/g} to parry.</indent>\\n-<indent=5%>On a successful {g|Encyclopedia:HitSequenceGlossary}hit{/g} with this power sword, the target suffers a \342\210\22210 {g|Encyclopedia:Penalty}penalty{/g} to {g|Encyclopedia:WarhammerWeaponSkill}Weapon Skill{/g}.</indent>"
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 26
  max_damage: 39
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "a3c5541e26f5428f853318342edcbbf4"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "AutoStriking_PowerSword_Feature"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - Ch05_Epitaph: RTNeutral"
  sources: "Unit - Ch05_Epitaph: RTNeutralFemale"
  sources: "Unit - Ch04_Canteena: Ch04Chorda_Bodyguard_unit"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level42_OlegParty_ExportedPregen"
  sources: "Unit - ExportedPregens: Kibellah40lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: Kibellah45lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: Kibellah50lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: Kibellah_level47_Gamescom2024_ExportedPregen"
}
weapon {
  guid: "719e2f637a674937910b05d90cf11ceb"
  blueprint_name: "Bloodletter_DrukhariPowerSword_Item"
  name_shared_key: "4f168cc3-2e37-44e9-a541-3d505d8f5843"
  name: "Bloodthirster"
  description_shared_key: "483cbb3b-e3aa-4336-8571-0896781ecca6"
  description: "Each {g|Encyclopedia:HitSequenceGlossary}hit{/g} decreases the target\'s {g|Encyclopedia:WarhammerWeaponSkill}Weapon Skill{/g}, {g|Encyclopedia:WarhammerBallisticSkill}Ballistic Skill{/g}, {g|Encyclopedia:WarhammerStrength}Strength{/g}, {g|Encyclopedia:WarhammerToughness}Toughness{/g}, and {g|Encyclopedia:WarhammerPerception}Perception{/g} by \342\210\2225. Stacks."
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 16
  max_damage: 24
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 10
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SerratedGreatSwordMeleeAttack_Ability"
    ability_bp: "77f1b45bf4994fc2815a416614391cd1"
    fx_bp_name: "BloodletterDrukhariPowerSword_AbilityFXSettings"
    fx_bp: "2f71f8f95ba94dc69edde993486df5f2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "SerratedGreatSwordTwoHandedSword_Ability"
    ability_bp: "7eb92bed842f485fbb1db8a71cb5229a"
    fx_bp_name: "BloodletterDrukhariPowerSword_AbilityFXSettings"
    fx_bp: "2f71f8f95ba94dc69edde993486df5f2"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "b5fe044e47604f47bf99ebd14440b579"
    bp_name: "DrukhariWeaponProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "3b641e65a8e949a586b7e23a696fec75"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "Bloodletter_DrukhariPowerSword_Feature"
  sources: "Unit - Ch02_PenalWorld: Tazarra"
}
weapon {
  guid: "366e56fd6e914a0089061a4c9294679c"
  blueprint_name: "Epiphany_PowerSword_Item"
  name_shared_key: "9b5ba274-eda5-43a0-bf7f-d5a01522a5b4"
  description_key: "e58df5c5-c09f-4478-956e-9f7aec7ec3b8"
  description: "If the wielder kills an enemy with <b>Charge</b>, this {g|Encyclopedia:Ability}ability{/g} has no {g|Encyclopedia:Cooldown}cooldown{/g}."
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 13
  max_damage: 23
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "e8f2057b69674afba5d136a759c60b76"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "Epiphany_PowerSword_Feature"
  extra_fact_name: "Parry10_Feature"
  sources: "Unit - ExportedPregens: Sayonara_39lvl_Abelard_ExportedPregen"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch04_TrueStart"
}
weapon {
  guid: "cb0a37f32de7486dbc79824d65dca7f8"
  blueprint_name: "HolySword_Item"
  name_shared_key: "77891fa8-1ec4-4eec-9816-2d21229538fa"
  description_key: "c108b630-c36f-4137-b36b-f82a8401c446"
  description: "This sword grants the following effects based on the wielder\'s rank of {g|Encyclopedia:SoulmarkTypesGlossary}Conviction{/g} \342\200\224 {g|Encyclopedia:SoulMarkFaith}Dogmatic{/g}:\\n-<indent=5%>Dogmatic \342\200\224 Adherent: ignores the {g|Encyclopedia:DodgeGlossary}dodge{/g} of xenos, daemons, and psykers.</indent>\\n-<indent=5%>Dogmatic \342\200\224 Votary: additionally ignores the {g|Encyclopedia:Deflection}deflection{/g} of xenos, daemons, and psykers.</indent>\\n-<indent=5%>Dogmatic \342\200\224 Fanatic: additionally ignores the {g|Encyclopedia:WarhammerArmourGlossary}armour{/g} of xenos, daemons, and psykers.</indent>"
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 50
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "SerratedGreatSword_AbilityFXSettings"
    fx_bp: "3f9a775831e04861afbfe9eaf8fe692b"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "MeleeAoESTwoHandedSword_ability"
    ability_bp: "163013a18e9c46419b2311454ad2b2c8"
    fx_bp_name: "GreatSword_AOE_AbilityFXSettings"
    fx_bp: "7c573c13e98b492982288e35264f64bb"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "f4b4990a85d946f8b2e863403553a3b6"
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact_name: "HolySword_Feature"
  extra_fact_name: "Parry10_Feature"
  sources: "Vendor - DrusianChapter4_VendorTable_Base 72PF"
}
weapon {
  guid: "c431fcd14b45453e8fea6b2b4186778d"
  blueprint_name: "SwordOfOnslaught_PowerSword_Item"
  name_shared_key: "69094610-a13c-4680-82a8-1e68f4b1eb6b"
  description_shared_key: "74063ba7-2494-4063-adba-d6c1c4ee2866"
  description: "Grants an additional {g|Encyclopedia:AreaOfEffect}area attack{/g} that affects all adjacent cells around the wielder.\\n<indent=5%>+1 {g|Encyclopedia:DamageGlossary}damage{/g} per target in the area of effect</indent>"
  category: Melee
  family: Power
  classification: Sword
  heavy: false
  two_handed: false
  min_damage: 12
  max_damage: 21
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SwordsMeleeAttack_Ability"
    ability_bp: "9dec1bdade284190b0977f5f70d26d3e"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "OneHandedSword_AoEAbility"
    ability_bp: "bac8a9c632934bec87c72fece5831673"
    fx_bp_name: "PowerSword_AbilityFXSettings"
    fx_bp: "1bc92b9832fe402caa887d8c5d990cb4"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: AOE
    ability_bp_name: "SwordOfOnslaught_AoEAbility"
    ability_bp: "bb3fd8ea6c9e425780be92e054ace715"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "53c19a9468d24539863989b3be9ed1f5"
  extra_fact: "c922721a6e314e18ab92cb02a0821fa9"
  extra_fact_name: "Parry10_Feature"
  extra_fact_name: "SwordOfOnslaught_Feature"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level29_ExportedPregen"
  sources: "Unit - ExportedPregens: RT_Lvl40_Bakula_ExportedPregen"
}

