# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "65b71d29858f4543b4e4c4a6b82aee52"
  blueprint_name: "AstropathsStaff_Item"
  name_shared_key: "65e19d83-b58b-46f7-9cf4-50b0b1dd5ead"
  name: "Detachment From Death"
  description_shared_key: "636f0984-4618-42db-a31b-de928fa66ee0"
  description: "Allies of this staff\'s wielder have their dodge increased by +{unit_stat|WarhammerWillpower|bonus}%."
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbility"
    ability_bp: "5a328c19cc214780b878be2183550910"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbilityHeroic"
    ability_bp: "5b19d80b3d694f77b84c2b38a04efe8f"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbilityDesperate"
    ability_bp: "8986fa989c474068b160ab1af21d763c"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "c074bd8a210743f48cbb536e3c7c677f"
    bp_name: "Telepathy_Base_Feature"
  }
  extra_fact: "b6444939f07e458886eb4f5eb62667e7"
  extra_fact: "848938f7390e437baf5c472e74b88361"
  extra_fact_name: "Willpower10_Feature"
  extra_fact_name: "AstropathsStaff_Feature"
  sources: "Unit - DLC1_AstropathicChapel: ChoirMaster"
}
weapon {
  guid: "e96f3bfb11bc4c47a1ef1fd1e0f61a04"
  blueprint_name: "AstropathStaffOfMindsight_Item"
  name_shared_key: "b05fb2b1-b7bb-40c5-b411-ae8eb76406cf"
  name: "Thought Guide"
  description_shared_key: "57cc0d53-836a-4677-9367-194c972d7620"
  description: "Allies of the wielder affected by psychic powers gain +{uip|Resolve|7d24ba5d71364a87ae9d1b7071b5bcd3} resolve for 1 round.\\n<indent=5%>+10 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbility"
    ability_bp: "5a328c19cc214780b878be2183550910"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbilityHeroic"
    ability_bp: "5b19d80b3d694f77b84c2b38a04efe8f"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbilityDesperate"
    ability_bp: "8986fa989c474068b160ab1af21d763c"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "c074bd8a210743f48cbb536e3c7c677f"
    bp_name: "Telepathy_Base_Feature"
  }
  extra_fact: "b6444939f07e458886eb4f5eb62667e7"
  extra_fact: "7d24ba5d71364a87ae9d1b7071b5bcd3"
  extra_fact_name: "Willpower10_Feature"
  extra_fact_name: "AstropathStaffOfMindsight_Feature"
  sources: "Vendor - PirateChapter4_VendorTable_Base 90PF"
}
weapon {
  guid: "aac1b16141ce4a9ebdce7970cc4fbd7a"
  blueprint_name: "BiomancersStaff_Item"
  name_key: "575b4bae-1846-4bef-aa05-4f10ee85c49f"
  name: "Biomancer\'s Staff"
  description_key: "c15583b6-4f76-4c7d-b81d-d48869e1d308"
  description: "The wielder of this staff (power level 6) gains the <b>Syphon Life</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} and healing level of this power.\\n<indent=5%>+10 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Biomancy_Weapon_SyphonLife_Ability"
    ability_bp: "fb5efed90c6442acb6f9c756905072eb"
    fx_bp_name: "SyphonLifeAbility_AbilityFXSettings"
    fx_bp: "eedccf9286064c0ab0d43d2463137315"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "Biomancy_Weapon_SyphonLife_AbilityHeroic"
    ability_bp: "f8629a743eaf414eb8bf79edee9b02d0"
    fx_bp_name: "SyphonLifeAbility_AbilityFXSettings"
    fx_bp: "eedccf9286064c0ab0d43d2463137315"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "Biomancy_Weapon_SyphonLife_AbilityDesperate"
    ability_bp: "65791f6355c04864b890c9e964b9c372"
    fx_bp_name: "SyphonLifeAbility_AbilityFXSettings"
    fx_bp: "eedccf9286064c0ab0d43d2463137315"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "5fa599e5cffc4bab93d6b07f68e0e6ba"
    bp_name: "Biomancy_Base_Feature"
  }
  extra_fact: "b6444939f07e458886eb4f5eb62667e7"
  extra_fact_name: "Willpower10_Feature"
  sources: "Unit - DLC2_FeudalWorld: FW_Sculptor"
  sources: "Unit - ExportedPregens: 4y6_Heinrix_22lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: 4y6_Heinrix_27lvl_ExportedPregen_ExportedPregen"
  sources: "Unit - ExportedPregens: Heinrix19Chapel_ExportedPregen"
  sources: "Unit - ExportedPregens: VasiliyHeinrix_15LvL_ExportedPregen"
  sources: "Unit - HeinrixCompanion: HeinrixCompanionNPC"
}
weapon {
  guid: "5f4091e7ebae4cfea6831d72db37ba33"
  blueprint_name: "BlooddrinkingStaff_Item"
  name_shared_key: "53023764-ce5b-4ee6-aa47-1df75b02fbfc"
  name: "Blooddrinker Staff"
  description_shared_key: "fb66ac1c-739b-484b-a2d5-c8377b2941d4"
  description: "The wielder of this staff gains <b>Syphon Life</b> {g|Encyclopedia:Ability}ability{/g} at power level 13. The ability is also available in its {g|Encyclopedia:HeroicAct}Heroic Act{/g} and {g|Encyclopedia:DesperateMeasure}Desperate Measure{/g} versions. The power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} and healing level of this power. In combat, the psyker wielding the staff suffers {g|Encyclopedia:BleedingEffect}bleeding{/g}. The bleeding damage every {g|Encyclopedia:Round}round{/g} is equal to the psyker\'s {g|Encyclopedia:PsyRating}psy rating{/g}.\\n<indent=5%>+20 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>\\n<indent=5%>+2 psy rating</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 13
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Biomancy_Weapon_SyphonLife_Ability"
    ability_bp: "fb5efed90c6442acb6f9c756905072eb"
    fx_bp_name: "SyphonLifeAbility_AbilityFXSettings"
    fx_bp: "eedccf9286064c0ab0d43d2463137315"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "Biomancy_Weapon_SyphonLife_AbilityHeroic"
    ability_bp: "f8629a743eaf414eb8bf79edee9b02d0"
    fx_bp_name: "SyphonLifeAbility_AbilityFXSettings"
    fx_bp: "eedccf9286064c0ab0d43d2463137315"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "Biomancy_Weapon_SyphonLife_AbilityDesperate"
    ability_bp: "65791f6355c04864b890c9e964b9c372"
    fx_bp_name: "SyphonLifeAbility_AbilityFXSettings"
    fx_bp: "eedccf9286064c0ab0d43d2463137315"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "5fa599e5cffc4bab93d6b07f68e0e6ba"
    bp_name: "Biomancy_Base_Feature"
  }
  extra_fact: "98a981e836d7416bbd498d09797b78ce"
  extra_fact: "0bf140afa0234176b00697a0e4eb8370"
  extra_fact_name: "Willpower20_Feature"
  extra_fact_name: "BlooddrinkingStaff_Feature"
  sources: "Chest - CR0: ReavingTempestSpire_GoodLoot02"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_Shaman"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_ShamanVillage"
  sources: "Unit - FakeAndWeak_WinterscaleParty: Quetza_Fake_Shaman"
  sources: "Unit - ExportedPregens: HeinrixCompanion_35_DLC2_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level42_OlegParty_ExportedPregen"
}
weapon {
  guid: "3a0d1cc8073b4e819ac2ba39120d6ad3"
  blueprint_name: "ChargedStaffItem"
  name_shared_key: "39344a95-84ef-4d49-8851-e71e04fc81fd"
  name: "Charged Staff"
  description_key: "ff86b17d-8711-4e2f-871d-706a357551b9"
  description: "The wielder of this staff (power level 9) gains the <b>Lightning Arc</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power.\\n<indent=5%>+10 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "ChainLightningAbility"
    ability_bp: "7b68b4aa3c024f348a20dce3ef172e40"
    fx_bp_name: "ChainLightning_AbilityFXSettings"
    fx_bp: "9a14a57512004161a91ec337f252e03c"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "ChainLightningPushAbility"
    ability_bp: "635161f3087c4294bf39c5fefe3d01af"
    fx_bp_name: "ChainLightning_AbilityFXSettings"
    fx_bp: "9a14a57512004161a91ec337f252e03c"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "ChainLightningDesperatePushAbility"
    ability_bp: "3c48374cbe244fc2bb8b6293230a6829"
    fx_bp_name: "ChainLightning_AbilityFXSettings"
    fx_bp: "9a14a57512004161a91ec337f252e03c"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "8ec7af173e174f269460f11528828bb0"
    bp: "395a77ff6fd344f5b8b4a0cc0def06dc"
    bp: "2f38c67478fd42ab9947fbabcf6ed17c"
    bp_name: "SanctionedPsyker"
    bp_name: "UnsanctionedPsyker"
    bp_name: "UnsanctionedPsykerSimplified"
  }
  extra_fact: "b027ad4f868f4cf1a5dcdf762c688605"
  extra_fact_name: "ChargedStaff_Feature"
  sources: "Chest - CR10: Forest_GoodLoot1"
  sources: "Unit - ExportedPregens: 4y6_Idira_22lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: 4y6_Idira_22lvl_PetRaven_ExportedPregen"
  sources: "Unit - ExportedPregens: 4y6_Idira_27lvl_ExportedPregen_ExportedPregen"
  sources: "Unit - ExportedPregens: Idira19Chapel_ExportedPregen"
  sources: "Unit - ExportedPregens: IdiraCompanion_Level25_MikandraParty_ExportedPregen"
  sources: "Unit - ExportedPregens: IdiraCompanion_Level39_PetRaven"
  sources: "Unit - ExportedPregens: IdiraCompanion_Level_27_Overseer"
  sources: "Unit - ExportedPregens: IdiraCompanion_lvl38_treasureworld_ExportedPregen"
  sources: "Unit - ExportedPregens: IdiraCompanion_lvl38_treasureworld_PetRaven_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level25_TesseraParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level37_TesseraParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level37_ValladinParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level47_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level47_PetEagle_ExportedPregen"
  sources: "Unit - ExportedPregens: RT_lv38_chordafight_Psyker_ExportedPregen"
  sources: "Unit - ExportedPregens: RT_lvl38_treasureworld_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_23_Idira_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_39lvl_Idira_ExportedPregen"
  sources: "Unit - ExportedPregens: Yanus19RT_ExportedPregen"
  sources: "Unit - ExportedPregens: zin_22_IdiraCompanion_ExportedPregen"
}
weapon {
  guid: "16ac3e0bae2243b59d3e735817142f00"
  blueprint_name: "DivinersStaff_Item"
  name_key: "ec0da6a2-5082-4846-bd53-1dd085a987f1"
  name: "Diviner\'s Staff"
  description_key: "64c488a5-7862-46d1-b061-f4ff51421b07"
  description: "The wielder of this staff gains the <b>Consign</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions.\\n<indent=5%>+5 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>\\n<indent=5%>+5 {g|Encyclopedia:WarhammerPerception}Perception{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "BluntAttack_AbilityFXSettings"
    fx_bp: "b42607999b9740c1ac74fc7d63ae0451"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Divination_Weapon_Consign_Ability"
    ability_bp: "26787468defa42598581625e2164ffd8"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 0
  }
  ability3 {
    type: Custom
    ability_bp_name: "Divination_Weapon_Consign_AbilityHeroic"
    ability_bp: "1598fb26e644442098e72562537ae660"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 0
  }
  ability4 {
    type: Custom
    ability_bp_name: "Divination_Weapon_Consign_AbilityDesperate"
    ability_bp: "4e6482c67f0548668107514fd187dadd"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 0
  }
  fact_requirement {
    all: false
    negate: false
    bp: "196d258a786c42e68eb4a468efb0089e"
    bp_name: "Divination_Base_Feature"
  }
  extra_fact: "93cc723519914813b176a0d0a410d81e"
  extra_fact: "9419c92956af4b1c8504da060aed09d8"
  extra_fact_name: "Willpower5_Feature"
  extra_fact_name: "Perception5_Feature"
  sources: "Chest - JailPlanetoid: Loot_Good_Hidden - Table"
  sources: "Unit - Ch04_Canteena: Ch04Chorda_Psyker_unit"
  sources: "Unit - Ch05_Epitaph: Ch05Inquisitor_Psyker_unit"
}
weapon {
  guid: "993996a4c0a24463aa400b9441d4caa8"
  blueprint_name: "ImperialStaff_Item"
  name_shared_key: "2083f8d5-cdc9-4ff7-b11a-0c89d3faa4d4"
  name: "Imperial Staff"
  description_shared_key: "2c534cf0-d2a7-4dcd-a87e-b5f1917ae947"
  description: "The wielder of this staff (power level 8) gains the <b>Emperor\'s Wrath</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power.\\n<indent=5%>+10 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>\\n<indent=5%>+5 {g|Encyclopedia:WarhammerFellowship}Fellowship{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Sanctic_Weapon_EmperorsWrath_Ability"
    ability_bp: "560aa7c658a441df8bb4b2f9f431064b"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "Sanctic_Weapon_EmperorsWrath_AbilityHeroic"
    ability_bp: "bdde427505b14cd68b20ab0d915d5fe3"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "Sanctic_Weapon_EmperorsWrath_AbilityDesperate"
    ability_bp: "7039f3b35fc5487e9b6c64909062ea04"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "a6a38016b90148878593d977d96b8264"
    bp_name: "SancticBaseFeature"
  }
  extra_fact: "b6444939f07e458886eb4f5eb62667e7"
  extra_fact: "ff44db0984644b5aa1abd779ac081262"
  extra_fact_name: "Willpower10_Feature"
  extra_fact_name: "Fellowship5_Feature"
  sources: "Chest - CR25: ImperiumRich_CorpseUnderWall"
  sources: "Unit - DLC1_Ch02_AstropathicChapel: IdiraPsyker_Imperium_AstropathicChapelCH2"
}
weapon {
  guid: "5b3cc3ca06714fbb8f735be239856215"
  blueprint_name: "Mindkiller_Item"
  name_shared_key: "efd4f686-4058-47ec-b191-8080d5a68cc0"
  name: "Mindkiller Staff"
  description_shared_key: "8b58a984-565d-4c47-96c8-bc29bbd5a50f"
  description: "Each enemy the psyker kills with a {g|Encyclopedia:PsykerPowersGlossary}psychic power{/g} from the telepathy discipline permanently increases the effective power level of all telepathy discipline staves this character wields by +1."
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 20
  max_damage: 25
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbility"
    ability_bp: "5a328c19cc214780b878be2183550910"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbilityHeroic"
    ability_bp: "5b19d80b3d694f77b84c2b38a04efe8f"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbilityDesperate"
    ability_bp: "8986fa989c474068b160ab1af21d763c"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "c074bd8a210743f48cbb536e3c7c677f"
    bp_name: "Telepathy_Base_Feature"
  }
  extra_fact: "98a981e836d7416bbd498d09797b78ce"
  extra_fact: "b3b19f84c8cd4d9e8599cb2cbb270203"
  extra_fact_name: "Willpower20_Feature"
  extra_fact_name: "Mindkiller_Feature"
  sources: "Chest - EpitaphEntrance: AdeptusMechanicus_HiddenLoot"
}
weapon {
  guid: "be31976934e8459c8cfbbafefac1e350"
  blueprint_name: "PsyFocusIdiraStartStaffItem"
  name_shared_key: "d924a718-278b-4e2b-8211-9ab667b2d1cc"
  name: "Psychic Staff"
  description_key: "110ed081-7307-4a99-8e0d-648c75a645fa"
  description: "The wielder of this staff (power level 6) gains the <b>Lightning Arc</b> {g|Encyclopedia:Ability}ability{/g}. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power."
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "ChainLightningAbility"
    ability_bp: "7b68b4aa3c024f348a20dce3ef172e40"
    fx_bp_name: "ChainLightning_AbilityFXSettings"
    fx_bp: "9a14a57512004161a91ec337f252e03c"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "8ec7af173e174f269460f11528828bb0"
    bp: "395a77ff6fd344f5b8b4a0cc0def06dc"
    bp: "2f38c67478fd42ab9947fbabcf6ed17c"
    bp_name: "SanctionedPsyker"
    bp_name: "UnsanctionedPsyker"
    bp_name: "UnsanctionedPsykerSimplified"
  }
  extra_fact: "03dab3facd004004ac0983cb333198a5"
  extra_fact_name: "PsyFocusIdiraStartStaff_Feature"
}
weapon {
  guid: "bff869dc979f4229af857cb15cb294ac"
  blueprint_name: "PsyFocusStaffItem"
  name_shared_key: "d924a718-278b-4e2b-8211-9ab667b2d1cc"
  name: "Psychic Staff"
  description_key: "4b0e50ec-0a72-4db1-8436-ed070f89b89c"
  description: "The wielder of this staff (power level 6) gains the <b>Lightning Arc</b> {g|Encyclopedia:Ability}ability{/g}. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power.\\n<indent=5%>+5 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "ChainLightningAbility"
    ability_bp: "7b68b4aa3c024f348a20dce3ef172e40"
    fx_bp_name: "ChainLightning_AbilityFXSettings"
    fx_bp: "9a14a57512004161a91ec337f252e03c"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "8ec7af173e174f269460f11528828bb0"
    bp: "395a77ff6fd344f5b8b4a0cc0def06dc"
    bp: "2f38c67478fd42ab9947fbabcf6ed17c"
    bp_name: "SanctionedPsyker"
    bp_name: "UnsanctionedPsyker"
    bp_name: "UnsanctionedPsykerSimplified"
  }
  extra_fact: "98046c678b3046c1ac099000b3df14f6"
  extra_fact_name: "PsyFocusStaff_Feature"
  sources: "Unit - Ch00_OfficersDeck: CultistPsyker_Ranged_OfficersDeck"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsCultistLeader"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsCultistLeader00"
  sources: "Unit - DLC1_Ch02_AstropathicChapel: Herimon_AstropathicChapelCH2"
  sources: "Unit - DLC1_LowerTunnel: GenestealerMagus_MeleeRanged_VoidshipCrypt1"
  sources: "Unit - ExportedPregens: IdiraCompanion_Level15_ExportedPregen"
  sources: "Unit - ExportedPregens: IdiraCompanion_Level7_EtelParty_ExportedPregen"
  sources: "Unit - ExportedPregens: idira_lv38_chordafight_ExportedPregen"
  sources: "Unit - ExportedPregens: VasiliyRt_15LvL_ExportedPregen"
}
weapon {
  guid: "c2e9878620fd4653b06a96e4cda2c967"
  blueprint_name: "PyromancersStaff_Item"
  name_shared_key: "64219d58-0a4f-41af-9a0f-ce8f16f5521c"
  name: "Pyromancer\'s Staff"
  description_shared_key: "88e0b949-b51b-4900-be72-9b489f6b277c"
  description: "The wielder of this staff (power level 7) gains the <b>Inferno</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power.\\n<indent=5%>+10 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "Pyromancy_Weapon_Inferno_Ability"
    ability_bp: "8a759cdc2b754309b1fb75397798fbf1"
    fx_bp_name: "PsykerPyromancyFireball00_AbilityFXSettings"
    fx_bp: "fd4e90328b3546feb38087b797de3db2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Burst
    ability_bp_name: "Pyromancy_Weapon_Inferno_AbilityHeroic"
    ability_bp: "84ddefd28f224d5fb3f5e176375c1f05"
    fx_bp_name: "PsykerPyromancyFireball00_AbilityFXSettings"
    fx_bp: "fd4e90328b3546feb38087b797de3db2"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Burst
    ability_bp_name: "Pyromancy_Weapon_Inferno_AbilityDesperate"
    ability_bp: "c4ea2ad9fe1e4509916cb5f1787b1530"
    fx_bp_name: "PsykerPyromancyFireball00_AbilityFXSettings"
    fx_bp: "fd4e90328b3546feb38087b797de3db2"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "b4d60f6a91b94d02840a58fd9df863cd"
    bp_name: "Pyromancy_Base_Feature"
  }
  extra_fact: "b6444939f07e458886eb4f5eb62667e7"
  extra_fact: "a952a91c1b1d416ebd6d7395f7b2542f"
  extra_fact: "549326560051464bb14d17c16183c7c7"
  extra_fact_name: "Willpower10_Feature"
  extra_fact_name: "InfernoAbility_Feature"
  extra_fact_name: "PyromancersStaff_Feature"
  sources: "Chest - StarPort: AdeptusMechanicusStarport_TrashLoot_Hidden"
  sources: "Chest - StarPort: AdeptusMechanicus_TrashLoot_Hidden"
  sources: "Unit - DLC1_Ch02_AstropathicChapel: IdiraPsyker_Light_AstropathicChapelCH2"
  sources: "Unit - DLC2_BoardedShip_Bridge: BoardedShip_Captain_Normal_Boss"
  sources: "Unit - ExportedPregens: PlayerRT_Level22_Pyromant_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level27_CyrusParty_ExportedPregen"
}
weapon {
  guid: "266766be7aab4142af87ba3e76e0ddce"
  blueprint_name: "SanctifiedStaff_Item"
  name_shared_key: "0ff0f68a-397e-4b8a-923f-9d90ccbde2bb"
  name: "Sanctified Staff"
  description_shared_key: "09cf422d-85f5-4dbf-a0e3-672f64c6bc0d"
  description: "The wielder of this staff, with a power level of {uip|PowerLevel|e401f82ef7134a31b40cbf821f24a8f6}, gains the <b>Emperor\'s Wrath</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power.\\nUsing <b>Emperor\'s Wrath</b> grants the psyker additional {g|Encyclopedia:WarhammerArmourGlossary}armour{/g} equal to the staff\'s power level until the start of the psyker\'s next {g|Encyclopedia:Turn}turn{/g}. Does not stack.\\n<indent=5%>+15 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>\\n<indent=5%>+10 {g|Encyclopedia:WarhammerFellowship}Fellowship{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Sanctic_Weapon_EmperorsWrath_Ability"
    ability_bp: "560aa7c658a441df8bb4b2f9f431064b"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "Sanctic_Weapon_EmperorsWrath_AbilityHeroic"
    ability_bp: "bdde427505b14cd68b20ab0d915d5fe3"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "Sanctic_Weapon_EmperorsWrath_AbilityDesperate"
    ability_bp: "7039f3b35fc5487e9b6c64909062ea04"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "a6a38016b90148878593d977d96b8264"
    bp_name: "SancticBaseFeature"
  }
  extra_fact: "e401f82ef7134a31b40cbf821f24a8f6"
  extra_fact: "a5038c9866404df58f22b175262a2989"
  extra_fact: "1ca44da780fa430abfa92202f3a3602d"
  extra_fact_name: "SanctifiedStaff_Features"
  extra_fact_name: "Willpower15_Feature"
  extra_fact_name: "Fellowship10_Feature"
  sources: "Unit - ExportedPregens: Gusev_Idira_26lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level25_TesseraParty_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level37_TesseraParty_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level37_ValladinParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level42_OlegParty_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_Heinrix_23lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: Yanus19Hen_ExportedPregen"
  sources: "Vendor - DrusianChapter2_VendorTable_Base 20PF"
}
weapon {
  guid: "7da9005aaf4d49969ff989cf0b1619cb"
  blueprint_name: "SolarStaff_Item"
  name_shared_key: "1a2a5a54-848e-4bff-8423-ead5e476a308"
  name: "Solar Staff"
  description_shared_key: "4bad054a-b394-442c-9ce4-1954186f77b6"
  description: "The wielder of this staff (power level 10) gains the <b>Inferno</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power. For every two creatures suffering {g|Encyclopedia:BurningEffect}burning{/g} in combat, the power level of this staff is increased by +1 and the {g|Encyclopedia:WarhammerWillpower}Willpower{/g} {g|Encyclopedia:Bonus}bonus{/g} is increased by +2.\\n<indent=5%>+15 Willpower</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 16
  max_damage: 21
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Pyromancy_Weapon_Inferno_Ability"
    ability_bp: "8a759cdc2b754309b1fb75397798fbf1"
    fx_bp_name: "PsykerPyromancyFireball00_AbilityFXSettings"
    fx_bp: "fd4e90328b3546feb38087b797de3db2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "Pyromancy_Weapon_Inferno_AbilityHeroic"
    ability_bp: "84ddefd28f224d5fb3f5e176375c1f05"
    fx_bp_name: "PsykerPyromancyFireball00_AbilityFXSettings"
    fx_bp: "fd4e90328b3546feb38087b797de3db2"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "Pyromancy_Weapon_Inferno_AbilityDesperate"
    ability_bp: "c4ea2ad9fe1e4509916cb5f1787b1530"
    fx_bp_name: "PsykerPyromancyFireball00_AbilityFXSettings"
    fx_bp: "fd4e90328b3546feb38087b797de3db2"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "b4d60f6a91b94d02840a58fd9df863cd"
    bp_name: "Pyromancy_Base_Feature"
  }
  extra_fact: "d5abec723f024db88c408dc12b64f6df"
  extra_fact: "a5038c9866404df58f22b175262a2989"
  extra_fact: "a952a91c1b1d416ebd6d7395f7b2542f"
  extra_fact_name: "SolarStaff_Feature"
  extra_fact_name: "Willpower15_Feature"
  extra_fact_name: "InfernoAbility_Feature"
  sources: "Unit - Ch05_Epitaph: RTHope"
  sources: "Unit - Ch05_Epitaph: RTHopeFemale"
  sources: "Unit - ExportedPregens: Uralon41Heinrix_ExportedPregen"
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 100PF"
}
weapon {
  guid: "d2fcdc1b825044e3862e4be02769d694"
  blueprint_name: "StaffOfBlood_Item"
  name_key: "8cf2bf9c-fd2c-4327-bafc-5296d545a28f"
  name: "Staff of Blood"
  description_key: "39eee82e-c211-4ec1-b9b2-938d60a7ad2d"
  description: "The wielder of this staff (power level 9) gains the <b>Syphon Life</b> {g|Encyclopedia:Ability}ability{/g}. This ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} and healing level of this power.\\n<indent=5%>+15 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>\\n<indent=5%>+10 {g|Encyclopedia:WarhammerToughness}Toughness{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 13
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Biomancy_Weapon_SyphonLife_Ability"
    ability_bp: "fb5efed90c6442acb6f9c756905072eb"
    fx_bp_name: "SyphonLifeAbility_AbilityFXSettings"
    fx_bp: "eedccf9286064c0ab0d43d2463137315"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "Biomancy_Weapon_SyphonLife_AbilityHeroic"
    ability_bp: "f8629a743eaf414eb8bf79edee9b02d0"
    fx_bp_name: "SyphonLifeAbility_AbilityFXSettings"
    fx_bp: "eedccf9286064c0ab0d43d2463137315"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "Biomancy_Weapon_SyphonLife_AbilityDesperate"
    ability_bp: "65791f6355c04864b890c9e964b9c372"
    fx_bp_name: "SyphonLifeAbility_AbilityFXSettings"
    fx_bp: "eedccf9286064c0ab0d43d2463137315"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "5fa599e5cffc4bab93d6b07f68e0e6ba"
    bp_name: "Biomancy_Base_Feature"
  }
  extra_fact: "a5038c9866404df58f22b175262a2989"
  extra_fact: "d9dd93d556be46d199184a7bdf4407a7"
  extra_fact_name: "Willpower15_Feature"
  extra_fact_name: "Toughness10_Feature"
  sources: "Chest - ForgeWorld: AdeptusMechanicus_MeltaUltima_Item_Loot"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level29_ExportedPregen"
  sources: "Unit - ExportedPregens: Henrix35Yremeris_ExportedPregen"
}
weapon {
  guid: "434561775c6840889db51d764667aacb"
  blueprint_name: "StaffofEndlessFlame_Item"
  name_shared_key: "b08f73a4-055b-4819-8cea-0909a64e0557"
  name: "Staff of Endless Flame"
  description_shared_key: "5c376901-7311-41c9-82f0-d8a2ed914e0d"
  description: "The wielder of this staff (power level 7) gains the <b>Inferno</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power. For every two creatures suffering {g|Encyclopedia:BurningEffect}burning{/g} in combat, the power level of this staff is increased by +1.\\n<indent=5%>+15 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 16
  max_damage: 21
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Pyromancy_Weapon_Inferno_Ability"
    ability_bp: "8a759cdc2b754309b1fb75397798fbf1"
    fx_bp_name: "PsykerPyromancyFireball00_AbilityFXSettings"
    fx_bp: "fd4e90328b3546feb38087b797de3db2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "Pyromancy_Weapon_Inferno_AbilityHeroic"
    ability_bp: "84ddefd28f224d5fb3f5e176375c1f05"
    fx_bp_name: "PsykerPyromancyFireball00_AbilityFXSettings"
    fx_bp: "fd4e90328b3546feb38087b797de3db2"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "Pyromancy_Weapon_Inferno_AbilityDesperate"
    ability_bp: "c4ea2ad9fe1e4509916cb5f1787b1530"
    fx_bp_name: "PsykerPyromancyFireball00_AbilityFXSettings"
    fx_bp: "fd4e90328b3546feb38087b797de3db2"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "b4d60f6a91b94d02840a58fd9df863cd"
    bp_name: "Pyromancy_Base_Feature"
  }
  extra_fact: "a5038c9866404df58f22b175262a2989"
  extra_fact: "03a41d1eff0b4d6daf3105eeb40bcdbf"
  extra_fact: "a952a91c1b1d416ebd6d7395f7b2542f"
  extra_fact_name: "Willpower15_Feature"
  extra_fact_name: "StaffofEndlessFlame_Feature"
  extra_fact_name: "InfernoAbility_Feature"
  sources: "Unit - Ch04_Canteena: Ch04Chorda_Pyromancer_unit"
  sources: "Unit - ExportedPregens: PlayerRT_Level29_ExportedPregen"
  sources: "Unit - ExportedPregens: RT_lv38_chordafight_Psyker_ExportedPregen"
  sources: "Unit - ExportedPregens: RT_lvl38_treasureworld_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_39lvl_Idira_ExportedPregen"
  sources: "Vendor - PirateChapter2_VendorTable_Base 30PF"
}
weapon {
  guid: "4cec384d96554d07a877aba50df57d86"
  blueprint_name: "StaffofGravityControl_Item"
  name_shared_key: "5b95a814-fd0b-46b7-82ed-574cfe789a31"
  name: "Staff of Gravity Control"
  description_shared_key: "14fdc31a-425c-49ee-9a25-80e64da2d5ff"
  description: "Enemies that begin their {g|Encyclopedia:Turn}turn{/g} {g|Encyclopedia:Stun}stunned{/g} or {g|Encyclopedia:ImmobilisedEffect}immobilised{/g} within the psyker\'s {g|Encyclopedia:LineOfSight}line of sight{/g} suffer 14 {g|Encyclopedia:DamageGlossary}damage{/g}."
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 16
  max_damage: 21
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "TelekinesisWeaponBindAbility"
    ability_bp: "8c23fa35c325419a817aae4bdca2a67b"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "TelekinesisWeaponBindAbilityHeroic"
    ability_bp: "9edd0e95bfea4532b764920a7b7f67bf"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "TelekinesisWeaponBindAbilityDesperate"
    ability_bp: "80fac3e0f5f54316ab6e10d6268969d2"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "3a12f16f99fa4d89981d0625a91c98da"
    bp_name: "Telekinesis_Base_Feature"
  }
  extra_fact: "5d221d9dda6947e5b2d6310d6ce98b85"
  extra_fact: "98a981e836d7416bbd498d09797b78ce"
  extra_fact_name: "StaffofGravityControl_Feature"
  extra_fact_name: "Willpower20_Feature"
}
weapon {
  guid: "c58a9c1a7e7348a0905a47521283d910"
  blueprint_name: "StaffOfKrudarach_Item"
  name_key: "b957c864-8176-4282-a372-5bb0cda73c66"
  name: "Staff of Krudarach"
  description_key: "9ef2d698-979e-4514-ba73-f20754d95135"
  description: "The wielder of this staff gains the <b>Consign</b> {g|Encyclopedia:Ability}ability{/g}. This ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. The wielder\'s divination {g|Encyclopedia:PsykerPowersGlossary}psychic powers{/g} that affect one ally also affect the ally closest to the target. Divination psychic powers, including <b>Consign</b>, that affect one enemy also affect the enemy closest to the target.\\n<indent=5%>+20 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>\\n<indent=5%>+10 {g|Encyclopedia:WarhammerPerception}Perception{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 16
  max_damage: 21
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "BluntAttack_AbilityFXSettings"
    fx_bp: "b42607999b9740c1ac74fc7d63ae0451"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Divination_Weapon_Consign_Ability"
    ability_bp: "26787468defa42598581625e2164ffd8"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 0
  }
  ability3 {
    type: Custom
    ability_bp_name: "Divination_Weapon_Consign_AbilityHeroic"
    ability_bp: "1598fb26e644442098e72562537ae660"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 0
  }
  ability4 {
    type: Custom
    ability_bp_name: "Divination_Weapon_Consign_AbilityDesperate"
    ability_bp: "4e6482c67f0548668107514fd187dadd"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 0
  }
  fact_requirement {
    all: true
    negate: false
    bp: "196d258a786c42e68eb4a468efb0089e"
    bp: "395a77ff6fd344f5b8b4a0cc0def06dc"
    bp_name: "Divination_Base_Feature"
    bp_name: "UnsanctionedPsyker"
  }
  extra_fact: "98a981e836d7416bbd498d09797b78ce"
  extra_fact: "edb2e208ba52466c94d7e9524d45c12c"
  extra_fact: "f145703bfe084724b7b460c5b261722f"
  extra_fact_name: "Willpower20_Feature"
  extra_fact_name: "Perception10_Feature"
  extra_fact_name: "StaffOfKrudarach_Feature"
  sources: "Unit - Ch04_TheDoor: TheDoorFarseer"
}
weapon {
  guid: "a203c9d0a56a41faba4774bee96ea2fa"
  blueprint_name: "StaffOfMindsight_Item"
  name_shared_key: "d4f915eb-eecf-484f-bdaa-6996c184a614"
  name: "Staff of Mindsight"
  description_shared_key: "f942a57c-e858-4e89-b534-99aada522b23"
  description: "The wielder of this staff (power level 12) gains the <b>Vision of Death</b> {g|Encyclopedia:Ability}ability{/g}. This ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power. Enemies suffer a \342\210\22210 {g|Encyclopedia:Penalty}penalty{/g} to all {g|Encyclopedia:ResistanceTest}resistance tests{/g} against {g|Encyclopedia:PsykerPowersGlossary}psychic powers{/g} of the telepathy discipline used by the wielder.\\n<indent=5%>+15 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>\\n<indent=5%>+10 {g|Encyclopedia:WarhammerPerception}Perception{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbility"
    ability_bp: "5a328c19cc214780b878be2183550910"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbilityHeroic"
    ability_bp: "5b19d80b3d694f77b84c2b38a04efe8f"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbilityDesperate"
    ability_bp: "8986fa989c474068b160ab1af21d763c"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "c074bd8a210743f48cbb536e3c7c677f"
    bp_name: "Telepathy_Base_Feature"
  }
  extra_fact: "a5038c9866404df58f22b175262a2989"
  extra_fact: "edb2e208ba52466c94d7e9524d45c12c"
  extra_fact: "107292efcefe4703994b3f69e666af6e"
  extra_fact_name: "Willpower15_Feature"
  extra_fact_name: "Perception10_Feature"
  extra_fact_name: "StaffOfMindsight_Feature"
  sources: "Chest - CR25: BottomlessPit_GoodHidden"
  sources: "Unit - ExportedPregens: PlayerRT_Level25_TesseraParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level37_TesseraParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level37_ValladinParty_ExportedPregen"
}
weapon {
  guid: "08824553c62145a78d642fde86286c6e"
  blueprint_name: "StaffOfShockAndAwe_Item"
  name_shared_key: "d633ef65-b6fe-43cb-b239-140631bb2beb"
  name: "Staff of Shock and Awe"
  description_shared_key: "04d1aee4-b1cd-48ff-b89d-639905ba03f9"
  description: "The wielder of this staff (power level 18) gains the <b>Lightning</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power.\\n<indent=5%>+20 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 16
  max_damage: 21
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "ChainLightningAbility"
    ability_bp: "7b68b4aa3c024f348a20dce3ef172e40"
    fx_bp_name: "ChainLightning_AbilityFXSettings"
    fx_bp: "9a14a57512004161a91ec337f252e03c"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "ChainLightningPushAbility"
    ability_bp: "635161f3087c4294bf39c5fefe3d01af"
    fx_bp_name: "ChainLightning_AbilityFXSettings"
    fx_bp: "9a14a57512004161a91ec337f252e03c"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "ChainLightningDesperatePushAbility"
    ability_bp: "3c48374cbe244fc2bb8b6293230a6829"
    fx_bp_name: "ChainLightning_AbilityFXSettings"
    fx_bp: "9a14a57512004161a91ec337f252e03c"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "8ec7af173e174f269460f11528828bb0"
    bp: "395a77ff6fd344f5b8b4a0cc0def06dc"
    bp: "2f38c67478fd42ab9947fbabcf6ed17c"
    bp_name: "SanctionedPsyker"
    bp_name: "UnsanctionedPsyker"
    bp_name: "UnsanctionedPsykerSimplified"
  }
  extra_fact: "98a981e836d7416bbd498d09797b78ce"
  extra_fact_name: "Willpower20_Feature"
  sources: "Unit - Ch05_Epitaph: IdiraAlternative"
  sources: "Unit - ForgeHeart: HeraldOfTzeentch_ForgeHeart"
  sources: "Vendor - LiegeChapter4_VendorTable_Base 118PF"
}
weapon {
  guid: "d891b6e2ca284b32aa5cfeafb07bdd29"
  blueprint_name: "StaffOfTheRigheousPyre_Item"
  name_shared_key: "9cf23550-96c8-49fd-9f80-cb42a7f6a21f"
  name: "Staff of the Righteous Pyre"
  description_shared_key: "b3f0e921-f4bd-40d8-81c6-df76b65952ee"
  description: "The wielder of this staff (power level 15) gains the <b>Emperor\'s Wrath</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} and healing of this power.\\nSanctic {g|Encyclopedia:PsykerPowersGlossary}psychic powers{/g} (including all versions of <b>Emperor\'s Wrath</b>) heal allies instead of damaging them.\\n<indent=5%>+20 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>\\n<indent=5%>+10 {g|Encyclopedia:WarhammerFellowship}Fellowship{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 16
  max_damage: 21
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Sanctic_Weapon_EmperorsWrath_Ability"
    ability_bp: "560aa7c658a441df8bb4b2f9f431064b"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "Sanctic_Weapon_EmperorsWrath_AbilityHeroic"
    ability_bp: "bdde427505b14cd68b20ab0d915d5fe3"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "Sanctic_Weapon_EmperorsWrath_AbilityDesperate"
    ability_bp: "7039f3b35fc5487e9b6c64909062ea04"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "a6a38016b90148878593d977d96b8264"
    bp_name: "SancticBaseFeature"
  }
  extra_fact: "98a981e836d7416bbd498d09797b78ce"
  extra_fact: "1ca44da780fa430abfa92202f3a3602d"
  extra_fact: "f64e4630969247b0a5763292050850cb"
  extra_fact_name: "Willpower20_Feature"
  extra_fact_name: "Fellowship10_Feature"
  extra_fact_name: "StaffOfTheRigheousPyre_Feature"
  sources: "Unit - ExportedPregens: Heinrix_level47_Gamescom2024_ExportedPregen"
  sources: "Vendor - DrusianChapter4_VendorTable_Base 97PF"
}
weapon {
  guid: "a9edcbb807094b1ea7a982314251f409"
  blueprint_name: "StaffOfUnseenChains_Item"
  name_shared_key: "c8402e10-9824-4dca-a120-a1a081e008a5"
  name: "Staff of Unseen Chains"
  description_shared_key: "e58d699a-173a-42ce-a916-ee210b36e61a"
  description: "The wielder of this staff (power level 12) gains the <b>Bind</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}Damage{/g} of this power. The first telekinesis power used by the wielder each {g|Encyclopedia:Turn}turn{/g}, does not increase the {g|Encyclopedia:VeilThickness}veil degradation{/g}.\\n<indent=5%>+15 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 16
  max_damage: 21
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "TelekinesisWeaponBindAbility"
    ability_bp: "8c23fa35c325419a817aae4bdca2a67b"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "TelekinesisWeaponBindAbilityHeroic"
    ability_bp: "9edd0e95bfea4532b764920a7b7f67bf"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "TelekinesisWeaponBindAbilityDesperate"
    ability_bp: "80fac3e0f5f54316ab6e10d6268969d2"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "3a12f16f99fa4d89981d0625a91c98da"
    bp_name: "Telekinesis_Base_Feature"
  }
  extra_fact: "a5038c9866404df58f22b175262a2989"
  extra_fact_name: "Willpower15_Feature"
}
weapon {
  guid: "2d89e66dde2b47b3ac0519dffc542bae"
  blueprint_name: "TelekineticistsStaff_Item"
  name_key: "3aa42f8f-6780-4e7d-a4d9-9e087c6dc9b0"
  name: "Telekineticist\'s Staff"
  description_key: "833b8f70-c5b9-4faa-8043-ed0721d9db0b"
  description: "The wielder of this staff (power level 9) gains the <b>Bind</b> {g|Encyclopedia:Ability}ability{/g}. This ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power.\\n<indent=5%>+10 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "TelekinesisWeaponBindAbility"
    ability_bp: "8c23fa35c325419a817aae4bdca2a67b"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "TelekinesisWeaponBindAbilityHeroic"
    ability_bp: "9edd0e95bfea4532b764920a7b7f67bf"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "TelekinesisWeaponBindAbilityDesperate"
    ability_bp: "80fac3e0f5f54316ab6e10d6268969d2"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "3a12f16f99fa4d89981d0625a91c98da"
    bp_name: "Telekinesis_Base_Feature"
  }
  extra_fact: "b6444939f07e458886eb4f5eb62667e7"
  extra_fact_name: "Willpower10_Feature"
}
weapon {
  guid: "49aaaa5ff4c84a479390becd15d70504"
  blueprint_name: "TelepathsStaff_Item"
  name_key: "5569bcae-bf97-44f9-a35d-354b11a346eb"
  name: "Telepath\'s Staff"
  description_key: "4f7666f1-ce6b-46db-ab95-1aa3fc262e3e"
  description: "The wielder of this staff (power level 9) gains the <b>Vision of Death</b> {g|Encyclopedia:Ability}ability{/g}. The ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. Power level affects the {g|Encyclopedia:DamageGlossary}damage{/g} of this power.\\n<indent=5%>+10 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "ForceSword_AbilityFXSettings"
    fx_bp: "02a6e061e3464785a0ed3d3f4e7ff41a"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbility"
    ability_bp: "5a328c19cc214780b878be2183550910"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbilityHeroic"
    ability_bp: "5b19d80b3d694f77b84c2b38a04efe8f"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  ability4 {
    type: Custom
    ability_bp_name: "TelepathyWeaponVisionOfDeathAbilityDesperate"
    ability_bp: "8986fa989c474068b160ab1af21d763c"
    fx_bp_name: "AssailAbility_AbilityFXSettings"
    fx_bp: "0cd3c32a98ad40349ed6db9fa5c7b49f"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: false
    bp: "c074bd8a210743f48cbb536e3c7c677f"
    bp_name: "Telepathy_Base_Feature"
  }
  extra_fact: "b6444939f07e458886eb4f5eb62667e7"
  extra_fact_name: "Willpower10_Feature"
  sources: "Unit - ExportedPregens: 4y6_Idira_22lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: 4y6_Idira_22lvl_PetRaven_ExportedPregen"
  sources: "Unit - ExportedPregens: 4y6_Idira_27lvl_ExportedPregen_ExportedPregen"
  sources: "Unit - ExportedPregens: Gusev_Idira_26lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: IdiraCompanion_Level_27_Overseer"
  sources: "Unit - ExportedPregens: Sayonara_23_Idira_ExportedPregen"
  sources: "Unit - ExportedPregens: zin_22_IdiraCompanion_ExportedPregen"
  sources: "Vendor - LiegeChapter2_VendorTable_Base 20PF"
}
weapon {
  guid: "714bca98165b4b18b626b26ebf1f05b0"
  blueprint_name: "WraithBoneStaff_Item"
  name_shared_key: "bd17e94b-211f-4410-8ffb-a5accb078b09"
  name: "Singing Spear"
  description_shared_key: "c9d1ee3a-fbd7-45ad-b432-141286e089b6"
  description: "The wielder of this staff gains the <b>Consign</b> {g|Encyclopedia:Ability}ability{/g}. This ability is also available in its {g|Encyclopedia:HeroicAct}heroic act{/g} and {g|Encyclopedia:DesperateMeasure}desperate measure{/g} versions. The wielder\'s divination {g|Encyclopedia:PsykerPowersGlossary}psychic powers{/g} have a 50% chance not to increase {g|Encyclopedia:VeilThickness}veil degradation{/g}.\\n<indent=5%>+15 {g|Encyclopedia:WarhammerWillpower}Willpower{/g}</indent>\\n<indent=5%>+10 {g|Encyclopedia:WarhammerPerception}Perception{/g}</indent>"
  category: Melee
  family: Primitive
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 8
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "MacesMeleeAttack_Ability"
    ability_bp: "638cd0973175462b9faaeb1242761d32"
    fx_bp_name: "Axe_AbilityFXSettings"
    fx_bp: "612936da5a8948ccab3ac067e5d45144"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "Divination_Weapon_Consign_Ability"
    ability_bp: "26787468defa42598581625e2164ffd8"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 0
  }
  ability3 {
    type: Custom
    ability_bp_name: "Divination_Weapon_Consign_AbilityHeroic"
    ability_bp: "1598fb26e644442098e72562537ae660"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 0
  }
  ability4 {
    type: Custom
    ability_bp_name: "Divination_Weapon_Consign_AbilityDesperate"
    ability_bp: "4e6482c67f0548668107514fd187dadd"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 0
  }
  fact_requirement {
    all: true
    negate: false
    bp: "196d258a786c42e68eb4a468efb0089e"
    bp: "395a77ff6fd344f5b8b4a0cc0def06dc"
    bp_name: "Divination_Base_Feature"
    bp_name: "UnsanctionedPsyker"
  }
  extra_fact: "a5038c9866404df58f22b175262a2989"
  extra_fact: "edb2e208ba52466c94d7e9524d45c12c"
  extra_fact: "d3cc01fccb474748ad5fcd2e9b1a9104"
  extra_fact_name: "Willpower15_Feature"
  extra_fact_name: "Perception10_Feature"
  extra_fact_name: "WraithBoneStaff_Feature"
  sources: "Unit - DLC1_Ch02_AstropathicChapel: IdiraPsyker_Chaos_AstropathicChapelCH2"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldEldarSeer_Muaran"
  sources: "Unit - ExportedPregens: IdiraCompanion_lvl38_treasureworld_ExportedPregen"
  sources: "Unit - ExportedPregens: IdiraCompanion_lvl38_treasureworld_PetRaven_ExportedPregen"
  sources: "Unit - ExportedPregens: idira_lv38_chordafight_ExportedPregen"
}

