# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "62f65e161ace4e49bc00f3247d92cda5"
  blueprint_name: "HexrifleT1CH2_Item"
  name_key: "29a5caa2-46e8-4083-867c-50d725b984b1"
  name: "[Mezoa-Pattern] Hexrifle"
  description_shared_key: "c4f2dd90-3553-4c96-9d4b-dfb15f796665"
  description: "When this shot {g|Encyclopedia:HitSequenceGlossary}hits{/g}, it poisons the target with a viral {g|Encyclopedia:ToxinEffect}toxin{/g} for 3 {g|Encyclopedia:Round}rounds{/g} if the enemy fails a {g|Encyclopedia:WarhammerToughness}Toughness{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g}."
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 18
  max_damage: 28
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 25
  recoil: 10
  max_range: 30
  ammo: 5
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SplinterRifle_SingleShot_Ability"
    ability_bp: "3fbac3a9c61742d790e0a76ea43faefd"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShotSplinterRifle_Ability"
    ability_bp: "083b3e6ce885487089638ca969070c03"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "b5fe044e47604f47bf99ebd14440b579"
    bp_name: "DrukhariWeaponProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "53f2c6910b124dc3889608e3eb0cd2ee"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "ViralToxin_Power6_ForWeapon_Feature"
  sources: "Vendor - LiegeChapter2_VendorTable_Base 66PF"
}
weapon {
  guid: "00f9917c1bec4a1daea7a5ceeae36d76"
  blueprint_name: "Hexrifle_Item"
  name_key: "1fd2fa8d-053f-4f61-ba0a-9c9036786296"
  name: "Hexrifle"
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 22
  max_damage: 25
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 25
  recoil: 10
  max_range: 30
  ammo: 5
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SplinterRifle_SingleShot_Ability"
    ability_bp: "3fbac3a9c61742d790e0a76ea43faefd"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShotSplinterRifle_Ability"
    ability_bp: "083b3e6ce885487089638ca969070c03"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "b5fe044e47604f47bf99ebd14440b579"
    bp_name: "DrukhariWeaponProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "53f2c6910b124dc3889608e3eb0cd2ee"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "ViralToxin_Power6_ForWeapon_Feature"
  sources: "Unit - Ch02_SantielsPrideUnderhive: DrukhariAcothyst"
  sources: "Unit - Ch03_CommorraghArena: DrukhariProselyte_Ranged_Portals"
  sources: "Unit - Ch02_SantielsPride: WrackLeader"
  sources: "Unit - Ch03_CommorraghArena: CommorraghArenaAchilleasWrack"
  sources: "Unit - Ch03_CommorraghArena: CommorraghArenaWrack"
  sources: "Unit - Ch03_Prison: WrackServant"
  sources: "Unit - Ch03_Prison: WrackServantNoName"
}
weapon {
  guid: "778ad38329514c87bb1205dea466fc2e"
  blueprint_name: "HuntingRifle_Item"
  name_key: "e37a175f-b347-4e3f-ae17-35ad91e1d5f4"
  name: "Hunting Rifle"
  description_key: "77bb0af2-1a2c-4664-9cda-7bf8188465d1"
  description: "{g|Encyclopedia:DeadeyeShot}Deadeye shots{/g} fired by this rifle deal additional {g|Encyclopedia:DamageGlossary}damage{/g} to larger enemies:\\n-<indent=5%>Hulking creatures (2\303\2272 cells) suffer +5 damage.</indent>\\n-<indent=5%>Enormous creatures (3\303\2273 cells) suffer +10 damage.</indent>\\n-<indent=5%>Massive creatures (4\303\2274 cells) suffer +15 damage.</indent>"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 20
  max_damage: 26
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 40
  recoil: 0
  max_range: 22
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "PlasmaRifle_SingleShot_AbilityFXSettings"
    fx_bp: "c4955f13ac1f4f37bc9f59b792e94366"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "957dced3e6af4465aa0943eee997f99d"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "HuntingRifle_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldRebelHunter"
  sources: "Unit - Ch02_Lair3: Lair3RebelSniper"
  sources: "Unit - Ch02_Lair4_TheLure: Lair4EndlessCombat"
  sources: "Unit - ExportedPregens: 4y6_Sniper_27lvl_ExportedPregen_ExportedPregen"
  sources: "Unit - ExportedPregens: Gusev_RT_26lvl_ExportedPregen"
}
weapon {
  guid: "9f1781a8ab2b41c1be7c1689f4aab9b7"
  blueprint_name: "HuntingSharpshooterRifle_Item"
  name_key: "d3232b10-4b88-46be-8ad3-26c612dee42b"
  name: "Sharpshooter Rifle"
  description_key: "77bb0af2-1a2c-4664-9cda-7bf8188465d1"
  description: "{g|Encyclopedia:DeadeyeShot}Deadeye shots{/g} fired by this rifle deal additional {g|Encyclopedia:DamageGlossary}damage{/g} to larger enemies:\\n-<indent=5%>Hulking creatures (2\303\2272 cells) suffer +5 damage.</indent>\\n-<indent=5%>Enormous creatures (3\303\2273 cells) suffer +10 damage.</indent>\\n-<indent=5%>Massive creatures (4\303\2274 cells) suffer +15 damage.</indent>"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 24
  max_damage: 36
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 40
  recoil: 0
  max_range: 22
  ammo: 3
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "PlasmaRifle_SingleShot_AbilityFXSettings"
    fx_bp: "c4955f13ac1f4f37bc9f59b792e94366"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "957dced3e6af4465aa0943eee997f99d"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "HuntingRifle_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - CR0: ReavingTempestSpire_GoodLoot03"
  sources: "Unit - CassiaCompanion: CassiaCompanion_Ch04_TrueStart"
  sources: "Unit - ExportedPregens: PlayerRT_Level38_ArbitratorOfficer_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level38_OfficerOverseer_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level38_OperativeOverseer_ExportedPregen"
  sources: "Unit - YrlietCompanion: YrlietCompanion_Ch03_TrueStart"
}
weapon {
  guid: "a223f91296d24d65a3390651c247ed83"
  blueprint_name: "JaeQuest_AeldariRiflePlaceholder_Item"
  name_key: "b5a5da06-ef7a-42ca-bc25-8cc1550f42a8"
  name: "Wanderer\'s Portent"
  description_key: "deb92c50-11d8-4e23-9e68-02264112247a"
  description: "This rifle can only perform {g|Encyclopedia:DeadeyeShot}deadeye shot{/g} attacks. Whenever the wielder scores a critical {g|Encyclopedia:HitSequenceGlossary}hit{/g} with a {g|Encyclopedia:SingleRangedAttacksGlossary}single-shot{/g} attack, they gain an additional attack this {g|Encyclopedia:Turn}turn{/g}."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 20
  max_damage: 25
  penetration: 20
  dodge_reduction: 30
  additional_hit_chance: 20
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "AeldariScoutLongRifle_PreciseShot_Ability"
    ability_bp: "7315f74b9a084b1d804caa90e9a26f47"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "261abe4b20f54a75aab43232a4457cb4"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "JaeQuest_AeldariRiflePlaceholder_Feature"
  sources: "Chest - Test: TestRaritiesLoot"
  sources: "Unit - ExportedPregens: 4y6_Yrliet_22lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: 4y6_Yrliet_27lvl_ExportedPregen_ExportedPregen"
  sources: "Unit - ExportedPregens: 4y6_Yrliet_41lvl_ExportedPregen_ExportedPregen"
}
weapon {
  guid: "4027957aa0bb430091cf555d3d09052f"
  blueprint_name: "LasblasterT2_Item"
  name_shared_key: "7d9c2e71-3639-41ad-b650-d1a7e8262062"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 25
  max_damage: 40
  penetration: 20
  dodge_reduction: 30
  additional_hit_chance: 25
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
}
weapon {
  guid: "6810bc819d164a7c9dd035c8dca82894"
  blueprint_name: "Lasblaster_Item"
  name_shared_key: "37a548ea-fa4e-4780-b4f9-cc7e9fc9e61b"
  name: "Lasblaster"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 23
  max_damage: 34
  penetration: 20
  dodge_reduction: 30
  additional_hit_chance: 25
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Chest - CR33: Drukhari_AngerChest"
  sources: "Unit - YrlietCompanion: YrlietCompanion_Ch04_TrueStart"
}
weapon {
  guid: "1b43f185a35545f7a161e444538f2178"
  blueprint_name: "LonglasExitus_Item"
  name_shared_key: "020caf8c-4600-440a-9a64-66754fa4069f"
  name: "Exitus Longlas"
  description_shared_key: "96ab3048-c5e9-46c6-b7d3-b1ccd23c0ba2"
  description: "Grants +25% {g|Encyclopedia:HitSequenceGlossary}hit chance{/g}. If the wielder has at least {g|Encyclopedia:SoulMarkHope}Iconoclast{/g} \342\200\224 Zealot, {g|Encyclopedia:DamageGlossary}damage{/g} is increased by +{uip|Damage|3188b332a5044c73964b85b1e07438ad}."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 40
  max_damage: 60
  penetration: 30
  dodge_reduction: 30
  additional_hit_chance: 50
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "LonglasShot_Cutscene_AbilityFXSettings"
    fx_bp: "23a01c850d7c43158febbcdddaa07ceb"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "2e4863e8493844da8065f8239cec4f5b"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "LonglasExitusApply_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Chest - CR0: AdeptusMechanicus_necron_container_01 (7)_loot_object"
}
weapon {
  guid: "6679bda02e994ebb96710a52ce27e3a2"
  blueprint_name: "LonglasT2CH04_Item"
  name_shared_key: "33f82e92-169e-4647-851e-268dce88f4e6"
  name: "Longlas"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 33
  max_damage: 49
  penetration: 25
  dodge_reduction: 30
  additional_hit_chance: 25
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 150PF"
}
weapon {
  guid: "05159922d36a4018bdcab94a4a3f979c"
  blueprint_name: "Longlas_Item"
  name_shared_key: "33f82e92-169e-4647-851e-268dce88f4e6"
  name: "Longlas"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 14
  max_damage: 20
  penetration: 15
  dodge_reduction: 30
  additional_hit_chance: 25
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Chest - CR0: Forest_ArmoryLoot (1)"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CultistMarksman"
  sources: "Unit - Ch03_CommorraghArena: ArenaGladiator3"
  sources: "Unit - Ch03_CommorraghArena: ArenaGladiator4"
  sources: "Unit - Ch03_CommorraghArena: ArenaGladiator5"
  sources: "Unit - Units: BoardedShip_Pirate_Sniper_Elite_Unit"
  sources: "Unit - Companions: CompanionCassiaPrototype"
  sources: "Unit - Companions: CompanionIdiraPrototype"
  sources: "Unit - ExportedPregens: 4y6_Sniper_22lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: CassiaCompanion_Level22_NeiliusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: CassiaCompanion_Level28_TesseraParty_ExportedPregen"
  sources: "Unit - ExportedPregens: CassiaCompanion_Level39_SolarParty_ExportedPregen"
  sources: "Unit - ExportedPregens: IdiraCompanion_Level19_HarmonParty_ExportedPregen"
  sources: "Unit - ExportedPregens: IdiraCompanion_Level39_PetRaven"
  sources: "Unit - ExportedPregens: IdiraCompanion_Level39_SolarParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT19Chapel_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level7_EtelParty_ExportedPregen"
  sources: "Unit - ExportedPregens: RT10CSM_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_23_GG_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_RT_23lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: VasiliyRt_15LvL_ExportedPregen"
  sources: "Unit - ExportedPregens: Yanus19RTT_ExportedPregen"
}
weapon {
  guid: "84da0da3f9464f36979d8e2c4f0b3682"
  blueprint_name: "LongRifleRelic_Item"
  name_shared_key: "67c9f648-30ae-4e7a-a5b1-a50782b37617"
  name: "Dream\'s Infinity"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 19
  max_damage: 22
  penetration: 20
  dodge_reduction: 30
  additional_hit_chance: 20
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Chest - VoidshipCrypt: Loot_SecretRoom_N2_Arsenal"
}
weapon {
  guid: "77e85ede7a21491caade41b481ae5160"
  blueprint_name: "LongRifleT1CH2_Item"
  name_key: "5978d211-c753-43cc-9fd9-5c0c7cb9bb04"
  name: "[Mezoa-Pattern] Long Rifle"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 22
  max_damage: 32
  penetration: 20
  dodge_reduction: 30
  additional_hit_chance: 20
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
}
weapon {
  guid: "c8c2bdcf4a8c49a398db939a3b160787"
  blueprint_name: "LongRifleT2_Item"
  name_key: "498b9da2-86dd-4a27-a5ee-236c3efab187"
  name: "Guardian Long Rifle"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 45
  penetration: 35
  dodge_reduction: 30
  additional_hit_chance: 20
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Unit - Ch04_Quetza-al_khet: Quetza_EldarRangerHard"
  sources: "Unit - Ch04_Quetza-al_khet: Quetza_EldarRangerNew"
}
weapon {
  guid: "db96ff8975434c40b78705377291ff4e"
  blueprint_name: "LongRifle_Item"
  name_key: "963c236e-78a2-40ea-af8c-0c6f3d43a0b9"
  name: "Aeldari Long Rifle"
  description_shared_key: "694f2b9a-ff8e-4e5f-b944-6f7a3d166a81"
  description: "<i>Laser weapons are effective against targets in {g|Encyclopedia:DetailsOfTheCoverGlossary}cover{/g} and targets with high {g|Encyclopedia:DodgeGlossary}dodge{/g}.</i>"
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 18
  max_damage: 21
  penetration: 20
  dodge_reduction: 30
  additional_hit_chance: 20
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Chest - CR33: ImperiumMilitary_PrisonPitTrashWeapon"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldEldarCutscene"
  sources: "Unit - Ch02_AgriWorldJungle: Yrliet_JungleWorldNPC"
  sources: "Unit - Ch02_AgriWorldTown: EldarCompanionNPC_Town"
  sources: "Unit - Ch02_AgriWorldTown: EldarCompanionNPC_TownBaked"
  sources: "Unit - Companions: CompanionYrlietPrototype"
  sources: "Unit - ExportedPregens: 4y6_Yrliet_22lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: 4y6_Yrliet_27lvl_ExportedPregen_ExportedPregen"
  sources: "Unit - ExportedPregens: Gusev_Yrliet_26lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: YrlietCompanion_Level22_NeiliusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: YrlietCompanion_Level25_MikandraParty_ExportedPregen"
  sources: "Unit - ExportedPregens: YrlietCompanion_Level27_CyrusParty_ExportedPregen"
  sources: "Unit - YrlietCompanion: YrlietCompanion"
  sources: "Unit - YrlietCompanion: YrlietCompanion_Ch02_TrueMid"
}
weapon {
  guid: "57c6247ab74e4d93b36cbfe55d508a0f"
  blueprint_name: "MarksmanRifle_Item"
  name_key: "f6a8fd0a-3fea-4985-81a6-e81247566d54"
  name: "Marksman Rifle"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 21
  max_damage: 25
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 20
  recoil: 0
  max_range: 30
  ammo: 5
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldRebelSniper"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverSniper_Ranged_Hard"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditHeavySniperQS"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditSniper"
  sources: "Unit - Ch02_FootFallSlums: FootfallQuarantineSniper"
  sources: "Unit - Ch02_FootFallSlums: Footfall_Generic_BanditSniper"
  sources: "Unit - Ch02_ForgeWorldSpaceHulk: SpaceHulk_MadLogos"
  sources: "Unit - Ch02_PascalEvent: Tarzus_Skitarii_Ranged"
  sources: "Unit - Ch02_RandomEncounters: PossessedSniperRandomEncounter"
  sources: "Unit - Ch02_SantielsPrideUnderhive: WildCannibalRange"
  sources: "Unit - Ch02_AgriWorldTown: CutsceneSniper"
  sources: "Unit - Ch02_ForgeWorldAndHeart: AssassinTechpriest"
  sources: "Unit - Ch02_ForgeWorldAndHeart: DoorLockerTechpriest1"
  sources: "Unit - Ch02_ForgeWorldAndHeart: DoorLockerTechpriest2"
  sources: "Unit - Ch02_ForgeWorldSpaceHulk: MadTechPriestLogi"
  sources: "Unit - ExportedPregens: 4y6_Sniper_22lvl_ExportedPregen"
}
weapon {
  guid: "9f1b9631aaf74730907aa6296f6f29f7"
  blueprint_name: "NeedleRifleT1CH02_Item"
  name_shared_key: "1e7ae4dd-a6b9-4ab8-94aa-3b71377a1964"
  name: "Needle Rifle"
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 12
  max_damage: 17
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 10
  recoil: 10
  max_range: 36
  ammo: 5
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SplinterRifle_SingleShot_Ability"
    ability_bp: "3fbac3a9c61742d790e0a76ea43faefd"
    fx_bp_name: "NeedlePistol_Shot_AbilityFXSettings"
    fx_bp: "eb9add1695f14d73bffd427b74d4dff0"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShotSplinterRifle_Ability"
    ability_bp: "083b3e6ce885487089638ca969070c03"
    fx_bp_name: "ShurikenCatapult_Shot_AbilityFXSettings"
    fx_bp: "0f7a77cad3f646838be3ca4ccfdc9939"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "ShurikenCatapult_Shot_AbilityFXSettings"
    fx_bp: "0f7a77cad3f646838be3ca4ccfdc9939"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "53f2c6910b124dc3889608e3eb0cd2ee"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "ViralToxin_Power6_ForWeapon_Feature"
  sources: "Unit - DLC1_CH02_OfficersDeck_Kelemorph: Neofit_Ranged_Common"
}
weapon {
  guid: "447c8afcacb446ad9d19a48527861a27"
  blueprint_name: "NeedleRifle_Item"
  name_shared_key: "1e7ae4dd-a6b9-4ab8-94aa-3b71377a1964"
  name: "Needle Rifle"
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 15
  max_damage: 23
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 10
  recoil: 10
  max_range: 36
  ammo: 5
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SplinterRifle_SingleShot_Ability"
    ability_bp: "3fbac3a9c61742d790e0a76ea43faefd"
    fx_bp_name: "NeedlePistol_Shot_AbilityFXSettings"
    fx_bp: "eb9add1695f14d73bffd427b74d4dff0"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShotSplinterRifle_Ability"
    ability_bp: "083b3e6ce885487089638ca969070c03"
    fx_bp_name: "ShurikenCatapult_Shot_AbilityFXSettings"
    fx_bp: "0f7a77cad3f646838be3ca4ccfdc9939"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "ShurikenCatapult_Shot_AbilityFXSettings"
    fx_bp: "0f7a77cad3f646838be3ca4ccfdc9939"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "53f2c6910b124dc3889608e3eb0cd2ee"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "ViralToxin_Power6_ForWeapon_Feature"
  sources: "Chest - CR0: Forest_EldarRifle"
  sources: "Unit - ExportedPregens: Gusev_Cassia_26lvl_ExportedPregen"
}
weapon {
  guid: "69748c23aa1c4adca0c27de877f4ab34"
  blueprint_name: "SniperRifleT1Tutorial_Item"
  name_key: "1023bc58-4a31-4460-8c1e-223293616a77"
  name: "Well-Maintained Sniper Rifle"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 12
  max_damage: 17
  penetration: 15
  dodge_reduction: 10
  additional_hit_chance: 30
  recoil: 0
  max_range: 30
  ammo: 5
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - VoidshipOfficersDeck: ImperiumMilitary_PrologueOD_CorridorChestAdept"
  sources: "Unit - ExportedPregens: CassiaCompanion_Level7_EtelParty_ExportedPregen"
}
weapon {
  guid: "c8f3d4d57f6b490d8b55aa5a7ca7acca"
  blueprint_name: "SniperRifleT2CH4_Item"
  name_shared_key: "3dfaf161-4c20-4cf2-a4ba-5897b08cf76e"
  name: "[Retobi-Pattern] Sniper Rifle"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 26
  max_damage: 39
  penetration: 20
  dodge_reduction: 10
  additional_hit_chance: 30
  recoil: 0
  max_range: 30
  ammo: 5
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - Ch04_ForgeHeart: CorruptedSkitarii_Ranged"
  sources: "Unit - Ch04_SalisPrine_ItsTime: ItsTime_MarauderSniper"
  sources: "Unit - Ch04_VoidshipBridgeBoarding: InquisitorSniper_Ranged_Boarding"
  sources: "Unit - DLC1_LowerTunnel: DLC1_HighFactotum_LowerTunnels_SF"
  sources: "Unit - ExportedPregens: Cassia_level47_Gamescom2024_ExportedPregen"
}
weapon {
  guid: "bb427b937c304ece913793a020aea87f"
  blueprint_name: "SniperRifleT2_Item"
  name_key: "6b0841db-1930-40a9-b2e5-e4f365b19fa2"
  name: "Rebel\'s Sniper Rifle"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 18
  max_damage: 25
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 30
  recoil: 0
  max_range: 30
  ammo: 5
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - Ch02_VoidshipTemple: GenestealerSniper_Ranged_VoidshipTempleAmbush"
  sources: "Unit - Ch04_LowerTunnel: GenestealerSniper_Ranged_LowerTunnels"
  sources: "Unit - Ch01_Starport: StarportRebelLeaderSniper"
  sources: "Unit - Ch04_ForgeHeart: CorruptedSkitariiSwarm_Ranged_ForgeHeart"
  sources: "Unit - DLC1_Ch02_VoidshipCrypt: Enforcers_Ranged_VoidshipCrypt"
  sources: "Unit - DLC1_Ch02_VoidshipCrypt: GenestealerSniper_Ranged_VoidshipCrypt"
  sources: "Unit - DLC1_LowerTunnels_StreetFight: Enforcers_Ranged_VoidshipCrypt1"
  sources: "Unit - ExportedPregens: 4y6_Sniper_27lvl_ExportedPregen_ExportedPregen"
  sources: "Unit - ExportedPregens: Idira19Chapel_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level22_NeiliusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level29_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_Level42_OlegParty_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_23_GG_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_RT_23lvl_ExportedPregen"
  sources: "Unit - ExportedPregens: zin_22_RT_Operative_ExportedPregen"
}
weapon {
  guid: "a5130a7096a546bf883574db563c4c57"
  blueprint_name: "SniperRifle_Item"
  name_shared_key: "4db42c2c-709f-4318-8061-619485b70ba9"
  name: "Sniper Rifle"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 12
  max_damage: 16
  penetration: 15
  dodge_reduction: 10
  additional_hit_chance: 30
  recoil: 0
  max_range: 30
  ammo: 5
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - CR0: Lair3Chest3"
  sources: "Chest - CR33: ImperiumMilitary_PrisonPitTrashWeapon"
  sources: "Unit - Ch01_ArcheotechReactor: IronCultist_ArcheotechReactor_Range"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Sniper"
  sources: "Unit - Ch01_Starport: StarportRebelSniper"
  sources: "Unit - Ch01_Starport: StarportRebelSniper_dlc"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsRebelSniper"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsRebelSniper_withLoot"
  sources: "Unit - Ch02_FootFallAtrium: FootfallAnverSniper_Ranged_Elite"
  sources: "Unit - Ch02_FootFallAtrium: FootfallPirateSniper"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditRingleaderSniper"
  sources: "Unit - Ch02_FootFallSlums: Footfall_Generic_BanditLeaderSniper"
  sources: "Unit - DLC1_Ch02_AstropathicChapel: Sniper_AstropathicChapelCH2"
  sources: "Unit - Ch02_ForgeWorldAndHeart: VeteranAssassinTechpriest"
  sources: "Unit - Ch02_ForgeWorldSpaceHulk: MadTechPriest_Technomat"
  sources: "Unit - Companions: CompanionJaePrototype"
  sources: "Unit - AbelardCompanion: AbelardCompanion_Gamescom"
  sources: "Unit - ExportedPregens: CassiaCompanion_Level15_ExportedPregen"
  sources: "Unit - ExportedPregens: JaeCompanion_Level39_SolarParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PascalCompanion_Level15_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT19ChapelPsyker_ExportedPregen"
  sources: "Unit - IdiraCompanion: IdiraCompanion"
  sources: "Unit - IdiraCompanion: IdiraCompanion_Gamescom"
  sources: "Unit - IdiraCompanion: IdiraCompanion_TrailerCinematic"
  sources: "Unit - IdiraCompanion: PC_Human_ChordaCompanion_F_HM"
}
weapon {
  guid: "e1de396a86f74948811040c0f35e20fa"
  blueprint_name: "Stubcarbine_Item"
  name_key: "33e7b2f6-82d5-4bb0-b922-9ca32f5de2e8"
  name: "Stubcarbine"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 12
  max_damage: 18
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 10
  max_range: 18
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "SolidProjectile_Shot_AbilityFXSettings"
    fx_bp: "38a747f2fafc4789ae7610c3b562bdbe"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - CR4: AdeptusMechanicus_TaintedStreets_GoodLoot07"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsRebelRangedLong"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverKnivesOutLeutenant_MeleeRanged_Common"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverKnivesOutLeutenant_MeleeRanged_CommonQS"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditHeavy"
  sources: "Unit - Ch02_FootfallDock: FootfallBanditKnivesOut_AnverLair_Ranged"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedSkitariiAlphaAuto_Ranged"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedSkitariiAuto_Ranged"
  sources: "Unit - Ch02_PascalEvent: TarzusTechPriestStubcarbine_Technomat_Adept"
  sources: "Unit - Ch02_PascalEvent: TarzusTechPriestStubcarbine_Technomat_AdeptTactical"
  sources: "Unit - Ch02_PascalEvent: TarzusTechPriestStubcarbine_Technomat_Hunter"
  sources: "Unit - Ch01_JailPlanetoid: JailPlanetoid_Ewain"
  sources: "Unit - Ch02_ForgeWorldSpaceHulk: MadTechPriestStubcarbine_Technomat"
  sources: "Unit - SideQuest: CultistPsyker_SororitasQuest_Ranged"
  sources: "Unit - Units: BoardedShip_Pirate_Gunner_Hard_Unit"
  sources: "Unit - ExportedPregens: IdiraCompanion_Level15_ExportedPregen"
}
weapon {
  guid: "b4fb3bd9360f48498763714078a8133e"
  blueprint_name: "BloodblightHexrifleItem"
  name_key: "cb4380fa-c6d2-4653-8b8e-5017b5eb4ff3"
  name: "Bloodblight Hexrifle"
  description_key: "b0b947b9-d4a5-4b04-b04a-3ba0df692859"
  description: "Attacks of this rifle inflict the bloodblight effect on the target.\\n<i>Bloodblight:</i> at the beginning of the target\'s {g|Encyclopedia:Turn}turn{/g} all creatures in a 2-cell radius suffer the bloodblight effect. If these creatures suffer impact, piercing, or {g|Encyclopedia:RendingDamage}rending damage{/g}, they also suffer an additional +4 {g|Encyclopedia:DirectDamage}direct damage{/g} and {g|Encyclopedia:BleedingEffect}bleeding{/g} (4)."
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 22
  max_damage: 30
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 20
  recoil: 10
  max_range: 30
  ammo: 5
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SplinterRifle_SingleShot_Ability"
    ability_bp: "3fbac3a9c61742d790e0a76ea43faefd"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShotSplinterRifle_Ability"
    ability_bp: "083b3e6ce885487089638ca969070c03"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "b5fe044e47604f47bf99ebd14440b579"
    bp_name: "DrukhariWeaponProficiencyFeature"
  }
  extra_fact: "b3f6ad202d1348539330d616ca15ea53"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "0f511a70cfdc4282ae3dc14113b4da0c"
  extra_fact_name: "BloodblightHexrifleFeature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "ViralToxin_Power8_ForWeapon_Feature"
  sources: "Unit - Ch03_CommorraghArena: DrukhariBeastmaster_MeleeRanged_ArenaFiend"
}
weapon {
  guid: "d043a2289a1f45f784a415057c725cb5"
  blueprint_name: "AeldariScout_LongRifle_Item"
  name_shared_key: "9fe0de4c-8ecc-48d6-940b-c9522aacc223"
  description_key: "ea0a1852-ba4b-43f7-80fb-e3bbde001140"
  description: "Grants +5 {g|Encyclopedia:MovementPoints}MP{/g} after each attack and allows the wielder to move after attacking. If an attack with this weapon {g|Encyclopedia:HitSequenceGlossary}hits{/g} 3 or more targets, this attack has no {g|Encyclopedia:Cooldown}cooldown{/g}.\\nThis rifle has +100% {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g}."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 45
  penetration: 35
  dodge_reduction: 30
  additional_hit_chance: 20
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "AeldariScoutLongRifle_SingleShot_Ability"
    ability_bp: "2c566ff745f845b1908ab49800ea4338"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "AeldariScoutLongRifle_PreciseShot_Ability"
    ability_bp: "7315f74b9a084b1d804caa90e9a26f47"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "9975a707cd3e4502947c7ff2967344c3"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "AeldariScout_LongRifle_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Chest - Test: TestRaritiesLoot"
  sources: "Unit - Ch04_Quetza-al_Khet: Quetza-al_Yrliet"
  sources: "Unit - ExportedPregens: 4y6_Yrliet_41lvl_ExportedPregen_ExportedPregen"
  sources: "Unit - ExportedPregens: Sayonara_39lvl_RT_ExportedPregen"
}
weapon {
  guid: "ca50b7f4f1854964963b2bcf73840101"
  blueprint_name: "HeavyLonglas_Item"
  name_shared_key: "33f82e92-169e-4647-851e-268dce88f4e6"
  name: "Longlas"
  description_key: "a4fc51b9-ee64-49b7-96f4-36a2475e0676"
  description: "A {g|Encyclopedia:DeadeyeShot}deadeye shot{/g} from this longlas stuns the target for 1 {g|Encyclopedia:Round}round{/g} if the target fails a {g|Encyclopedia:WarhammerToughness}Toughness{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g}."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 15
  max_damage: 18
  penetration: 15
  dodge_reduction: 30
  additional_hit_chance: 25
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_actions: "248a9ee7cc6e490d86826d77d0686b4f"
    on_hit_action_name: "HeavyLonglas_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
}
weapon {
  guid: "f60145a8ecab427384488ba10eee4637"
  blueprint_name: "LasblasterCH4Unique_Item"
  name_key: "b36a74e7-d9d8-469f-8e83-c6c686d93b03"
  name: "Suin Kaelean"
  description_key: "bed9ccc1-db69-4430-ac51-4eb14f50225f"
  description: "When this weapon {g|Encyclopedia:HitSequenceGlossary}hits{/g}, the target must pass a {g|Encyclopedia:WarhammerToughness}Toughness{/g} {g|Encyclopedia:Test}Test{/g} with a \342\210\22235 {g|Encyclopedia:Penalty}penalty{/g} or become {g|Encyclopedia:BlindedEffect}blinded{/g} for 1 {g|Encyclopedia:Round}round{/g}."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 28
  max_damage: 42
  penetration: 15
  dodge_reduction: 30
  additional_hit_chance: 25
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "10abb59e36064ff0b2299a15db4d7583"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "LasblasterCH4Unique_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Chest - Quetza-al_Khet: Loot_Good_Outpost_TableEldarLoot"
}
weapon {
  guid: "243fbd87bf7c47318362e3ecf8518e62"
  blueprint_name: "LongBarreledSniperRifle_Item"
  name_key: "46961177-f3fc-41f5-81d1-4b629daff940"
  name: "[Mezoa-Pattern] Sniper Rifle"
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 20
  max_damage: 30
  penetration: 20
  dodge_reduction: 10
  additional_hit_chance: 30
  recoil: 0
  max_range: 36
  ammo: 5
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - CassiaCompanion: CassiaCompanion_Ch02_TrueMid"
  sources: "Vendor - LiegeChapter2_VendorTable_Base 56PF"
}
weapon {
  guid: "5cf6c50f53cb4b1b9f98961158654810"
  blueprint_name: "LonglasCH04_Item"
  name_key: "cda52d3b-0e27-41e8-8e73-717e5fbae653"
  name: "Stupor"
  description_key: "bbb6491e-e90b-4549-a8a4-8c9af127c5c8"
  description: "Whenever a {g|Encyclopedia:DeadeyeShot}deadeye shot{/g} from this weapon deals {g|Encyclopedia:CritChancesAndCritDamageGlossary}critical damage{/g}, the target becomes {g|Encyclopedia:Stun}stunned{/g} for 1 {g|Encyclopedia:Turn}turn{/g}."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 45
  penetration: 30
  dodge_reduction: 30
  additional_hit_chance: 25
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "d27d02087b274b05a4f3ab50b6d8183e"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "LongRifleCH04Unique_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Chest - Quetza-al_Khet: Loot_Good_Graves_CommisarArtefact"
  sources: "Unit - ExportedPregens: PascalCompanion_Level47_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerMercenary_Level42_OlegParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_level47_Gamescom2024_ExportedPregen"
}
weapon {
  guid: "9caaa7b9089a4b88aad4c385081ee29d"
  blueprint_name: "LongRifleCH2Unique2_Item"
  name_key: "e936deab-81aa-4a53-aa5c-e9a389ead19f"
  name: "Bane of Sorrow"
  description_key: "61653e4d-b63a-4ac4-bd85-2e684d20f226"
  description: "This rifle deals an additional +33% {g|Encyclopedia:DamageGlossary}damage{/g} to Drukhari enemies."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 22
  max_damage: 32
  penetration: 10
  dodge_reduction: 30
  additional_hit_chance: 20
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 4
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "b961db2cbe074675b4519ca24e2d0b58"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "LongRifleCH2Unique2_Item_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Vendor - LiegeChapter2_VendorTable_Base 62PF"
}
weapon {
  guid: "1344f02029274817a17ced1009fe206c"
  blueprint_name: "LongRifleCH2Unique_Item"
  name_shared_key: "fa3dc9c4-9c66-4ad0-bd15-40c0d1de6977"
  name: "Ynnealith"
  description_shared_key: "ddb7db30-5a81-410d-89f2-46c0db9342d8"
  description: "{g|Encyclopedia:DodgeReduction}<b>Dodge reduction</b>{/g} against Drukhari and Aeldari is increased by +40%."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 25
  max_damage: 28
  penetration: 30
  dodge_reduction: 30
  additional_hit_chance: 20
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "ff866c90646f4850a5364be1c20bd3dc"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "LongRifleCH2Unique_Item_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Unit - YrlietCompanion: YrlietCompanion_Ch04_TrueStart"
  sources: "Vendor - PirateChapter2_VendorTable_Base 56PF"
}
weapon {
  guid: "f5042e3db22b4057b14b0dc49e98e7f4"
  blueprint_name: "NeedleRifleCH2Unique1_Item"
  name_key: "25fd7e2a-6f9b-478e-a7d5-835b269441a8"
  name: "The Roar"
  description_key: "16505f72-1910-493c-9e4a-04a8a4ab7107"
  description: "Targets hit by this rifle are forced to move 2 cells away from the shooter."
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 15
  max_damage: 23
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 10
  recoil: 10
  max_range: 36
  ammo: 5
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SplinterRifle_SingleShot_Ability"
    ability_bp: "3fbac3a9c61742d790e0a76ea43faefd"
    fx_bp_name: "NeedlePistol_Shot_AbilityFXSettings"
    fx_bp: "eb9add1695f14d73bffd427b74d4dff0"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShotSplinterRifle_Ability"
    ability_bp: "083b3e6ce885487089638ca969070c03"
    fx_bp_name: "ShurikenCatapult_Shot_AbilityFXSettings"
    fx_bp: "0f7a77cad3f646838be3ca4ccfdc9939"
    on_hit_actions: "9c7d83b9dee54096b763309cf88179b0"
    on_hit_action_name: "ViralToxin_withCheck0_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "ShurikenCatapult_Shot_AbilityFXSettings"
    fx_bp: "0f7a77cad3f646838be3ca4ccfdc9939"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "b5511030d52c4b0eae0e6c385ce4189d"
  extra_fact: "f556469b5352474c88cf8dfed2b7ee83"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "ViralToxin_Power10_ForWeapon_Feature"
  extra_fact_name: "NeedleRifleCh2Unique1_Feature"
  sources: "Vendor - LiegeChapter2_VendorTable_Base 55PF"
}
weapon {
  guid: "2059b9aeefb24b1fb1072c08b9859439"
  blueprint_name: "Repeater_Longlas_Item"
  name_key: "b90fe2dd-37db-4e1b-9bf1-c20d8c4f8891"
  name: "Deadly Repeater"
  description_key: "78a41318-fee5-4d26-abe6-3f4896c7728c"
  description: "The wielder gains a 30% chance to gain one more attack action after a kill."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 22
  max_damage: 32
  penetration: 15
  dodge_reduction: 30
  additional_hit_chance: 25
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Lasgun_LasShot_AbilityFXSettings"
    fx_bp: "321b0a7923dd49d19c9429ae4721cda2"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "2802344bc7414607b092d7afd5f22dd2"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "Repeater_Longlas_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  sources: "Vendor - ExploratorChapter2_VendorTable_Base 45PF"
}
weapon {
  guid: "7e3f2d1c720240b7a62d7a9d2b709ee1"
  blueprint_name: "SniperRifleCH5Unique_Item"
  name_shared_key: "001bbb99-7166-4adf-bf4a-d030944b4701"
  name: "Gloomrifle"
  description_shared_key: "7f01c09c-ff3e-4777-88ed-441022fec8b4"
  description: "{g|Encyclopedia:DamageGlossary}Damage{/g} from {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g} is always equal to 100%.\\nDeals an additional +{uip|Damage|ad4636f2df894381b0053a052d04129f} damage."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 42
  max_damage: 65
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 40
  recoil: 0
  max_range: 30
  ammo: 5
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "ad4636f2df894381b0053a052d04129f"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SniperRifleCH5Unique_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - CrashedShip: ImperiumMilitary_GoodLoot02"
}
weapon {
  guid: "3983a821be1b4f2f912e1ef6b7d73e86"
  blueprint_name: "SniperRifleMammonthkiller_Item"
  name_key: "a93eeeab-efdf-456a-b2eb-55ab18fe0545"
  name: "Terrorax Slayer"
  description_key: "83609125-35b8-41cd-b946-8eb67cac87ac"
  description: "This rifle\'s {g|Encyclopedia:DeadeyeShot}deadeye shot{/g} costs +1 {g|Encyclopedia:ActionPoints}AP{/g} more and deals triple {g|Encyclopedia:DamageGlossary}damage{/g} against large targets (size 2\303\2272 cells and larger)."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 45
  penetration: 35
  dodge_reduction: 0
  additional_hit_chance: 30
  recoil: 0
  max_range: 30
  ammo: 5
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 3
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "d03f1b89fa9945c3b4f48f8f9b140853"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SniperRifleMammonthkiller_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - NewTrashLoot: AdeptusMechanicus_SecretRoomContainer_Locked"
  sources: "Unit - ExportedPregens: Uralon41RT_ExportedPregen"
}
weapon {
  guid: "8b7f01112edf4b9a90239b544cf667d2"
  blueprint_name: "StarPoison_Hexrifle_Item"
  name_shared_key: "75c31604-d3c7-4030-b967-691d3ea74a48"
  description_key: "ccdd2610-ac2d-4ad2-964e-522bdf528580"
  description: "This rifle inflicts {g|Encyclopedia:FatiguedEffect}fatigued{/g} and {g|Encyclopedia:SlowedEffect}slowed{/g} on the target."
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 19
  max_damage: 29
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 25
  recoil: 10
  max_range: 30
  ammo: 4
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SplinterRifle_SingleShot_Ability"
    ability_bp: "3fbac3a9c61742d790e0a76ea43faefd"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_actions: "918fd1e77a74440eb5a8ecc1ab45a4e2"
    on_hit_action_name: "StarPoison_Hexrifle_AbilityAdditionalEffect"
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "PreciseShotSplinterRifle_Ability"
    ability_bp: "083b3e6ce885487089638ca969070c03"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_actions: "918fd1e77a74440eb5a8ecc1ab45a4e2"
    on_hit_action_name: "StarPoison_Hexrifle_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Splinter_Shot_AbilityFXSettings"
    fx_bp: "8d01a96abb6a4db396e88a9c83fc35a1"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "b5fe044e47604f47bf99ebd14440b579"
    bp_name: "DrukhariWeaponProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "53f2c6910b124dc3889608e3eb0cd2ee"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "ViralToxin_Power6_ForWeapon_Feature"
  sources: "Unit - ExportedPregens: Gusev_Jae_26lvl_ExportedPregen"
}
weapon {
  guid: "a21028fb1b3840d5a12ce8ef0a3fc407"
  blueprint_name: "Chapter2_Unique_AeldariSerenityLongRifle_Item"
  name_shared_key: "ce641388-cb98-4aab-b33f-4a2fd877bdb3"
  name: "Silence of Sha\'eil"
  description_shared_key: "c6ded3c0-033b-4615-aa3e-9407aebbf92e"
  description: "Targets {g|Encyclopedia:HitSequenceGlossary}hit{/g} with this weapon must pass a {g|Encyclopedia:WarhammerWillpower}Willpower{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} with a +20 bonus or suffer psychosomatic {g|Encyclopedia:Traumas}trauma{/g} for 1 {g|Encyclopedia:Round}round{/g}."
  category: Basic
  family: Laser
  heavy: false
  two_handed: true
  min_damage: 29
  max_damage: 30
  penetration: 25
  dodge_reduction: 30
  additional_hit_chance: 25
  recoil: 0
  max_range: 36
  ammo: 10
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "LongrifleEnergyBolt_Shot_AbilityFXSettings"
    fx_bp: "49d2c44a4a424ce5b2a7ae8d34fc9949"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: false
    bp: "365ad1a4ef1b4a47be74509c33b2be3b"
    bp_name: "AeldariWeaponProficiencyFeature"
  }
  extra_fact: "df91db4a78a342d59a909f538e98fd6a"
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "89f35ebe2a2c4208a56c53849eab6afa"
  extra_fact_name: "LaserCoverReduce_Feature"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "Chapter2_Unique_AeldariSerenityLongRifle_ Feature"
  sources: "Chest - BoardedShip_Bridge: Drukhari_CapitansChest"
}
weapon {
  guid: "34612ed374a74558815bc594244eb1b2"
  blueprint_name: "Chapter2_Unique_GovernorsSniperRifle_Item"
  name_shared_key: "d35f8cb0-1aab-41fe-a0a5-4a39419d0b68"
  name: "Cruel Fate"
  description_shared_key: "46805497-e79e-4405-b36a-6b1cdca18672"
  description: "This weapon gains +75% {g|Encyclopedia:OverpenetrationFullGlossary}overpenetration{/g}. Whenever the wielder scores a {g|Encyclopedia:CritChancesAndCritDamageGlossary}critical hit{/g}, they regain +1 {g|Encyclopedia:ActionPoints}AP{/g}."
  category: Basic
  family: Solid
  heavy: false
  two_handed: true
  min_damage: 25
  max_damage: 30
  penetration: 35
  dodge_reduction: 10
  additional_hit_chance: 0
  recoil: 0
  max_range: 30
  ammo: 5
  rate_of_fire: 0
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShot_Ability"
    ability_bp: "a489b6d823ef4b86b431aa1d42e385c7"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Custom
    ability_bp_name: "PreciseShot_Ability"
    ability_bp: "8fe7633db25d46a8bebc2868b8acff12"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "BigSniperRifle_AbilityFXSettings"
    fx_bp: "04f07f00d30e42e4927536f2cc198778"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "7712185d9ea049609fda2784a6ca75ce"
  extra_fact: "64a7ae46868440c09d0edadd08e96888"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "SniperRifle_CritDamage_Feature"
  extra_fact_name: "Chapter2_Unique_GovernorsSniperRifle_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - DLC2_FeudalWorld: FW_TrueGovernor"
}

