# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "75eae8904b504e0abf0dfe1ce34ac08f"
  blueprint_name: "ChainSawT1CH2_Item"
  name_shared_key: "a1a3c049-a64c-45e6-bd55-bcc5825446b1"
  name: "Rusty Heavy Rock Saw"
  category: Melee
  family: ChainSaw
  classification: Chainsaw
  heavy: false
  two_handed: true
  min_damage: 5
  max_damage: 8
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 3
  ability1 {
    type: Burst
    ability_bp_name: "ChainsawMeleeAttack_Ability"
    ability_bp: "4d34770f4fff4f1f93417555c29ccca3"
    fx_bp_name: "CircularSaw_AbilityFXSettings"
    fx_bp: "28b46663dab84697867c0f966c662042"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "ChainsawAoEMeleeAttack_Ability"
    ability_bp: "b29d0b8fd1e94ca4825f0a486862d7e4"
    fx_bp_name: "CircularSawAoE_AbilityFXSettings"
    fx_bp: "b427d37703cd4535b48a8c13439e6b46"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Vendor - DrusianChapter2_VendorTable_Base 27PF"
}
weapon {
  guid: "687cdf03a15240ed8cef4015bda9b451"
  blueprint_name: "ChainSawT1CH4_Item"
  name_shared_key: "385a22e2-cfd4-4e7f-8fb7-3b75ffa3904c"
  name: "Well-Maintained Heavy Rock Saw"
  category: Melee
  family: ChainSaw
  classification: Chainsaw
  heavy: false
  two_handed: true
  min_damage: 15
  max_damage: 25
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 4
  ability1 {
    type: Burst
    ability_bp_name: "ChainsawMeleeAttack_Ability"
    ability_bp: "4d34770f4fff4f1f93417555c29ccca3"
    fx_bp_name: "CircularSaw_AbilityFXSettings"
    fx_bp: "28b46663dab84697867c0f966c662042"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "ChainsawAoEMeleeAttack_Ability"
    ability_bp: "b29d0b8fd1e94ca4825f0a486862d7e4"
    fx_bp_name: "CircularSawAoE_AbilityFXSettings"
    fx_bp: "b427d37703cd4535b48a8c13439e6b46"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Chest - LowerTunnels: IL_SF_Loot_Good_Lock"
}
weapon {
  guid: "a80c3102906943e2b26b2b803e8730a7"
  blueprint_name: "ChainsawT2CH4_Item"
  name_shared_key: "385a22e2-cfd4-4e7f-8fb7-3b75ffa3904c"
  name: "Well-Maintained Heavy Rock Saw"
  category: Melee
  family: ChainSaw
  classification: Chainsaw
  heavy: false
  two_handed: true
  min_damage: 12
  max_damage: 16
  penetration: 25
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 4
  ability1 {
    type: Burst
    ability_bp_name: "ChainsawMeleeAttack_Ability"
    ability_bp: "4d34770f4fff4f1f93417555c29ccca3"
    fx_bp_name: "CircularSaw_AbilityFXSettings"
    fx_bp: "28b46663dab84697867c0f966c662042"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "ChainsawAoEMeleeAttack_Ability"
    ability_bp: "b29d0b8fd1e94ca4825f0a486862d7e4"
    fx_bp_name: "CircularSawAoE_AbilityFXSettings"
    fx_bp: "b427d37703cd4535b48a8c13439e6b46"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
}
weapon {
  guid: "84571fa9b1b24c639b0d75f0f18789b6"
  blueprint_name: "ChainSaw_Item"
  name_shared_key: "39f20791-0ee4-4cfe-86f1-de7345dd6a93"
  name: "Heavy Rock Saw"
  category: Melee
  family: ChainSaw
  classification: Chainsaw
  heavy: false
  two_handed: true
  min_damage: 4
  max_damage: 6
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 3
  ability1 {
    type: Burst
    ability_bp_name: "ChainsawMeleeAttack_Ability"
    ability_bp: "4d34770f4fff4f1f93417555c29ccca3"
    fx_bp_name: "CircularSaw_AbilityFXSettings"
    fx_bp: "28b46663dab84697867c0f966c662042"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "ChainsawAoEMeleeAttack_Ability"
    ability_bp: "b29d0b8fd1e94ca4825f0a486862d7e4"
    fx_bp_name: "CircularSawAoE_AbilityFXSettings"
    fx_bp: "b427d37703cd4535b48a8c13439e6b46"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
}
weapon {
  guid: "6c133495b45b49e0bd79cdcb8533b35b"
  blueprint_name: "HardRockSawT1CH4_Item"
  name_shared_key: "e4aad9d1-66cc-46c2-9fb9-7e935b7e17a5"
  name: "Improved Heavy Rock Saw"
  category: Melee
  family: ChainSaw
  classification: Chainsaw
  heavy: false
  two_handed: true
  min_damage: 6
  max_damage: 8
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 4
  ability1 {
    type: Burst
    ability_bp_name: "ChainsawMeleeAttack_Ability"
    ability_bp: "4d34770f4fff4f1f93417555c29ccca3"
    fx_bp_name: "Sword_AbilityFXSettings"
    fx_bp: "a29d9b4bce7449d78fc33c1e5797d028"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "ChainsawAoEMeleeAttack_Ability"
    ability_bp: "b29d0b8fd1e94ca4825f0a486862d7e4"
    fx_bp_name: "Sword_AbilityFXSettings"
    fx_bp: "a29d9b4bce7449d78fc33c1e5797d028"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Vendor - DrusianChapter4_VendorTable_Base 84PF"
}
weapon {
  guid: "7c3341ad9be845e89ce23e7d10ba070a"
  blueprint_name: "HardRockSawT2CH4_Item"
  name_shared_key: "39f20791-0ee4-4cfe-86f1-de7345dd6a93"
  name: "Heavy Rock Saw"
  category: Melee
  family: ChainSaw
  classification: Chainsaw
  heavy: false
  two_handed: true
  min_damage: 7
  max_damage: 9
  penetration: 30
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 5
  ability1 {
    type: Burst
    ability_bp_name: "ChainsawMeleeAttack_Ability"
    ability_bp: "4d34770f4fff4f1f93417555c29ccca3"
    fx_bp_name: "Sword_AbilityFXSettings"
    fx_bp: "a29d9b4bce7449d78fc33c1e5797d028"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "ChainsawAoEMeleeAttack_Ability"
    ability_bp: "b29d0b8fd1e94ca4825f0a486862d7e4"
    fx_bp_name: "Sword_AbilityFXSettings"
    fx_bp: "a29d9b4bce7449d78fc33c1e5797d028"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 125PF"
}
weapon {
  guid: "4f08867f33394819977edd720f57d93a"
  blueprint_name: "HardRockSaw_Item"
  name_key: "e657e476-d0ba-4647-abde-ffe4070cbbf6"
  category: Melee
  family: Primitive
  classification: Chainsaw
  heavy: false
  two_handed: true
  min_damage: 5
  max_damage: 6
  penetration: 45
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 4
  ability1 {
    type: Burst
    ability_bp_name: "ChainsawMeleeAttack_Ability"
    ability_bp: "4d34770f4fff4f1f93417555c29ccca3"
    fx_bp_name: "CircularSaw_AbilityFXSettings"
    fx_bp: "28b46663dab84697867c0f966c662042"
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
}
weapon {
  guid: "a2077f2e36904590aa251821af1c66f1"
  blueprint_name: "HardRockSawUnique1_Item"
  name_shared_key: "1e87d2ce-692a-4fbc-b588-9935da132456"
  name: "Heavy Emergency Cutter"
  description_shared_key: "bc1a2f47-649f-486f-b8fb-a051f9682132"
  description: "Each attack with this saw increases the wielder\'s critical hit damage by +{uip|Damage|af6818977b6b403c9f558c070c156f3f}%. This bonus stacks and lasts until the end of combat."
  category: Melee
  family: ChainSaw
  classification: Chainsaw
  heavy: false
  two_handed: true
  min_damage: 6
  max_damage: 7
  penetration: 50
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 4
  ability1 {
    type: Burst
    ability_bp_name: "ChainsawMeleeAttack_Ability"
    ability_bp: "4d34770f4fff4f1f93417555c29ccca3"
    fx_bp_name: "CircularSaw_AbilityFXSettings"
    fx_bp: "28b46663dab84697867c0f966c662042"
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "af6818977b6b403c9f558c070c156f3f"
  extra_fact_name: "HardRockSawUnique1_Feature"
  sources: "Vendor - ExploratorChapter2_VendorTable_Base 57PF"
}
weapon {
  guid: "68c53ceed84440048feb092e904c7082"
  blueprint_name: "RockDrill_Item"
  name_shared_key: "31277840-8342-46ac-8641-728531c8ad7a"
  name: "Emergency Drill"
  description_shared_key: "d0bd0036-fe00-4b22-a8cb-6fdb422d4a2a"
  description: "This weapon has a special attack called {g|f:3c11c05ae18d4d4a992308b584a388ab}Drilling Strike{/g}."
  category: Melee
  family: ChainSaw
  classification: Chainsaw
  heavy: false
  two_handed: true
  min_damage: 20
  max_damage: 25
  penetration: 40
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 1
  ammo: -1
  rate_of_fire: 3
  ability1 {
    type: Burst
    ability_bp_name: "ChainsawMeleeAttack_Ability"
    ability_bp: "4d34770f4fff4f1f93417555c29ccca3"
    fx_bp_name: "CircularSaw_AbilityFXSettings"
    fx_bp: "28b46663dab84697867c0f966c662042"
    on_hit_action_name: ""
    ap: 2
  }
  ability2 {
    type: Burst
    ability_bp_name: "RockDrillMeleeAttack_Ability"
    ability_bp: "3c11c05ae18d4d4a992308b584a388ab"
    fx_bp_name: "CircularSaw_AbilityFXSettings"
    fx_bp: "28b46663dab84697867c0f966c662042"
    on_hit_action_name: ""
    ap: 7
  }
  ability3 {
    type: Burst
    ability_bp_name: "ChainsawAoEMeleeAttack_Ability"
    ability_bp: "b29d0b8fd1e94ca4825f0a486862d7e4"
    fx_bp_name: "CircularSaw_AbilityFXSettings"
    fx_bp: "28b46663dab84697867c0f966c662042"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  sources: "Vendor - LiegeChapter4_VendorTable_Base 108PF"
}

