# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "14f255683002426282b043f8d9debebc"
  blueprint_name: "CombatShotgunT2CH04_Item"
  name_shared_key: "2c05160e-6594-480f-bba0-27280754bfaf"
  name: "Combat Shotgun"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 18
  max_damage: 24
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - VigilCastle: ImperiumMilitary_VC_AfterBattle"
  sources: "Unit - Ch04_VoidshipBridgeBoarding: HumanBridgeGuard_Ranged_Boarding"
}
weapon {
  guid: "12d75eca428e4b6f9b43d16d35b46ea2"
  blueprint_name: "CombatShotgun_Item"
  name_shared_key: "2c05160e-6594-480f-bba0-27280754bfaf"
  name: "Combat Shotgun"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 18
  max_damage: 22
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - Prison: Drukhari_PrisonPitOwnChest01"
  sources: "Unit - Ch02_DestroyedBlackShip: PossessedOfficer"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverKnivesOutLeader_MeleeRanged_Elite"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedLexmechanic"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedMagosOrdinator"
  sources: "Unit - Ch02_Lair4_TheLure: Lair4GenestealerCultGrenadier"
  sources: "Unit - Ch02_Macrocannon_Psyker_Q1: MacrocannonPossessedGuard"
  sources: "Unit - Ch02_ForgeWorldAndHeart: HeinrixCompanionCopy"
  sources: "Unit - ExportedPregens: Yanus19Abel_ExportedPregen"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch02_TrueMid"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch03_TrueStart"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_22lvl_Overseer"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_22lvl_WithGlaito"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_27lvl_Overseer"
}
weapon {
  guid: "fcaa04148dbe4734bc9b222fc7045152"
  blueprint_name: "FoehammerT2CH2_Item"
  name_key: "ac49ca29-e80e-484e-8941-f8c3d2a8e5bc"
  name: "[Retobi-Pattern] Foehammer"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Pistol
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: false
  min_damage: 11
  max_damage: 21
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunFoehammer_ScatterAbility"
    ability_bp: "9b1465cc069d410884c1f55f0f646079"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Vendor - PirateChapter2_VendorTable_Base 38PF"
}
weapon {
  guid: "1c7a3dcf6afa4b48a7028642e596ab61"
  blueprint_name: "FoehammerT2CH3_Item"
  name_key: "881ad76f-4ed5-4ea0-9358-28faeb487976"
  name: "[Ryza-Pattern] Foehammer"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Pistol
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: false
  min_damage: 15
  max_damage: 23
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunFoehammer_ScatterAbility"
    ability_bp: "9b1465cc069d410884c1f55f0f646079"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - FootfallSlums_LateBy: SafeLoot"
}
weapon {
  guid: "54ad15d26eb34b8c8d8b39d57cde6b0e"
  blueprint_name: "ShotgunDLC2CH4T2_Item"
  name_shared_key: "4912715b-633d-4ae5-80f6-b4b819c06011"
  name: "Advanced Adeptus Arbites Shotgun"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 40
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  extra_fact_name: "ShotgunPush_Feature"
  sources: "Chest - TreasureWorld: Loot_GuardCache_Normal"
  sources: "Unit - ExportedPregens: RT_FORTEASER_2_ExportedPregen"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_38lvl_Overseer"
}
weapon {
  guid: "8556e1820aa44f25a348b807ff854170"
  blueprint_name: "ShotgunT1CH02_Item"
  name_shared_key: "443b8b89-e5df-45b8-a864-4f3be5c775f2"
  name: "Shotgun"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 24
  max_damage: 36
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  extra_fact_name: "ShotgunPush_Feature"
}
weapon {
  guid: "7dc658dc5ad54417a9b2723d43bc8945"
  blueprint_name: "Shotgun_Item"
  name_shared_key: "443b8b89-e5df-45b8-a864-4f3be5c775f2"
  name: "Shotgun"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 15
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - CR0: ImperiumRich_PrologueOD_ClubLockedChest01"
  sources: "Chest - CR33: ImperiumMilitary_PrisonPitTrashWeapon"
  sources: "Chest - DrukhariAttackOnShip: DrukhariAttack_WeaponLootShotgun"
  sources: "Chest - EE_DestroyedBlackShip: Loot_Poor+Uniq - CorpseWithWeapon"
  sources: "Chest - FootFallDock: Loot_Good - EnCorpseV1"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobiliteShotgun_Guard"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobiliteShotgun_GuardFemale"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Ranged_ShotgunZombie"
  sources: "Unit - Ch01_NavisNobiliteStation: NavisNobilite_Ranged_ShotgunZombieFemale"
  sources: "Unit - Ch01_Starport: StarPortSolider"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsCultistLeader"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsCultistLeader02"
  sources: "Unit - Ch02_AgriWorldJungle: JungleWorldRebelStunner"
  sources: "Unit - Ch02_FootFallAtrium: FootfallAnverChange_MeleeRanged_Common"
  sources: "Unit - Ch02_FootfallDock: FootfallAnverGrenade_Ranged_Common"
  sources: "Unit - Ch02_FootfallDock: FootfallAnver_MeleeRanged_Common"
  sources: "Unit - Ch02_FootfallDock: Footfall_NobleGuard"
  sources: "Unit - Ch02_FootFallSlums: FootfallAnverArsonistGrenade_Ranged_Common"
  sources: "Unit - Ch02_FootFallSlums: FootfallAnverArsonistGrenade_Ranged_Swarm"
  sources: "Unit - Ch02_FootFallSlums: FootfallAnverArsonistGrenade_Ranged_SwarmQS"
  sources: "Unit - Ch02_FootFallSlums: Footfall_Generic_BanditHeavy"
  sources: "Unit - Ch02_FootFallSlums: Footfall_Generic_Specialist"
  sources: "Unit - Ch02_ForgeWorldAndHeart: CorruptedMagosProvender"
  sources: "Unit - Ch02_LowerDecks: Guard"
  sources: "Unit - Ch02_LowerDecks: Guard_CutsceneNeutral"
  sources: "Unit - Ch02_RandomEncounters: CultisthNurgleRangeRandomEncounter"
  sources: "Unit - Ch02_RandomEncounters: PossessedGuardRandomEncounter"
  sources: "Unit - Ch02_SpaceScavengers: ScavengerCutter"
  sources: "Unit - Ch05_QuarryWorld: QuarryWorld_Guard"
  sources: "Unit - Ch01_TaintedStreets: TaintedStreetsRebel02"
  sources: "Unit - Ch02_SantielsPrideUnderhive: CannibalGirlScout"
  sources: "Unit - OurShipCrew: OurCrewGuard"
  sources: "Unit - Companions: CompanionHeinrixPrototype"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level19_HarmonParty_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level22_NeiliusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: HeinrixCompanion_Level27_CyrusParty_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT_level27_VasyaParty_ExportedPregen"
  sources: "Unit - ExportedPregens: VasiliyAbelar_15LvL_ExportedPregen"
  sources: "Unit - SolomonCompanion: SolomoneCompanion"
}
weapon {
  guid: "18ab1db71b0749188f2cf56b301de967"
  blueprint_name: "ShredderShotgun_Item"
  name_shared_key: "98cccbbf-7d4a-4649-a265-7e3990c0dc08"
  name: "Shredder Shotgun"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 20
  max_damage: 25
  penetration: 5
  dodge_reduction: 20
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - FootfallAtrium: AdeptusMechanicus_GoodLoot03"
  sources: "Unit - Ch02_PenalWorld: GladiatorLeader"
  sources: "Unit - Ch02_SantielsPrideUnderhive: SurvivorLeaderWoman"
  sources: "Unit - Ch02_SantielsPrideUnderhive: WildCannibalLeader"
  sources: "Unit - ExportedPregens: Cassia_Lv38_Chordafight_ExportedPregen"
}
weapon {
  guid: "0f2a18b9d13644f48da34fc5d978a470"
  blueprint_name: "ShardShotgunItem"
  name_key: "13dd5bc2-dac3-47a6-b5a4-89fc007b9832"
  name: "Shard Shotgun"
  description_key: "8fc058ae-bdae-47d3-96f9-ecc70e71a651"
  description: "Targets {g|Encyclopedia:HitSequenceGlossary}hit{/g} with this shotgun must pass a {g|Encyclopedia:WarhammerToughness}Toughness{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} or become poisoned, suffering {g|Encyclopedia:ToxinEffect}toxin{/g} (8) {g|Encyclopedia:DamageGlossary}damage{/g} each {g|Encyclopedia:Turn}turn{/g}."
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 24
  max_damage: 34
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 4
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunRending_ScatterAbility"
    ability_bp: "c39ff72671eb48bbafde513d8ac208c7"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "0f511a70cfdc4282ae3dc14113b4da0c"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact: "afd622602e914b918712c7a57630308e"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "ViralToxin_Power8_ForWeapon_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  extra_fact_name: "ShardShotgunFeature"
  sources: "Chest - CR33: Drukhari_AngerChest"
  sources: "Unit - HeinrixCompanion: HeinrixCompanion_Ch04_TrueStart"
}
weapon {
  guid: "43e408e752ab419c9f835741552d40e5"
  blueprint_name: "ArbitesFoehammer_Item"
  name_shared_key: "1a37d98b-a59f-4ba2-a336-d09ca8a61611"
  name: "Advanced Adeptus Arbites Foehammer"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Pistol
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: false
  min_damage: 33
  max_damage: 40
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunFoehammer_ScatterAbility"
    ability_bp: "9b1465cc069d410884c1f55f0f646079"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - DLC2_CH01TaintedStreets: TaintedStreets_ArbitesShield_NPC"
  sources: "Unit - DLC2_Ch04_TreasureWorld: TreasureWorld_Arbites_ShieldNShotgun"
  sources: "Unit - Ch01_CommandCenter: CommandCenter_Arbiter_SnieldNPistol"
}
weapon {
  guid: "4ac891a9148847559e468e15f19c7149"
  blueprint_name: "DoubleBarelled_Shotgun_Item"
  name_shared_key: "6413b6d9-5ce2-4af8-8b76-45bd5d4e2c2e"
  name: "Double-Barreled Shotgun"
  description_shared_key: "f75dd90e-9b9b-48c5-bd7b-d8e9ad310ebe"
  description: "This shotgun never misses."
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 70
  max_damage: 100
  penetration: 1
  dodge_reduction: 33
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 2
  rate_of_fire: 2
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunDouplet_ScatterAbility"
    ability_bp: "b161cefca14e4113823323a5b564b335"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "c52f187da70f4c9ca85f1948afa3dace"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "DoubleBarelled_Shotgun_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Vendor - PirateChapter4_VendorTable_Base 99PF"
}
weapon {
  guid: "55c1ef16027a48b2bbf694797e19336b"
  blueprint_name: "Foehammer_Item"
  name_key: "bf7b6312-9be4-4a98-9000-097ddffea172"
  name: "Foehammer"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Pistol
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: false
  min_damage: 9
  max_damage: 14
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunFoehammer_ScatterAbility"
    ability_bp: "9b1465cc069d410884c1f55f0f646079"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - JailPlanetoid: Loot_Uniq - OverseerArsenal"
  sources: "Unit - ExportedPregens: AbelardCompanion_Level15_ExportedPregen"
  sources: "Unit - ExportedPregens: PlayerRT19ChapelPsyker_ExportedPregen"
}
weapon {
  guid: "ed88d48af2ca421d9549c91333c3dbb2"
  blueprint_name: "MassiveShotgun_Item"
  name_key: "fbb4cd76-91a5-4bbe-9012-825d78fd268e"
  name: "[Drusus Prime Pattern] Shotgun"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 21
  max_damage: 24
  penetration: 20
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - ExportedPregens: Uralon41RT_ExportedPregen"
  sources: "Vendor - PirateChapter2_VendorTable_Base 47PF"
}
weapon {
  guid: "65e5065d182d49fba7a78e81f02a23d6"
  blueprint_name: "NullifyingShotgun_Item"
  name_key: "0036e7fc-b765-4dd3-9607-67a5e47d23fe"
  name: "Nullifying Shotgun"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 24
  max_damage: 31
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - Ch02_Lair3: Lair3RebelLeader3"
  sources: "Unit - ExportedPregens: zin_22_ArgentaCompanion_ExportedPregen"
}
weapon {
  guid: "e0e76a258d844385a16c9dc602caa316"
  blueprint_name: "PistolShotgunCH04Unique_Item"
  name_shared_key: "28bfc456-68d6-4044-8eeb-5bea0bc53596"
  name: "Bone-Shatterer"
  description_shared_key: "bf878c06-cbe2-4746-9f88-7a087f06227c"
  description: "All types of {g|Encyclopedia:PhysicalDamage}physical damage{/g} dealt to targets {g|Encyclopedia:HitSequenceGlossary}hit{/g} by this shotgun pistol are increased by +33% for 2 {g|Encyclopedia:Round}rounds{/g}."
  category: Pistol
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: false
  min_damage: 27
  max_damage: 40
  penetration: 15
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "19725afdd98242cb9cbe756511db98ef"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "PistolShotgunCH04Unique_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - ExportedPregens: PlayerRT_Level38_OperativeOverseer_ExportedPregen"
  sources: "Vendor - PirateChapter4_VendorTable_Base 63PF"
}
weapon {
  guid: "e45711cd0c3444b4ac4be52fb2e6d5bb"
  blueprint_name: "ShotgunCH01Unique_Item"
  name_key: "a56a8bcf-3e80-4343-8cce-068e6ab987a9"
  name: "Blast Wave"
  description_key: "c044f580-9352-4f72-aeb3-8984788a6dd1"
  description: "Shots from this shotgun {g|Encyclopedia:PushGlossary}push{/g} targets 3 cells away even if the shot misses."
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 15
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 0
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "b0807c5aaa154741bb3ec64e40884f41"
  extra_fact_name: "ShotgunCH01UniquePush_Feature"
  sources: "Unit - Ch01_CommandCenter: Arbites_ch1"
  sources: "Unit - ExportedPregens: zin_22_RT_Operative_ExportedPregen"
}
weapon {
  guid: "6168e8d5d7c44a05b07911f38f5f5a60"
  blueprint_name: "ShotgunCH04Unique_Item"
  name_key: "d7e5f9e7-e76a-4aba-a6f7-843f3a5c6ba1"
  name: "Hailstorm"
  description_key: "e08f6a55-1719-48cc-b086-afbbea338104"
  description: "This shotgun has an increased attack area. Its attacks deal +150% {g|Encyclopedia:DamageGlossary}damage{/g}, but their {g|Encyclopedia:HitSequenceGlossary}hit chance{/g} is decreased by \342\210\22250%."
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 45
  penetration: 0
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "6545a27c1ff241beb96531ba650079e0"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "ShotgunCH04Unique_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - CR25: AdeptusMechanicus_BE_Reward"
}
weapon {
  guid: "385a8305390b4db7bd60d0b63f0e71b4"
  blueprint_name: "Chapter1_Unique_OlReliableShotgun_Item"
  name_shared_key: "b2041a35-415d-4083-be7e-6c672fcb87b9"
  name: "Sturdy Shotgun"
  description_shared_key: "74d068a2-fbb3-4af3-a1f3-2c9907a19d0a"
  description: "The wielder\'s {g|Encyclopedia:CritChancesAndCritDamageGlossary}critical hit chance{/g} is increased by +{uip|Critical Hit Chance|7c4174fdd62040fcb6e48ca751ef635b}% and {g|Encyclopedia:ArmourPenetration}armour penetration{/g} \342\200\224 by +{uip|Penetration|7c4174fdd62040fcb6e48ca751ef635b}% against adjacent targets."
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 7
  max_damage: 10
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact: "7c4174fdd62040fcb6e48ca751ef635b"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  extra_fact_name: "Chapter1_Unique_OlReliableShotgun_Feature"
  sources: "Chest - TaintedStreets: ImperiumMilitary_GoodLoot01_DLC2"
}
weapon {
  guid: "37b8c2e5935a433d94c9b1a0155bc9e1"
  blueprint_name: "Chapter2_Unique_ConcentrationControlShotgun_Item"
  name_shared_key: "ca23b40f-838a-4a47-af99-f25d60fe3afc"
  name: "Crescendo"
  description_shared_key: "b8a4f622-3fc1-4582-8ad4-f2d4592811bf"
  description: "When the wielder {g|Encyclopedia:Parry}parries{/g} an attack or {g|Encyclopedia:HitSequenceGlossary}hits{/g} 2 or more enemies with this shotgun\'s {g|Encyclopedia:RangeAreaAttacksGlossary}ranged area attack{/g}, they gain +1 attack until the start of their next {g|Encyclopedia:Turn}turn{/g}. Does not stack."
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 20
  max_damage: 23
  penetration: 10
  dodge_reduction: 5
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact: "7563ee99c3d74989adbae3995bfbb304"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  extra_fact_name: "Chapter2_Unique_ConcentrationControlShotgun_Feature"
  sources: "Chest - BoardedShip: AdeptusMechanicus_ClosedLittleRoomChest"
  sources: "Unit - ExportedPregens: Solomorne_LvL28_Varl1n_v2_ExportedPregen"
  sources: "Unit - ExportedPregens: Solomorne_LvL28_Varl1n_v2_ExportedPregen_OLD"
}
weapon {
  guid: "ed2cfcc90df8492cb4ccce434020930d"
  blueprint_name: "Chapter3_Pattern_Shotgun_Item"
  name_shared_key: "fa82ecf8-7865-4a23-bb35-265b06555fc3"
  name: "[Mars-Pattern] Shotgun"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 27
  max_damage: 35
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - Prison: Drukhari_DLC2_PrisonPitOwnChest"
  sources: "Vendor - PitBossChapter3_VendorTable_Base 0PF"
}
weapon {
  guid: "5393f6f94e4840e48dd4eec214e7c478"
  blueprint_name: "Chapter3_Unique_ViglisPistol_Item"
  name_shared_key: "ebc25bb6-f708-4078-9b0d-4a115ce2bcb7"
  name: "Bloody Vigil"
  description_shared_key: "9a59980a-5971-4ad9-b392-e60d762ebc9a"
  description: "The first {g|f:2162ce26f6db4cd1b748a4105c364ddb}Fulminating Shot{/g}, {g|f:027e75ab89364049b844a720feca85ec}Grisly Adjudication{/g}, or {g|f:def7164545244af28d52cd38d0502525}Double Slug{/g} from this weapon per {g|Encyclopedia:Turn}turn{/g} costs 1 {g|Encyclopedia:ActionPoints}AP{/g} and gains an additional +{uip|Critical Hit Chance|08e2ca4d59134bb58ca1e5fa7221eb58}% {g|Encyclopedia:CritChancesAndCritDamageGlossary}critical hit chance{/g}."
  category: Pistol
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: false
  min_damage: 25
  max_damage: 30
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunFoehammer_ScatterAbility"
    ability_bp: "9b1465cc069d410884c1f55f0f646079"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "08e2ca4d59134bb58ca1e5fa7221eb58"
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "Chapter3_Unique_ViglisPistol_Feature"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - SolomorneCompanion: SOLOMORNE_FORTEASER_ExportedPregen"
}
weapon {
  guid: "ad0c9fe64af14745b640e99ceab505ef"
  blueprint_name: "Chapter4_Pattern_Shotgun_Item"
  name_shared_key: "05b64ff5-e06c-4d28-a7cf-174d2040f2ff"
  name: "[Sol-Pattern] Shotgun"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 35
  max_damage: 45
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Vendor - ExploratorChapter4_VendorTable_Base 71PF"
}
weapon {
  guid: "c2302baa4d4f4c9a9d543c76a2e7bcb6"
  blueprint_name: "Chapter4_Unique_ButNotLeastShotgun_Item"
  name_shared_key: "53ac93ad-10b6-44ff-b6b8-8b836387c2d1"
  name: "Final Chord"
  description_shared_key: "19baca31-5ea2-43ca-9460-0699a1179c93"
  description: "When shooting the last shell from this shotgun, this shot ignores the target\'s {g|Encyclopedia:WarhammerArmourGlossary}armour{/g}. That target must pass an {g|Encyclopedia:WarhammerAgility}Agility{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} or become {g|Encyclopedia:ImmobilisedEffect}immobilised{/g}."
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 40
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 4
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact: "4b5f770887264aae8f3c9546bd7b4efc"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  extra_fact_name: "Chapter4_Unique_ButNotLeastShotgun_Feature"
  sources: "Unit - ExportedPregens: Solomorne_LvL38_Varl1n_v2_ExportedPregen"
  sources: "Unit - ExportedPregens: Solomorne_LvL38_Varl1n_v2_ExportedPregen_OLD"
  sources: "Vendor - PirateChapter4_VendorTable_Base 122PF"
}
weapon {
  guid: "88a7c325e86246fc9a6990295b0a6fc3"
  blueprint_name: "Chapter4_Unique_ScopedShotgun_Item"
  name_shared_key: "6c53a30b-4f8c-43f6-aec2-bcb2a75f4762"
  name: "Scoped Shotgun"
  description_shared_key: "bad7a1f4-147e-40d0-8cbd-8c02c8e03f34"
  description: "This weapon has an additional single-target attack that deals double damage and {g|Encyclopedia:PushGlossary}pushes{/g} the target 5 cells away. For this attack, the minimal firing range is 2 cells, and the {g|Encyclopedia:Range}effective range{/g} is increased by +5."
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 35
  max_damage: 40
  penetration: 10
  dodge_reduction: 10
  additional_hit_chance: 5
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: SingleShot
    ability_bp_name: "Chapter4_Unique_ScopedShotgun_SingleShot_Ability"
    ability_bp: "de185fe713514822bbd1d7bc7e9db761"
    fx_bp_name: "Bolter_BoltShot_AbilityFXSettings"
    fx_bp: "51440c65ca9048d9bc2765dcbaf9f83f"
    on_hit_action_name: ""
    ap: 1
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact: "40803df9762a406a8aea7d2c8d2316ea"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  extra_fact_name: "Chapter4_Unique_ScopedShotgun_Feature"
  sources: "Chest - TreasureWorld: Loot_Arbitor_Good"
  sources: "Unit - ExportedPregens: Solomorne_LvL40_Varl1n_v2_ExportedPregen"
  sources: "Unit - ExportedPregens: Solomorne_LvL40_Varl1n_v2_ExportedPregen_OLD"
}
weapon {
  guid: "d110df1a16bd46ef8a5c9bdf885aad15"
  blueprint_name: "Chapter4_Unique_UnderarmFoehammer_Item"
  name_shared_key: "5b976430-ed26-4e26-8007-3aa52f049804"
  name: "Arbites Underarm Foehammer"
  description_shared_key: "446c2fb9-5633-4026-8084-fb0f27b23f4f"
  description: "When the wielder kills the target with a {g|Encyclopedia:MeleeAttacksGlossary}melee attack{/g} for the first time in a {g|Encyclopedia:Round}round{/g}, they gain +1 free ranged attack from this weapon until the end of their {g|Encyclopedia:Turn}turn{/g}."
  category: Pistol
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: false
  min_damage: 30
  max_damage: 40
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunFoehammer_ScatterAbility"
    ability_bp: "9b1465cc069d410884c1f55f0f646079"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "2a94d897a2a140c0915900154065181f"
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "Chapter4_Unique_UnderarmFoehammer_Feature"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Vendor - LiegeChapter4_VendorTable_Base 120PF"
}
weapon {
  guid: "4a5f53359ab84866a3f722f8f820a8f9"
  blueprint_name: "Chapter5_Unique_FullAutoShotgun_Item"
  name_shared_key: "1a07f208-a14e-49b0-953c-9a7ab8501c7b"
  name: "Full-Auto Shotgun"
  description_shared_key: "1f4ca2c5-59ff-455f-8cfc-fe46f8376a3f"
  description: "This weapon has a {g|Encyclopedia:BurstAttacksGlossary}burst{/g} attack (4 {g|Encyclopedia:ActionPoints}AP{/g}) with a {g|Encyclopedia:RateOfFire}rate of fire{/g} equal to the number of shells in the magazine. When the wielder uses it, they become {g|Encyclopedia:StaggeredEffect}staggered{/g} for 1 {g|Encyclopedia:Round}round{/g}. {g|Encyclopedia:Reload}Reloading{/g} costs 3 AP."
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 45
  max_damage: 55
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 6
  rate_of_fire: 6
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Burst
    ability_bp_name: "BurstFire_Ability"
    ability_bp: "1cdd00b349324e7f958a8cb1dfcde2fe"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 4
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact: "dddfcccfca1b43d09d3adbef433787f5"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  extra_fact_name: "Chapter5_Unique_FullAutoShotgun_Feature"
  sources: "Chest - EpitaphEntrance: AdeptusMechanicus_Corpse_DLC2"
}
weapon {
  guid: "414a941ed21c4602a2b4555f43b811df"
  blueprint_name: "Chapter5_Unique_RackFoehammer_Item"
  name_shared_key: "5103630f-3ee1-44d8-9611-d8866ba3a4bb"
  name: "The Rack"
  description_shared_key: "8371eabd-ec33-49f9-a70a-d0d62d654153"
  description: "The wielder can make a free attack with this weapon if they shot from {g|f:48f5a4051c0c4cf691c84cb27b6876a3}the Ruin{/g} on the same {g|Encyclopedia:Turn}turn{/g}."
  category: Pistol
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: false
  min_damage: 35
  max_damage: 40
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunFoehammer_ScatterAbility"
    ability_bp: "9b1465cc069d410884c1f55f0f646079"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "4aae129e52984d4fac819d2a723e9c93"
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "Chapter5_Unique_RackFoehammer_Feature"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - EpitaphEntrance: AdeptusMechanicus_Chest_DLC2"
}
weapon {
  guid: "48f5a4051c0c4cf691c84cb27b6876a3"
  blueprint_name: "Chapter5_Unique_RuinFoehammer_Item"
  name_shared_key: "14844bb3-9471-49ec-ad54-316044316780"
  name: "The Ruin"
  description_shared_key: "fb7cc554-38ab-498b-84e9-4535b6d37d6e"
  description: "The wielder can make a free attack with this weapon if they shot from {g|f:414a941ed21c4602a2b4555f43b811df}the Rack{/g} on the same {g|Encyclopedia:Turn}turn{/g}."
  category: Pistol
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: false
  min_damage: 35
  max_damage: 40
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunFoehammer_ScatterAbility"
    ability_bp: "9b1465cc069d410884c1f55f0f646079"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "95c2fdd6912146a6b24a1c7b2dd602ea"
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "Chapter5_Unique_RuinFoehammer_Feature"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Chest - EpitaphEntrance: AdeptusMechanicus_Chest_DLC2"
}
weapon {
  guid: "975d778db625472ca9e9fdcf3bcc378a"
  blueprint_name: "Solomorne_Foehammer_Item"
  name_shared_key: "928665e7-0758-45b5-95e7-7b10667d8d34"
  name: "Adeptus Arbites Foehammer"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Pistol
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: false
  min_damage: 12
  max_damage: 20
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 6
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "ShotgunFoehammer_ScatterAbility"
    ability_bp: "9b1465cc069d410884c1f55f0f646079"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 1
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - DLC2_CH01_StarPort: SolomorneCompanion_22lvl_OverseerNPC"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_15lvl_Test"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_NPC_Boarding"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_NPC_Ch01_CommandCenter"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_NPC_Ch01_StarPort_Combat"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_NPC_Ch01_TaintedStreets"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_NPC_Ch04_PenalWorld"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_NPC_FootFall"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_PetOwner_Eagle"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_PetOwner_Mastiff"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_PetOwner_Raven"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_PetOwner_Swarm"
}
weapon {
  guid: "1b828df3c7064be7910020678116ea0d"
  blueprint_name: "Solomorne_Shotgun_Item"
  name_shared_key: "ce12ac9e-bee3-4d2f-9e2e-7b54e68a18d0"
  name: "Adeptus Arbites Shotgun"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 13
  max_damage: 22
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
  sources: "Unit - Ch01_CommandCenter: Arbites_ch1"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_15lvl_Test"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_NPC_BoardingBolter"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_NPC_Ch01_StarPort_Combat"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_NPC_Ch04_PenalWorld"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_NPC_FootFall"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_PetOwner_Eagle"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_PetOwner_Mastiff"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_PetOwner_Raven"
  sources: "Unit - SolomorneCompanion: SolomorneCompanion_PetOwner_Swarm"
  sources: "Unit - SolomorneCompanion: SOLOMORNE_FORTEASER_ExportedPregen"
}
weapon {
  guid: "05b6b57b89ef426fa51f79b1105a116b"
  blueprint_name: "WithoutDLC2_ArbitesShotgun_Item"
  name_shared_key: "9edb5cdc-a927-4908-b3dc-0f6342e9e2cc"
  description_shared_key: "e40bae2c-ee7c-4c05-9e9b-f8e86af5b047"
  description: "<i>Shotguns knock enemies back when shot at {g|Encyclopedia:Range}effective range{/g}.</i>"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 12
  max_damage: 15
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterAbility"
    ability_bp: "160d6a1414d043598bedb261577a24e0"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "52113ebaef8c44798641e08788daa40d"
  extra_fact: "3af882215424458592fc0884ef0c82c4"
  extra_fact_name: "ShotgunPush_Feature"
  extra_fact_name: "SolidProjectileWeapon_Feature"
}
weapon {
  guid: "0e192a942a344182a04d606216a58c5a"
  blueprint_name: "ShotgunTest_Prototype2_Item"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 18
  max_damage: 24
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterNoPushAbility"
    ability_bp: "261451cdd7ab4accb849c8ab1e7521f4"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterPushAbility"
    ability_bp: "2d2e2ac2035047989e563d1683537718"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_actions: "46ce16c99d454f5ea69a838e76ec6311"
    on_hit_action_name: "ShotgunTest_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "3d22cdd9a08e4f7bbe1e41c92409ae0c"
  extra_fact_name: "ShotgunTest_Feature2"
}
weapon {
  guid: "32a6b98335b5466d9ba9315e4084f567"
  blueprint_name: "ShotgunTest_Prototype_Item"
  category: Basic
  family: Solid
  classification: Shotgun
  heavy: false
  two_handed: true
  min_damage: 18
  max_damage: 24
  penetration: 10
  dodge_reduction: 0
  additional_hit_chance: 0
  recoil: 0
  max_range: 7
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterNoPushAbility"
    ability_bp: "261451cdd7ab4accb849c8ab1e7521f4"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_action_name: ""
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Shotgun_ScatterPushAbility"
    ability_bp: "2d2e2ac2035047989e563d1683537718"
    fx_bp_name: "Shotgun_Shot_AbilityFXSettings"
    fx_bp: "ffc8362ff31744ceb7975074da52bf15"
    on_hit_actions: "46ce16c99d454f5ea69a838e76ec6311"
    on_hit_action_name: "ShotgunTest_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 2
  }
  fact_requirement {
    all: false
    negate: true
    bp: "950565a69d144391897cdc0024747755"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp_name: "SpaceMarineEquipment_Proficiency"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "AeldariArmourProficiencyFeature"
  }
  extra_fact: "15910485fc0349adab996dc0e11a632e"
  extra_fact_name: "ShotgunTest_Feature"
}

