# proto-file: proto/weapon/Weapon.proto
# proto-message: weapon.WeaponList

weapon {
  guid: "8e678409153040e99a8ff77a6a7f9db4"
  blueprint_name: "WebberCH4Unique_Item"
  name_key: "cd292ed3-5ee5-422f-8f36-20ba56e679b5"
  name: "Strangler Webber"
  description_key: "4a33e45c-1968-47d9-9df2-8af9a023f454"
  description: "In addition to the webber attack effects, the target suffers a \342\210\22220 penalty to Weapon Skill and cannot perform attacks of opportunity. These penalties last for 2 rounds."
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 30
  max_damage: 40
  penetration: 0
  dodge_reduction: 10
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShotWebber_Ability"
    ability_bp: "f32ef0db1e7144af865b7649d42d2368"
    fx_bp_name: "Webber_SingleShot_AbilityFXSettings"
    fx_bp: "924913f27d394dc5b15321c765159787"
    on_hit_actions: "225864e2944347b5b60ee069deaac4f7"
    on_hit_action_name: "WebberCH4Unique_AbilityAdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Webber_AoEAbility"
    ability_bp: "52d98e3eda934168b6c60e8670546a1d"
    fx_bp_name: "Webber_AoEShot_AbilityFXSettings"
    fx_bp: "5ad2da88903149d797ec05505e7ca14d"
    on_hit_actions: "225864e2944347b5b60ee069deaac4f7"
    on_hit_action_name: "WebberCH4Unique_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "AeldariArmourProficiencyFeature"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  sources: "Unit - DLC1_VoidshipBridge: InfernusDaughter"
}
weapon {
  guid: "7d9277c789bf429385bf04f1f078d2a5"
  blueprint_name: "WebberT1CH4_Item"
  name_shared_key: "06429b87-46eb-4031-9ad5-840265627e77"
  name: "Improved Webber"
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 20
  max_damage: 30
  penetration: 0
  dodge_reduction: 10
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShotWebber_Ability"
    ability_bp: "f32ef0db1e7144af865b7649d42d2368"
    fx_bp_name: "Webber_SingleShot_AbilityFXSettings"
    fx_bp: "924913f27d394dc5b15321c765159787"
    on_hit_actions: "7a36c9e33791422880a0b6f9635aaf7f"
    on_hit_action_name: "Webber_AbilityAdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Webber_AoEAbility"
    ability_bp: "52d98e3eda934168b6c60e8670546a1d"
    fx_bp_name: "Webber_AoEShot_AbilityFXSettings"
    fx_bp: "5ad2da88903149d797ec05505e7ca14d"
    on_hit_actions: "7a36c9e33791422880a0b6f9635aaf7f"
    on_hit_action_name: "Webber_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "AeldariArmourProficiencyFeature"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  sources: "Chest - LowerTunnels: IL_SF_Loot_EnforcerSafe"
}
weapon {
  guid: "487b54d66e6e4cddb1915004888669da"
  blueprint_name: "WebberT1_Item"
  name_shared_key: "4b389c31-d039-4e5e-bc7a-a62dee9f72b7"
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 6
  max_damage: 10
  penetration: 0
  dodge_reduction: 5
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShotWebber_Ability"
    ability_bp: "f32ef0db1e7144af865b7649d42d2368"
    fx_bp_name: "Webber_SingleShot_AbilityFXSettings"
    fx_bp: "924913f27d394dc5b15321c765159787"
    on_hit_actions: "7a36c9e33791422880a0b6f9635aaf7f"
    on_hit_action_name: "Webber_AbilityAdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Webber_AoEAbility"
    ability_bp: "52d98e3eda934168b6c60e8670546a1d"
    fx_bp_name: "Webber_AoEShot_AbilityFXSettings"
    fx_bp: "5ad2da88903149d797ec05505e7ca14d"
    on_hit_actions: "7a36c9e33791422880a0b6f9635aaf7f"
    on_hit_action_name: "Webber_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "AeldariArmourProficiencyFeature"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  sources: "Chest - VoidshipReactor: Loot_Webber"
}
weapon {
  guid: "cd61ebbc44d84db6a63aedfa3005f05e"
  blueprint_name: "WebberT2CH4_Item"
  name_shared_key: "9d00d121-c94f-46b9-8402-5aebce7ff92d"
  name: "Well-Maintained Webber"
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 17
  max_damage: 25
  penetration: 0
  dodge_reduction: 10
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShotWebber_Ability"
    ability_bp: "f32ef0db1e7144af865b7649d42d2368"
    fx_bp_name: "Webber_SingleShot_AbilityFXSettings"
    fx_bp: "924913f27d394dc5b15321c765159787"
    on_hit_actions: "7a36c9e33791422880a0b6f9635aaf7f"
    on_hit_action_name: "Webber_AbilityAdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Webber_AoEAbility"
    ability_bp: "52d98e3eda934168b6c60e8670546a1d"
    fx_bp_name: "Webber_AoEShot_AbilityFXSettings"
    fx_bp: "5ad2da88903149d797ec05505e7ca14d"
    on_hit_actions: "7a36c9e33791422880a0b6f9635aaf7f"
    on_hit_action_name: "Webber_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "AeldariArmourProficiencyFeature"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  sources: "Vendor - PirateChapter4_VendorTable_Base 112PF"
}
weapon {
  guid: "1bd52c7f2fd44aaaac159a2e21873961"
  blueprint_name: "Webber_Item"
  name_shared_key: "9e2e4368-4d45-47ea-ad79-189faaf064eb"
  name: "Webber"
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 6
  max_damage: 8
  penetration: 0
  dodge_reduction: 10
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShotWebber_Ability"
    ability_bp: "f32ef0db1e7144af865b7649d42d2368"
    fx_bp_name: "Webber_SingleShot_AbilityFXSettings"
    fx_bp: "924913f27d394dc5b15321c765159787"
    on_hit_actions: "7a36c9e33791422880a0b6f9635aaf7f"
    on_hit_action_name: "Webber_AbilityAdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Webber_AoEAbility"
    ability_bp: "52d98e3eda934168b6c60e8670546a1d"
    fx_bp_name: "Webber_AoEShot_AbilityFXSettings"
    fx_bp: "5ad2da88903149d797ec05505e7ca14d"
    on_hit_actions: "7a36c9e33791422880a0b6f9635aaf7f"
    on_hit_action_name: "Webber_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "AeldariArmourProficiencyFeature"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  sources: "Unit - Ch02_VoidshipTemple: GenestealerWebber_Ranged_VoidshipTempleAmbush"
  sources: "Unit - DLC1_LowerTunnels_StreetFight: GenestealerWebber_Ranged_LowerTunnels"
  sources: "Unit - ExportedPregens: KibellahCompanion_Level25_MikandraParty_ExportedPregen"
  sources: "Vendor - ExploratorChapter2_VendorTable_Base 18PF"
}
weapon {
  guid: "cdc9b6a7f66c4edf82195278fee072de"
  blueprint_name: "Chapter2_Unique_AcidSpitterWebber_Item"
  name_shared_key: "97587703-29b0-4632-a7da-25d6a377a26c"
  name: "Acid Spitter"
  description_shared_key: "3beeb763-ce3e-4432-9cb6-30f828ad5809"
  description: "At the start of their {g|Encyclopedia:Turn}turn{/g}, targets {g|Encyclopedia:ImmobilisedEffect}immobilised{/g} by this webber suffer 10 {g|Encyclopedia:ToxicDamage}toxic damage{/g} and +1 stack of {g|Encyclopedia:MeltingEffect}melting{/g}. Both effects last until the end of combat."
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 6
  max_damage: 7
  penetration: 0
  dodge_reduction: 5
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShotWebber_Ability"
    ability_bp: "f32ef0db1e7144af865b7649d42d2368"
    fx_bp_name: "Webber_SingleShot_AbilityFXSettings"
    fx_bp: "924913f27d394dc5b15321c765159787"
    on_hit_actions: "59976c176f4745b4a8653b310e3ba5e0"
    on_hit_action_name: "Chapter2_Unique_AcidSpitterWebber_AbilityAdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Webber_AoEAbility"
    ability_bp: "52d98e3eda934168b6c60e8670546a1d"
    fx_bp_name: "Webber_AoEShot_AbilityFXSettings"
    fx_bp: "5ad2da88903149d797ec05505e7ca14d"
    on_hit_actions: "59976c176f4745b4a8653b310e3ba5e0"
    on_hit_action_name: "Chapter2_Unique_AcidSpitterWebber_AbilityAdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "AeldariArmourProficiencyFeature"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  sources: "Vendor - PirateChapter2_VendorTable_Base 30PF"
}
weapon {
  guid: "312f8fdbbc0e4d6bb6e3c74535c8e244"
  blueprint_name: "Chapter3_Unique_SpiderWebber_Item"
  name_shared_key: "d53397b7-53a9-4013-9adc-423d3cfc6b35"
  name: "The Spider\'s Web"
  description_shared_key: "7e14a266-ecc9-4818-8e6c-afad2838c268"
  description: "This webber\'s {g|Encyclopedia:AreaOfEffect}area attacks{/g} cost 1 {g|Encyclopedia:ActionPoints}AP{/g}.\\nIf this weapon\'s {g|Encyclopedia:SingleRangedAttacksGlossary}single-shot{/g} attack {g|Encyclopedia:ImmobilisedEffect}immobilises{/g} a target, it must pass an {g|Encyclopedia:WarhammerAgility}Agility{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} with a +20 bonus or suffer {g|Encyclopedia:CantAttackEffect}cannot attack{/g} for 1 {g|Encyclopedia:Round}round{/g}."
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 10
  max_damage: 20
  penetration: 0
  dodge_reduction: 5
  additional_hit_chance: 0
  recoil: 0
  max_range: 6
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShotWebber_Ability"
    ability_bp: "f32ef0db1e7144af865b7649d42d2368"
    fx_bp_name: "Webber_SingleShot_AbilityFXSettings"
    fx_bp: "924913f27d394dc5b15321c765159787"
    on_hit_actions: "7d6ffcab32f341e3885b51e7be3ffb2e"
    on_hit_action_name: "Chapter3_Unique_SpiderWebber_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Webber_AoEAbility"
    ability_bp: "52d98e3eda934168b6c60e8670546a1d"
    fx_bp_name: "Webber_AoEShot_AbilityFXSettings"
    fx_bp: "5ad2da88903149d797ec05505e7ca14d"
    on_hit_actions: "7a36c9e33791422880a0b6f9635aaf7f"
    on_hit_action_name: "Webber_AbilityAdditionalEffect"
    ap: 1
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "AeldariArmourProficiencyFeature"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  sources: "Chest - PrisonLabBottom: Drukhari_Ch03_PrisonLabTrash04_DLC2"
}
weapon {
  guid: "1fb0b18e06454e3188eb33e3524ec340"
  blueprint_name: "Chapter5_Unique_ProtectiveWebber_Item"
  name_shared_key: "8581fc4a-aea4-4434-b9eb-cf8dec0a9a78"
  name: "Pacification Webber"
  description_shared_key: "2b65bb59-0e29-4080-aec2-801600b228a9"
  description: "Targets {g|Encyclopedia:HitSequenceGlossary}hit{/g} by this webber suffer \342\210\22230 {g|Encyclopedia:WarhammerWeaponSkill}Weapon Skill{/g} and {g|Encyclopedia:WarhammerBallisticSkill}Ballistic Skill{/g}. At the start of their {g|Encyclopedia:Turn}turn{/g}, they must pass an {g|Encyclopedia:WarhammerAgility}Agility{/g} {g|Encyclopedia:ResistanceTest}resistance test{/g} with a \342\210\22210 penalty to remove this effect."
  category: Basic
  family: Exotic
  heavy: false
  two_handed: true
  min_damage: 35
  max_damage: 40
  penetration: 0
  dodge_reduction: 10
  additional_hit_chance: 0
  recoil: 0
  max_range: 10
  ammo: 8
  rate_of_fire: 1
  ability1 {
    type: SingleShot
    ability_bp_name: "SingleShotWebber_Ability"
    ability_bp: "f32ef0db1e7144af865b7649d42d2368"
    fx_bp_name: "Webber_SingleShot_AbilityFXSettings"
    fx_bp: "924913f27d394dc5b15321c765159787"
    on_hit_actions: "703ab4e4a5c14b07b6556bf8e3d0d08b"
    on_hit_action_name: "Chapter5_Unique_ProtectiveWebber_AdditionalEffect"
    ap: 1
  }
  ability2 {
    type: AOE
    ability_bp_name: "Webber_AoEAbility"
    ability_bp: "52d98e3eda934168b6c60e8670546a1d"
    fx_bp_name: "Webber_AoEShot_AbilityFXSettings"
    fx_bp: "5ad2da88903149d797ec05505e7ca14d"
    on_hit_actions: "703ab4e4a5c14b07b6556bf8e3d0d08b"
    on_hit_action_name: "Chapter5_Unique_ProtectiveWebber_AdditionalEffect"
    ap: 2
  }
  ability3 {
    type: Reload
    ability_bp_name: "ReloadAbility"
    ability_bp: "98f4a31b68e446ad9c63411c7b349146"
    fx_bp_name: ""
    on_hit_action_name: ""
    ap: 3
  }
  fact_requirement {
    all: false
    negate: true
    bp: "590cb5c394ee4b5eb213121c96063dec"
    bp: "c7a53b43ac5f4f11a1aef612dd3f4f71"
    bp: "950565a69d144391897cdc0024747755"
    bp_name: "AeldariArmourProficiencyFeature"
    bp_name: "DrukhariArmourProficiencyFeature"
    bp_name: "SpaceMarineEquipment_Proficiency"
  }
  sources: "Chest - TechArcGrave_Lair: AdeptusMechanicus_Chests_DLC2"
}

